### PR TITLE
Restructure and complete the LaTeX generator.

### PR DESCRIPTION
**Pull request by FSMaxB**
I'm done restructuring `lib/util/latex.js` and everything related. This isn't perfect but should work for now and be useful.

Changes:
* Remove most of the complexities at the price of slightly more redundancy.
* Define the LaTeX output for things that haven't had any before ( many of the functions and operators )
* Fix ambiguities in the notation
* Decrease interdependencies between the nodes and `lib/util/latex.js`
* Split the LaTeX output of functions (like with `FunctionNode`s) into separate functions so they can be moved to the definitions of each funcion (`lib/function`) in v2.
* Write tests for the LaTeX output of all those functions

This will require more work in the future but I'm very statisfied with the state it is in right now.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks a lot, I will have a look at your code asap (but won't make it tonight...).

**Comment by josdejong** [comment]
@FSMaxB looks good, thanks! And thanks for adding extra unit tests.

I like the simplicity of every function having its own toTex function without "magic".

There is one thing that pops in my mind: is there need to add functions like `ones`, `range`, `resize`, etc, as these use the `defaultToTex`, and the function falls back to `defaultToTex` anyway? And maybe a second sort of `defaultToTex` can be useful for all functions like `\\coth`, `\\cot`, etc, which is the same as `defaultToTex` exept that it prefixes the function name with two backslashes?

**Comment by FSMaxB** [comment]
There is no need to add those functions, but I did this on purpose because this makes clear that a particular LaTeX output is being used intentionally and not because this particular function has been left out. This makes it easier to check if there are functions left that still lack LaTeX output.
 
As for a second `defaultToTex`: My Plan is to move these functions to `lib/function` in v2, so there will be one default that will either throw an exception ( in which case every LaTeX output has to be done explicitly ) or is calling `defaultToTex`. So I thought that everything that doesn't follow the default should be done explicitly.

But I can change both of those depending on your opinion.

**Comment by josdejong** [comment]
I think it is best to do it like you did: have all functions explicitly in the map, so you could easily spot functions which do not have a toTex and probably need attention. I think at runtime it's best to fallback on the `defaultToTex` (for functions added by users), but our unit tests should give an error when any of the built-in functions is missing a `toTex`. Indeed for v2 I think it's best to move the toTex functions to the function file itself.

I was just thinking... it looks like so much repetitive code. Thinking aloud here: how about defining the toTex functions as a template instead? Like:

```js
var defaultTemplate = '${name}\\left(${args}\\right)';
var fns = {
  add:      '\\left({${args[0]}}+{${args[1]}}\\right)',
  subtract: '\\left({${args[0]}}-{${args[1]}}\\right),
  max:      '\\max\\left(${args}\\right)',
  sin:      '\\sin\\left(${args}\\right)',
  fix:      defaultTemplate
  // ...
};

```

With a simple regexp you could replace all `${...}` with the toTex output of either a single argument or all arguments separated by a comma. Not sure how this would work out, and maybe a different syntax for the placeholders is needed to prevent conflicts with LaTeX (I took the ES6 template syntax here). This could even be interesting to offer as public API?

**Comment by FSMaxB** [comment]
Nice idea. I'll look into that. But there's one problem to be solved for this to be possible: Some of the functions require different output depending on the number and/or type of arguments. I'm not sure how this could be represented in a template notation.

**Comment by josdejong** [comment]
Yes indeed. We should keep it simple and not try to do everything with such a template. It may be a very convenient solution for 90% of the cases. For the other we have the callback function giving you full freedom.

**Comment by FSMaxB** [comment]
So a hybrid approach with both template strings and callbacks in the same map. Seems doable. I'll take a look at it this weekend.

**Comment by josdejong** [comment]
Ok cool!

**Comment by josdejong** [comment]
And please stay critical, the code should become simpler in the end, not more complicated :)

**Comment by FSMaxB** [comment]
Well that was easy! It's now possible to use templates of the form `%name%(%0%,%1%)`. What's left is that I port all those callback functions to the template notation.

**Comment by FSMaxB** [comment]
Ok, now you can use `%*%` to get a comma separated list of all arguments and `%%` if you want a percent sign.

**Comment by josdejong** [comment]
Nice! Maybe we have to give the template syntax some more thought but for a first version its nice (it's not something public (yet) so we can freely play around with it). 

If I see it correctly you've not yet replaced all callback functions with templates except for the defaultToTex, or am I overlooking something?

**Comment by FSMaxB** [comment]
Yes, it's not complete yet. I'll tell you when it's ready to pull.

**Comment by josdejong** [comment]
Ok thanks beforehand, take your time :)

**Comment by FSMaxB** [comment]
Ok, now it's ready. I added one more feature to the templates: When there are multiple different LaTeX outputs for different numbers of arguments, you can make an object with the number of arguments as the key and the template or callback as value.

**Comment by josdejong** [comment]
Thanks, I like it! :)

**Pull request merged**
