### PR TITLE
[DON'T MERGE] Use npm esm package to remove need for transpiling on node.

### PR DESCRIPTION
**Pull request by harrysarson**
I created mainly this to have a look at what it would look like and to run all the tests.
I cannot work out if `esm` should dependency or a full one

Upsides:
  - we no longer need to transpile tests before running (maybe they
will be faster?
  - `$ node -e "console.log(require('mathjs/src/main'))"` now works!

I kept the default export of mathjs still pointing to the `lib` directory.

refs: #1371

### CODE REVIEW

**Comment by harrysarson** [comment]
Looking at travis the node tests seem to run about 15 seconds faster now.

**Comment by josdejong** [comment]
:+1:  really cool not having to transpile.

I'm a bit hesitant to delivering non-transpiled code which requires to run through a special hook in order to work. In general I prefer a simple, robust solution which doesn't require any "smart" hooks. 

We could easily start with using it ourselves for debugging purposes, to make our life easier. We can create a separate npm script and index file to start the CLI/REPL via esm. And running tests via esm also doesn't involve any production risks, so that could be an option too if it works nicely with test frameworks (I run tests for example via WebStorm, and source code mapping should work correct).

**Comment by harrysarson** [comment]
> I'm a bit hesitant to delivering non-transpiled code which requires to run through a special hook in order to work. In general I prefer a simple, robust solution which doesn't require any "smart" hooks.

lodash plans to do just this in v5 https://github.com/lodash/lodash/issues/3745, I completely see your point though.

> We could easily start with using it ourselves for debugging purposes, to make our life easier. We can create a separate npm script and index file to start the CLI/REPL via esm. And running tests via esm also doesn't involve any production risks, so that could be an option too if it works nicely with test frameworks (I run tests for example via WebStorm, and source code mapping should work correct).

Let's go with this, I will wait until #1319 lands and then think of the best approach. 👍 

Closing for now...

**Comment by josdejong** [comment]
:+1: Interesting to see the approach of lodash, I think we can learn from that.

**Pull request closed without merging**
