### PR TITLE
custom toTex

### PR DESCRIPTION
**Pull request by FSMaxB**
This is a new pull request, continuing the effort in #298.
I had to make a new pull request because github got confused by my rebases.

This version simplifies the implementation while incorporating your suggestions *and* keeping my solution of passing a map of callbacks ( take a look at the documentation included in this pull request for more details ).

This is ready for review!

About passing a map of callbacks:
1. It allows having multiple maps and merging them together ( you can easily combine callbacks from several sources ).
2. It's a more intuitive UI in my opinion.
3. It's still possible to just pass a single callback if you want to.
4. It's only 9 lines of code and it can be easily replaced by a better solution in v2.

**Update:** I fixed my fix ( see commit message ). ( and the problem with github displaying commits in the wrong order seems to be fixed )

### CODE REVIEW

**Comment by josdejong** [comment]
Looks good. The documentation is very clear! Thanks a lot Max, I like it.

Indeed for v2 we can make it even simpler for the user.

I had one last thought. We now have two solutions. The first is a generic callback handler, which covers *all* cases. The second way is passing a map with identifiers, which right now covers *all* cases too. This map is meant for convenience in my opinion. As we now have this generic callback solution, the convenience solution with the map may not need to cover all cases too. I think that in practice 90% of the users will only want to add a custom `toTex` for their own *functions*. So maybe we could limit the map-passing solution to just support passing *function* names there instead of these more complicated Node identifiers? That would offer even more convenience for this broad use case. And if you want to do more "complicated" things, you can just use a generic callback function and go nuts.

One last detail: I think I would let all private `_toTex` functions only accept a function callback, not the map, and rename the parameter `customFunctions` to `callback`. Only the public facing `toTex` supports a map, and in that case it will create a little wrapper function around the map, and pass this callback function to the private `_toTex` functions. All `_toTex` functions can directly call the `_toTex` of their childs as they know they are always dealing with a callback function. 
It's no big deal to me though, it's fine with me if you want to leave this as it is right now.

**Comment by FSMaxB** [comment]
Your suggestions sound like a good idea. Using function names in the map does increase convenience quite a bit, I'll do that and change the documentation accordingly.

About passing callbacks to the private `_toTex`: The `_toTex` functions need to get the entire map. They don't do anything with it anyways, all they do is to pass them along. But I can change the name to `callback` or `callbacks`.

**Comment by josdejong** [comment]
Changing the `_toTex` argument indeed doesn't make much difference in the implementation, but it simplifies mental model.

**Comment by FSMaxB** [comment]
I'm done. This code is ready to be merged.

**Comment by josdejong** [comment]
Thanks a lot for all your work. I'm really glad with the final result!

**Pull request merged**
