### PR TITLE
Add "mentions" badge

### PR DESCRIPTION
**Pull request by DenisGorbachev**
Sending a PR with the badge - right now it's a static version, just wanted to release it as soon as possible :)

Does it look good?

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for your PR Denis. 

Yes the badge looks good :) The hard-coded ip address looks scary though, I would love to see it pointing to a neat url of a "real" service. And clicking the badge should lead to a page which explains what "mentions" is, how it is measured.

I prefer a complete release over a fast, incomplete release. These badges haven't been there for years, a few days more or less will not make a big difference. I think it's best to add all relevant badges at once and be done with it. Let's create a list with which badges we would like to show (not just the "mentions" one). What are libraries typically measuring in this respect? Some pointers:
- https://www.npmjs.com/package/badges
- https://nodei.co/
- http://badges.github.io/gh-badges/

**Comment by DenisGorbachev** [comment]
@josdejong Sure, let's put some polish on it :) How about mentions-badge.com as a domain name?

As for other badges, how about the following:
* Build status
* Test coverage
* Downloads
* Mentions

?

**Comment by josdejong** [comment]
yes that sounds good. Let's also add a badge with the latest npm version.

- Version: https://img.shields.io/npm/v/mathjs.svg
- Downloads: https://img.shields.io/npm/dm/mathjs.svg
- Mentions / dependencies
- Build status: https://img.shields.io/travis/josdejong/mathjs/master.svg
- Test coverage (not yet available)

I think it will be interesting and most useful to open a discussion at [shields.io](https://github.com/badges/shields) about the "Mentions" metric you want to introduce. You could start your own metrics service but it's more powerful to extend existing ones if possible.

**Comment by josdejong** [comment]
I just came across http://packagequality.com/#?package=mathjs 

[Package Quality](http://packagequality.com/#?package=mathjs)

also interesting?

**Comment by DenisGorbachev** [comment]
Definitely interesting!

Also, visiting packagequality.com made me realize the importance of explaining how the badge works... :)

**Comment by josdejong** [comment]
Will close this PR, it was still open but we already have badges in the README for some time now.

**Pull request closed without merging**
