### PR TITLE
Infer types of arguments more precisely

### PR DESCRIPTION
**Pull request by sylee957**
I changed `args: TArgs` to `args: [...TArgs]` and it makes some differences in how typescript infers the types

I think that it is more useful to infer the types of arguments of math nodes as tuples than arrays
because tuples keep the types of positional arguments, and often expression nodes are built with lots of heterogeneous types,
such as:

```
const node1 = new ConstantNode(2)
const node2 = new SymbolNode('x')
const node3 = new FunctionNode('sqrt', [node2])
const node4 = new OperatorNode('+', 'add', [node1, node3])
```

And now `node4` is inferred as `OperatorNode<"+", "add", [ConstantNode<2>, FunctionNode<string, [SymbolNode]>]>` 
which keeps very precise information about everything about its arguments.
Previously, they were inferred as `OperatorNode<"+", "add", (ConstantNode<2> | FunctionNode<string, SymbolNode[]>)[]>`, which is not very useful.

~I've only made exceptions for `ArrayNode`,
however, I may also change that if it is also useful there too.~

### CODE REVIEW

**Comment by josdejong** [comment]
That is very nice! I don't understand why `[...TArgs]` makes this work but happy to see this improvement.

I think this is not a breaking change, right? It is only a refinement in the types.

Can you implement the same solution for the other relevant Node classes? That would be great.

**Comment by sylee957** [comment]
Fortunatly, I can't find any other nodes with generic parameter `extends MathNode[]` further than these

**Comment by josdejong** [comment]
Ok sounds good, thanks!

**Comment by josdejong** [comment]
Published now in v12.3.1

**Pull request merged**
