### PR TITLE
fix(gamma function): use reflection formula to handle negative values

### PR DESCRIPTION
**Pull request by kmdrGroch**
fixes: #1681

### CODE REVIEW

**Comment by kmdrGroch** [comment]
@josdejong finally :D

**Comment by josdejong** [comment]
Thanks a lot Bartosz. It makes the function indeed bigger but it is very readable. 

And feel free to create a PR refactoring `gamma` if you like :)

**Comment by kmdrGroch** [comment]
I am working on it right now :) I hope it works 🤞🏻

**Comment by josdejong** [comment]
😎

**Comment by josdejong** [comment]
Your fix is published now in `v10.0.1`, thanks again!

**Pull request merged**
