### PR TITLE
Quoted symbols

### PR DESCRIPTION
**Pull request by rianmcguire**
This PR extends the parser to allow arbitrary strings to be parsed as SymbolNodes by quoting them with backquotes (eg. `` `symbol with spaces` + 2 ``). This allows expressions to reference to symbols in the evaluation scope that were previously inaccessible because of their name. Backquotes within symbol names can be escaped with `\`.

If this is a feature you're interested in merging, I'm happy to update the docs too.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Riam. It's an interesting idea, I understand it. I find it important though to keep things simple and straight forward, and therefore I prefer not to support names with spaces in it: it can lead to complications and allowing it doesn't give us much added value in my opinion. 

It may be an idea to validate the values in `scope` though before evaluating: if there are names with spaces, we know they can't be accessed in expressions, therefore we could give a warning or throw an error.

**Comment by josdejong** [comment]
Ok to close this Rian?

**Comment by rianmcguire** [comment]
> Ok to close this Rian?

Yes, no worries. Sorry for the delay in replying.

No argument from me about the benefits of keeping things simple. For our particular use case, we don't have full control of the names in the scope, so we wanted a way to refer to them regardless of the name. We'll maintain this patch ourselves.

**Comment by josdejong** [comment]
Thanks for your feedback :+1: 

Alternatively, it may be possible to put the variables in an object so you can so you can use bracket notation like: 

```js
const scope = {
  myVariables: {}
}
scope.myVariables['symbol with spaces']= 4

math.evaluate('myVariables["symbol with spaces"] + 2', scope) // 6
```

**Pull request closed without merging**
