### PR TITLE
Fix Source Map Location

### LINKED ISSUE #300: Source Maps, Ember, and Mathjs (Not Sitting in a Tree)
I've found the following error when building an Ember project:

```
Build failed.
ENOENT, no such file or directory '/Users/james/xyz/tmp/tree_merger-tmp_dest_dir-WZt9LsZb.tmp/bower_components/mathjs/dist/dist/math.js'
Error: ENOENT, no such file or directory '/Users/james/xyz/tmp/tree_merger-tmp_dest_dir-WZt9LsZb.tmp/bower_components/mathjs/dist/dist/math.js'
  at Error (native)
  at Object.fs.openSync (fs.js:502:18)
  at Object.fs.readFileSync (fs.js:354:15)
  at SourceMap.<anonymous> (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:270:17)
  at Array.map (native)
  at SourceMap._resolveSourcesContent (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:263:27)
  at SourceMap._assimilateExistingMap (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:242:63)
  at SourceMap.<anonymous> (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:216:10)
  at SourceMap._cacheEncoderResults (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:124:16)
  at SourceMap._addMap (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:215:8)
  at SourceMap.addFileSource (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:91:19)
  at SourceMap.addFile (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:69:15)
  at Class.<anonymous> (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:85:21)
  at Array.forEach (native)
  at Class.module.exports.CachingWriter.extend.addFiles (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:78:8)
  at Class.module.exports.CachingWriter.extend.updateCache (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
  at /Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
  at lib$rsvp$$internal$$tryCatch (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:355:11)
```

It seems to me that the problem is that the location for the sourcemap doesn't make much sense insofar that it's assuming the directory structure I'm using. Shouldn't it look sort of like the below?

```
{"version":3,"file":"math.map","sources":["math.js"] <snip>
```

### PR DESCRIPTION
**Pull request by jherdman**
Resolves #300 

I didn't bother updating the dist files, I figured that's usually handled before publishing a new version.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks. Did you try to use the `sourceRoot` option of uglifyjs [described here](https://github.com/mishoo/UglifyJS2#the-simple-way)? That may be a more neat solution than changing the current directory (which could confuse other gulp tasks).

**Comment by jherdman** [comment]
Yeah, I tried this:

```patch
--git a/gulpfile.js b/gulpfile.js
index d87567b..fadea23 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -60,6 +60,7 @@ var webpackConfig = {
 
 var uglifyConfig = {
   outSourceMap: FILE_MAP,
+  sourceRoot: DIST,
   output: {
     comments: /@license/
   }
```

And:

```patch
diff --git a/gulpfile.js b/gulpfile.js
index d87567b..fadea23 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -60,6 +60,7 @@ var webpackConfig = {
 
 var uglifyConfig = {
   outSourceMap: FILE_MAP,
+  sourceRoot: '.',
   output: {
     comments: /@license/
   }
```
To no avail. Any suggestions?

**Comment by josdejong** [comment]
hm, I gave it a little try but no luck either. I have the feeling that there should be a "real" solution though. However it's not really worth spending hours and hours on this. Switching directory to `./dist` is ok I think, though it would be neat to go back to the original directory `..` at the end of the task.

Alternatively, we could run a little regexp on the generated code of the map, replacing `"./dist/math.js"` with `"./math.js"`, but that may be an even uglier hack ;)

**Comment by jherdman** [comment]
> Switching directory to ./dist is ok I think, though it would be neat to go back to the original directory .. at the end of the task.

Did you find that your CWD was changed to dist after running gulp? I found I stayed in my original dir:

```
mathjs [fix-source-map-location] % pwd
/Users/james/Projects/mathjs
mathjs [fix-source-map-location] % gulp
[gulp] Using file /Users/james/Projects/mathjs/gulpfile.js
[gulp] Working directory changed to /Users/james/Projects/mathjs
[gulp] Running 'validate'...
exec: use child_process.execFile instead
[16:32:35] Validation successful: all functions are documented.
[gulp] Finished 'validate' in 404 ms
[gulp] Running 'bundle'...
[16:32:36] bundled ./dist/math.js
[gulp] Finished 'bundle' in 1.04 s
[gulp] Running 'minify'...
[16:32:43] Minified math.min.js
[16:32:43] Mapped math.map
[gulp] Finished 'minify' in 6.92 s
[gulp] Running 'default'...
[gulp] Finished 'default' in 5.1 μs
mathjs [fix-source-map-location●] % pwd
/Users/james/Projects/mathjs
```

**Comment by josdejong** [comment]
Yes, it works right now, but *could* break something in a later stage, in case there would be a task executed after minify which needs the right directory too. 

It's just a habit of mine to want my code to "clean up" afterwards and leave global things as they where beforehand. Just in case.

**Comment by jherdman** [comment]
Cool! I'll add that in tonight.

**Comment by jherdman** [comment]
Fixed!

**Comment by josdejong** [comment]
Thanks James, looks good.

**Pull request merged**
