### PR TITLE
Function to get the operator precedence

### PR DESCRIPTION
**Pull request by FSMaxB**
Adds the following:
* Function `getIdentifier()` for every Node.
* Function `getPrecedence()` for every Node.
* Tests to check those new functions.

See #273

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, that looks good!

There are a few things I'm not yet sure about:
- For robustness, I think the getIdentifier and getPrecedence should throw an error when not implemented or when the identifier is not recognized. So returning `Infinity` as I proposed may not be a good idea, instead the function should throw an error. 
- What's the best place for the precedence list. It feels not so neat to put this in super class Node, which should not know about the sub classes implementing it. Maybe it's more clear to put this in a separate file `preference.js`, but on the other hand this just complicates the code.

what do you think?

**Comment by FSMaxB** [comment]
* How can `getIdentifier` be not implemented? And if so, it can't throw an error because it's not implemented. It could throw an error for `OperatorNode` however if `this.fn` is undefined or empty.
* `getPrecedence` could throw `Error( 'Precedence is not defined for "' + identifier + '".'`. Note that this would require that every call to an unknown node is wrapped in try-catch.
* I could put  the preference list in `lib/expression/preference.js` and add `var precedence = require('../precedence');` to `Node.js`

I'm glad that I'm not the only one to confurse "precedence" with "preference".

**Comment by FSMaxB** [comment]
Ok.
* The precedence list is now in `lib/expression/precedence.js`
* `getPrecedence()` throws an error whenever the given identifier can't be found in the precedence list.
* `OperatorNode.prototype.getIdentifier()` throws an error if `this.fn` isn't a string or is empty.

**Comment by josdejong** [comment]
ah... yeah I mean precedence ;)

We can implement `Node.prototype.getIdentifier` like this to enforce it to be implemented in new types of Nodes:
```js
Node.prototype.getIdentifier = function () {
  throw new Error('getIdentifier not implemented for node ' + this.type);
}
```

For the preference.js file: when only moving the list to a separate file, still used by Node.js, we don't really "solve" this issue. It would require making `getPrecedence(node)` a static function and move it to `precedence.js` too. That way there is no notion at all of this whole precedence function and list in `Node.js`. All implementations of `Node.js` then have to import this file and call the static function `getPrecedence` that way. That's more cumbersome. I'm not sure if that's worth it for "purities" sake, and I'm ok with both.

The error message for `getPrecedence` sounds good. I think we're on the right way with this.

**Comment by FSMaxB** [comment]
Shouldn't the identifier be the node's type by default and only be overloaded if necessary?

As for the "purity". Only implementing `getPrecedence` for those nodes that support it in the first place seems reasonable. I would move it to `preference.js` as a static function an then implement `getPrecedence()` for `AssignmentNode`, `ConditionalNode`, `OperatorNode` and `RangeNode`.

**Comment by FSMaxB** [comment]
I moved `getPrecedence` from Node.js to preference.js and implemented `getPrecedence` for every Node for which a precedence is defined.

Currently the entire precedence list is exposed, should this be private?

**Comment by josdejong** [comment]
Looks good, thanks. 

It's perfectly fine with me to expose the precedence list, the opener stuff is, the easier people can hack all kind of smart things around it. One detail is that it may be more clear to export like this instead:
```js
exports.precedence = precedence;
exports.getPrecedence = function (node) { ... }
```

**Comment by FSMaxB** [comment]
I started reimplementing `toString` and found out that there is more to this than just precedence. There's right associativeness vs. left associativeness and commutativeness etc. which are important for parenthesis.

I'd suggest doing this more generic by renaming `precedence.js` to `operators.js` to be able to add more properties later as they are needed.

**Comment by josdejong** [comment]
That's a good point! Man, this is more complicated than I had expected. But it's good to *finally* get this right.

**Comment by FSMaxB** [comment]
I pushed the corresponding commit. I would say that the getPrecedence function should stay as is as an interface to use but the underlying data structure of the precedence list may be changed later if necessary when implementing toString and toTex.

**Comment by josdejong** [comment]
Did you already implement precedence checks for right associative operators?

**Comment by FSMaxB** [comment]
I started a separate branch which isn't public yet ( also haven't committed anything so far ). I modified the tests and added some new ones regarding parenthesis in toString and I've started rewriting toString in OperatorNode.js. It already does some stoff better than before but still has some regressions.

This is much more complicated than I anticipated, especially stuff like `1-1+1` without brackets in a generic way.

I think this should be done in a new Github Issue.

**Comment by josdejong** [comment]
It's an interesting challenge :D. Ok let's close this PR and continue in a new one. 

I'm not sure which problem you mean with `1-1+1`, in that example there are no parenthesis needed at all.

**Pull request closed without merging**
