### PR TITLE
Matrix LU decomposition with partial pivoting and LU based linear equations solver

### PR DESCRIPTION
**Pull request by rjbaucells**
This pull request adds Matrix LU decomposition with partial pivoting and a LU based linear equations solver.

Syntax (CLI): 

`m = [1, 2, -1; 2, 1, 1; 1, 2, 1];`
`x = lusolve(m, [4; -2; 2])`

Using explicit LUP decomposition:

`m = [1, 2, -1; 2, 1, 1; 1, 2, 1];`
`d = lup(m);`
`x = lusolve(d, [4; -2; 2])` --> Solving linear equations system 1
`y = lusolve(d, [1; 1; 8])`  --> Solving linear equations system 2 (same LUP decomposition)

Algorithms have been optimized for Dense and Sparse Matrices:

`m = matrix([1, 2, -1; 2, 1, 1; 1, 2, 1], "ccs");`
`x = lusolve(m, [4; -2; 2])`

### CODE REVIEW

**Comment by josdejong** [comment]
Awesome, that's an impressive job! Thanks a lot.

It's quite an amount of code. That's no problem, but I'm thinking about how to keep code modular (which is one of the things I want to get right in v2). Right now, most logic is put in `DenseMatrix`, `CcsMatrix`, and `CrsMatrix`. That means that you can't effectively create a custom bundle from math.js containing limited functionality, for example you cannot easily exclude all `lusolve` related code if you just want to do basic arithmetics with matrices. How do you think about this?

**Comment by rjbaucells** [comment]
Yes putting all that code in the Matrix type will make it available for any combination of modules loading the actual matrix type. It is a compromise, you could break the code in different files but that will make maintenance worst and more difficult to understand. Simple refactoring of a type will be spread out in many files, leaving one behind will introduce bugs.

It is possible that consumers want to pick individual functions into a package but I do not think that is manageable, that will require to split all type files and manually import the desired ones from the individual functions. I think a better compromise will be by functionality, for example "Linear Algebra", that will load all functions in that category. Still you will have the risk of splitting files and making maintenance worst.

The approach the library was following of putting the actual functionality on the function implementations; for example, `multiply()` used to have the `Matrix` related code embedded into its own file; works fine with the granular packages but has big performance problems since it will work on generic data structures (`matrix.valueOf()`) not taking advantage of the underlying data representation (`CRS` & `CCS`).

What do you think about these points? 

We can continue talking about this topic on #280 since it is related to it.

**Comment by josdejong** [comment]
You have some good arguments about maintainability. On the other hand, endlessly growing the three files of the matrices and putting everything in there isn't good/modular/maintainable either (as a general rule of thumb I think a single file should not contain more than 1000 lines, if it grows further you have to try to split it up). 

We could choose some sort of mixin structures to extend the matrix prototypes, but I'm not really in favor of that: it makes it hard to see what functionality is there and where it is coming from. 

What is left then is moving these functions acting on a matrix (like transpose, diagonal, trace, lup, etc) in separates files of their own, and refactor them into static, pure functions. They then will have to access the "internal" properties of the matrices, which isn't neat from an object oriented point of view (but on the other hand, there is no practical problem here). I don't think there is a problem with sharing here: you can just `require` these functions everywhere you  need it. Also no performance issue, it's just moving the code somewhere and not using `this` anymore, but we still need multiple implementations for the different types of matrices.

I'm not yet happy with either off these options. How do we keep our code modular and maintainable in the long term?...

**Comment by rjbaucells** [comment]
Yes the only option left based on the file size constraint and the mixin strategy problems is static functions. What I do not like about static functions is that functionality is spread among many files, a simple type refactoring is difficult to achieve.

How are we going to load these functions? Suppose we create three files for the `transpose()` implementation, Dense, CRS and CCS formats. The public API `transpose()` function need to load the implementation only if the associated type has been loaded. You could create a package with Dense matrix only so no need to load the other two implementations.

Is this something you want to achieve with the library? 

Is the three implementation functions the way to go? 
Or, 
Is a single big function (`transpose()`) the way to go (for sure with more than 1000 lines in some cases `lup()`)?

Just let me know and I will update the push request accordingly.

**Comment by rjbaucells** [comment]
I started doing some modifications to `lup()` to see how the implementation could be detached from the actual types and I found more things I did not think about before:

The implementation of `CcsMatrix.prototype.lup = function () {}` invoke internal `CcsMatrix` operations not part of the prototype definition like `var _forEachRow = function (j, values, index, ptr, callback) {}`, `var _swapRows = function (x, y, columns, values, index, ptr) {}` and `var _getValueIndex = function(i, top, bottom, index) {}`. 

This functions do the core functionality, they are designed to be called by functions that are part of the prototype definition and they should not be invoked from the outside world. These functions do not validate parameters since they are always wrapped by another that is in charge of that functionality, they are designed to do quick small operations (see one example at [`CcsMatrix` line 376](https://github.com/josdejong/mathjs/blob/v2/lib/type/matrix/CcsMatrix.js#L376))

Do we want those operations as part of the `CcsMatrix` prototype definition?

How can we re-use these operations from static functions?

**Comment by josdejong** [comment]
hm. Basically this is about whether to group functionality per `type` or per `function`. Let me give this some more thought this weekend.

**Comment by josdejong** [comment]
@rjbaucells I've put a reply on this topic here: https://github.com/josdejong/mathjs/issues/280#issuecomment-92100399. There are pros and cons for both options. I would like to go for the functional approach rather than the object oriented solution, thus storing functionality per function rather than per type. 

If you can agree with this approach, it would be great if you could restructure your code like this. Static functions like `forwardSubstitution`, `backwardSubstitution`, `lup`, etc, possibly each in their own file. I think it's fine to keep small util functions such as `swapRows` in the Matrix prototypes. In total it requires more bookkeeping due to more files, but such a functional approach can also make it easier testable and gives the modularity that we want. I'm not so afraid for any refactorings of data types: thanks to the unit tests and using a modern IDE like WebStorm this shouldn't be a big deal.

btw. I'm really glad with the equation solver you've implemented, it really brings math.js to the next level!!

**Comment by rjbaucells** [comment]
@josdejong I have updated the push request with the static functions implementation. Please review it and let me know.

**Comment by josdejong** [comment]
Thanks a lot! Looks good, I will merge your PR now.

**Pull request merged**
