### PR TITLE
Improve CI testing

### PR DESCRIPTION
**Pull request by harrysarson**
Reduces number of build stages (3 -> 2) and adds testing of the mathjs bundle.

I could not find a way to go to one build stage without running linting, browser tests and the bundle test on all three versions of node. This repetition would slow the CI run down to the point where it defeats the point of parallelising these tests.

### CODE REVIEW

**Comment by josdejong** [comment]
Nice improvement Harry!

Shouldn't all tests under "other" run on node 8 (LTS)? Some run on node 6

**Comment by harrysarson** [comment]
They should.

Additionally, can you think of a better name than other?

**Comment by josdejong** [comment]
> They should.

:+1: 

> Additionally, can you think of a better name than other?

Maybe "Nodejs and bundle tests" and "Linting and browser tests". I can't come up with a single word explaining everything the stage does.

**Comment by harrysarson** [comment]
Sorry, a lot of commits here. You got to push before travis will tell you if it works or not.

I am happy with how it is now. Thinking about it I reckon the name 'other' is decent and fairly clear.

**Comment by josdejong** [comment]
looks really neat, nice improvement!

How do you think about doing all 7 tests in parallel in a single stage?

**Comment by harrysarson** [comment]
If it's possible then let's do it :+1:

I don't think it is though but I might be wrong.

**Comment by josdejong** [comment]
ah, well, I have no clue, it's just an idea :)

**Pull request merged**
