### PR TITLE
Hyperexecute Integrations

### PR DESCRIPTION
**Pull request by gauravchawhan**
Integration with the Lambdatest Hyperexecute

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @gauravchawhan for working out this PR. Some questions:

1. Using Lambdatest Hyperexecute would replace BrowserStack, right? So we can consider Hyperexecute when it is faster or more reliable for example. Are there other advantages?
2. What is needed to work out this solution so it actually replaces BrowserStack? Right now it doesn't run. I've tried to make it work in branch [gauravchawhan-develop](https://github.com/josdejong/mathjs/tree/gauravchawhan-develop), but that doesn't work, see https://github.com/josdejong/mathjs/actions/runs/3912568690/jobs/6687370464

**Comment by josdejong** [comment]
@gauravchawhan I see you made some additional commits, what is the status right now?

**Comment by gauravchawhan** [comment]
Hi Jos,

Thanks for your patience. 
We are currently working on the solution for this and will get back to you soon. I will personally keep you posted on the updates. 

To answer your question, yes Hyperexecute was built to solve end to end testing challenges like speed, reliability, triaging and much more. You can check out our features and what they do [here](https://www.lambdatest.com/support/docs/key-features-of-hyperexecute/). Alternatively, I would love to get on a call and take you through the advantages of using Hyperexecute and how its a complete solution for you.

Looking forward to hearing from you. 

Best regards,
@gauravchawhan

**Comment by josdejong** [comment]
👍 I'll await your updates. The goal of Hyperexecute is clear to me, let's see how it does in practice :)

**Comment by SparshKesari** [comment]
Hi @josdejong,

Can you please try with the latest changes in the PR, let us know if you face any issues.

**Comment by josdejong** [comment]
Thanks, I'll try it out tomorrow, I see GitHub workflow doesn't directly pick up the new Hyperexecute workflow.

**Comment by josdejong** [comment]
First: thanks for helping met get the tests running @SparshKesari  and @gauravchawhan! I've merged the PR in develop and can run the tests now (triggered manually). 

The first run did timeout after 15 minutes (on my machine, runing the 5172 tests takes 4 seconds):

https://github.com/josdejong/mathjs/actions/runs/11476151346/job/31935529424

Any idea why it times out?

**Comment by SparshKesari** [comment]
checking @josdejong 

cc: @gauravchawhan

**Pull request merged**
