### PR TITLE
Split unit

### PR DESCRIPTION
**Pull request by ericman314**

### CODE REVIEW

**Comment by FSMaxB** [comment]
Now I understand. Letting the user decide how to split the units is much easier than having a list of unit systems that can be split automatically.

**Comment by josdejong** [comment]
Nice job, thanks!

**Comment by josdejong** [comment]
Will do a release right now (wanted to do that last weekend already but I didn't make it, sorry for that).

**Comment by josdejong** [comment]
`v3.4.0` is now available on npm :)

**Pull request merged**
