### PR TITLE
New ParenthesisNode to represent parentheses in the node tree

### PR DESCRIPTION
**Pull request by FSMaxB**
Today I noticed that I need a way to represent parentheses in the node tree, so I started implementing a `ParenthesisNode` ( which is now ready, faster than expected ).

What this changes:
This adds a new configuration option called `parenthesis` that can be either `'automatic'` or '`manual`'. `automatic` is the way it works right now. `manual` parses every pair or parentheses as a `ParenthesisNode`. `automatic` is the default.

I don't know if this feature is something that you want in your library.

Why I think this feature is needed: There are cases where an application wants to display a formula that a user types in and present it in more or less the same way as the user typed it in without sanitizing parentheses.

This already works, but I'd like to add some more tests. Please take a look and tell me what you think.

### CODE REVIEW

**Comment by Lakedaemon** [comment]
On 04/22/2015 09:08 PM, Max Bruckner wrote:
>
> Today I noticed that I need a way to represent parentheses in the node 
> tree, so I started implementing a |ParenthesisNode| ( which is now 
> ready, faster than expected ).
>
> What this changes:
> This adds a new configuration option called |parenthesis| that can be 
> either |'automatic'| or '|manual|'. |automatic| is the way it works 
> right now. |manual| parses every pair or parentheses as a 
> |ParenthesisNode|. |automatic| is the default.
>
> I don't know if this feature is something that you want in your library.
>
> Why I think this feature is needed: There are cases where an 
> application wants to display a formula that a user types in and 
> present it in more or less the same way as the user typed it in 
> without sanitizing parentheses.
>
Yes, I personnaly need this. :)

In my android app, under the math.js, I want to display the rendered 
math code so the user can check what he types (WYSIWYG).
Having sanitized parentheses in that place would confuse him.

While in lots of other places where I want to display pretty/easily 
readable math results, i would like to use the sanitized parenthesis.


+1 for the dumb and the smart parentheses :)

**Comment by josdejong** [comment]
Yes, I like your idea of explicitly creating a ParenthesisNode, so you do not lose any information after parsing an expression. Afterwards you then have all freedom to represent the parsed expression with either original parentheses or only the necessary parentheses (or even by displaying parentheses for every operator to make it completely unambiguous for everyone like for example [Qalculate!](http://qalculate.sourceforge.net/) does).

 I will have a closer look at your solution tomorrow.

**Comment by FSMaxB** [comment]
Ok, so you're proposing a more generic approach than what I've done in this pull request. But we can discuss this after you read my current solution.

**Comment by josdejong** [comment]
Your code looks good, thanks!

I think the new ParenthesisNode is a good idea. Question is what will be the best way to deal with configuration. The way you solved it now is by making the decision at parse time. I think it may be better to just always parse a ParenthesisNode, so the generated node tree exactly reflects the user input. 

- Suppose you want to remove ParenthesisNodes from a parsed tree, then you can do so using a `transform`.
- For output using `toString` and `toTex`, you would by default get the exact representation from the user (which should be unambiguous). Additionally, we could introduce output options for `toString` and `toTex`, like `node.toString({parenthesis: 'original' | 'auto' | 'always'})` or configure this globally (like you now did with the new config option `parenthesis`).

Btw this would be a breaking change and hence should be implemented for v2.

What do you think?

**Comment by FSMaxB** [comment]
Sounds good in and of itself, but I have to think about how this can be implemented. I don't know how to do this right now.

The biggest problem is propagating the configuration options. I think v2 needs one central place for configuration options with the possibility to overload them ( by passing to `toTex` for example ). I haven't read the v2 code yet, so I can't say anything about that, but before the problem of configuration isn't solved, implementing this in v2 doesn't make sense.

I'd prefer this being merged into v1, then I can work on the necessary ground work in v2 to later incorporate your suggestions.

**Comment by josdejong** [comment]
Ok let's give it a little bit more thought. Get a clear picture on where we want to end up with v2, and then align any improvements in v1 with this final goal.

**Comment by FSMaxB** [comment]
So you're saying we should always represent parentheses in the node tree with the ability to change the parenthesis when using `toString` and `toTex`.

The following changes are required to achieve this:
* Add the new `ParenthesisNode` and change the parser so that it always creates them.
* Make that the current algorithm for calculating necessary parentheses still works. (I hope this only requires traversing down the `ParenthesisNode`s until some other node is found, but I'm not sure. This may become ugly )
* There needs to be a way to pass configuration options on to `toString` and `toTex`. Ideally this can be set in a central way with the possibility to override this. I thing we should come up with a configuration system that allows global configuration that is accessible from everywhere and can be overridden locally.
* Additionally I need to implement a way to always use parentheses. This shouldn't be too hard once the other problems are solved.

**Comment by FSMaxB** [comment]
I built and commited the dist files so if anybody needs this feature right now it can be used.

To be clear: This feature wont make it into mathjs in the current form, the final version will probably work differently, so keep this in mind when using it.

**Comment by josdejong** [comment]
You could put this feature in a separate feature branch for now :)

Indeed how you describe it is what I had in mind: 1-to-1 parsing of the expression, and afterwards you can transform the tree and/or normalize output the way you like. 

We indeed have to put configuration in the global `config` object and make this accessible for the Nodes. We can discuss further in #342.

**Comment by FSMaxB** [comment]
This functionality is now available in the v2 branch. The API is different though.

**Pull request closed without merging**
