### PR TITLE
docs: update pretty print with MathJax

### LINKED ISSUE #2022: docs: upgrade pretty print to mathjax v3
The documentation uses MathJax v2.3 which is 7 years old. Also, MathJax v3 has a completely different API.

If there's interest, I'm happy to make a PR.

### PR DESCRIPTION
**Pull request by pkra**
Upgrades to MathJax v3 and adjusts to new APIs.

Resolves #2022

### CODE REVIEW

**Comment by pkra** [comment]
This might be a bit unconvential. Instead of adding TeX to the DOM and typesetting, it typesets and adds the result. This can lead to slight differences in font-size matching which seemed unimportant here. But I can rewrite it in the old style if you prefer.

**Comment by josdejong** [comment]
Thanks @pkra, looks good 👍

**Comment by josdejong** [comment]
The change in font-size doesn't matter indeed for this example: it's just a minimal example to show you how easy it is to do pretty printing.

**Comment by pkra** [comment]
Thanks, Jos.

**Comment by josdejong** [comment]
Updated example is now published in `v8.0.1`, thanks again Peter

**Pull request merged**
