### PR TITLE
Change types in matrix map() and forEach()

### PR DESCRIPTION
**Pull request by xiaohk**
I believe the second parameter b of the `callback(a, b, c)` of `mat.map(callback)` and `mat.forEach(callback)` should be an index of type `number[]`. This PR aims to change the TypeScript type definition of `callback` signature.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Jay, you're right 👍 

Can you please make the linter happy? It's failing right now due to a missing newline at the end of the file. (run `npm run lint` and/or `npm run format`)

**Comment by xiaohk** [comment]
Sounds good! Just added a new line in https://github.com/josdejong/mathjs/pull/2887/commits/4332cf050920034a512e90e9136e0eb1f2314a68

**Comment by josdejong** [comment]
The fix is published now in `v11.5.1`.

**Comment by xiaohk** [comment]
Thanks! Wow it was fast!

**Pull request merged**
