### PR TITLE
Add Kronecker Product (Direct / Tensor Product)

### PR DESCRIPTION
**Pull request by adamisntdead**
Adds Kronecker Product as math.kron(x, y);

From issue #704

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Adam, I will review your PR tomorrow night or in the worst on Friday.

**Comment by josdejong** [comment]
Thanks, looks good!

There is one thing that may not work as expected right now: 

```
kron(1:4, ones(3, 1))
// RangeError: Vectors with dimensions greater then 2 are not supported expected 
// (Size x = 4, y = 3)
```

reason is that `1:4` is a vector with one dimension and the function expects 2 dimensions. The error is a bit misleading here. This works OK:
```
kron([1:4], ones(3, 1))  // OK
```

What do you think is best here? When the input has 1 dimension wrap it in a second one automatically?

**Comment by adamisntdead** [comment]
Yeah, that could work, I will add it later on and see if that gives the required results.

**Comment by adamisntdead** [comment]
Okay, I added that and put in a unit test, all works fine.
I added it to the documentation for the function so that it's clear that it's being wrapped too

**Comment by josdejong** [comment]
:+1: thanks, nice job!

**Comment by adamisntdead** [comment]
Just realized that won't support complex numbers, gonna fix now and throw another PR

**Pull request merged**
