### PR TITLE
Fix #2463

### LINKED ISSUE #2463: pow(matrix, n) can easily be extended to negative n
The typical meaning of M^(-2) would be inv(M)^2. It would seem reasonable to extend pow(M,n) to negative n in this way. There doesn't seem to be any risk; pow(M,-2) might throw an error if M is noninvertible, but it always throws an error at the moment. Unless some problem with this extension is foreseen, I will extend the definition of pow(M, n) in this way when I get a chance.

### PR DESCRIPTION
**Pull request by HanchaiN**

### CODE REVIEW

**Comment by gwhitney** [comment]
Thank you for the submission! The comment just below createPow in pow.js also needs to be updated, and in the examples there it would be good if at least one of the examples used a negative and/or non-integer exponent. It would also be good if there was a matrix example (not necessarily with negative exponent, either way) in src/expression/embeddedDocs/function/arithmetic/pow.js. If you can make these documentation changes we should be able to move this PR along, thanks!

**Comment by HanchaiN** [comment]
The documentation has been updated, thanks.

**Comment by gwhitney** [comment]
This is looking quite reasonable. Turning on the regression tests in this PR.

**Comment by gwhitney** [comment]
Hmm, there's still a failure in build-and-test; I don't know why, but I can never see the error in these CI reports. But anyway @HanchaiN you can run `npm run build-and-test` locally on your end and see what is up, thanks.

**Comment by josdejong** [comment]
Thanks again @HanchaiN 👍

**Pull request merged**
