### PR TITLE
Range refactoring

### PR DESCRIPTION
**Pull request by dvd101x**
This is just an idea to refactor the function.

### CODE REVIEW

**Comment by josdejong** [comment]
Nice, I like it! 

I think we can merge this PR as-is, or do you have more plans with it? Like merge the number and BigNumber functions together by passing an additional argument `add` 😉?

**Comment by dvd101x** [comment]
I would like to, unfortunately I can't just include `add` in the dependancies, I don't know why.

From that PR if I include `add` I get `Error: Cannot create function "range", some dependencies are missing: "?matrix", "?bignumber", "add".`

**Comment by josdejong** [comment]
(this argument `add` only needs the following implementations: `(a, b) => a + b` for numbers and `(a, b) => a.plus(b)` for BigNumber. Still, I'm not sure if that generalization is worth it)

**Comment by dvd101x** [comment]
I think there are two generalizatoins, `add` and `isPositive`. It's currently working by adding them as dependancies but I could also replicate the previous logic by making it's own functions add and isPositive. Would you recommend doing it that way instead of with the added dependancies due to performance?

**Comment by josdejong** [comment]
This looks very neat indeed! It makes a lot of sense to "just" use the standard functions `add` and `isPositive`. I like the simplicity of your solution a lot 😎 

Yeah my only concern was a bit of performance optimization, but I think this is neglectable (and if really an issue, we can always optimize later). 

Ok shall I merge your PR now?

**Comment by dvd101x** [comment]
Thanks! Yes please

**Comment by josdejong** [comment]
The refactor has been published now in `v11.9.0`

**Pull request merged**
