### PR TITLE
Make dim optional for std and var

### PR DESCRIPTION
**Pull request by NattapongSiri**
Per comment in https://github.com/josdejong/mathjs/issues/2429#issuecomment-1060957073
This pull request should fix this

### CODE REVIEW

**Review by NattapongSiri — COMMENTED** [review]
The reason that I change one of overload signature that accept normalization without dim from optional to required is because if user choose to omit both dim and norm then the signature will be matched with the most comprehensive overload which would show the JSDoc for all arguments.

**Comment by gwhitney** [comment]
I just wanted to add that now that we have some testing of the typescript typings (by running types/index.ts), please add to this PR code in types/index.ts that checks the typings of std and variance (i.e that will only compile or run properly if the type declarations are correct). Thanks!

**Comment by NattapongSiri** [comment]
I'm done with .ts test case

**Comment by NattapongSiri** [comment]
It seem to me that the signature version of `math.variance([1, 2, 3], "biased")` throw an error with message `Error: Cannot convert "biased" to a number`.

I'm not sure how to fix this.

**Comment by NattapongSiri** [comment]
My attempt to fix test case. I thought it just test the type definition so I don't care if the function can be actually executed.
It turn out that this is not the case. It actually trying to calculate variance/std on number then it thought that the second argument is variadic parameter.

For example: `math.chain([1, 2, 3]).std("biased").std("unbiased")` will cause such error. 
The error message is misleading thought but I guess that can't be help when the actual execution is done from JS side.

**Comment by gwhitney** [comment]
There is still an inconsistency between the types for the "direct" math.std and math.variance and the "chain" .std and .variance. Specifically, the following works in plain JavaScript:

`math.chain(2).std(3,3,4)`

and it produces exactly the same results as `math.std(2,3,3,4)` because that's just the way that "chains" work.
However, although the latter works fine in TypeScript, the former currently fails to type with an `Expected 0-2 arguments, but got 3.` error.

Now because this would be an odd use of a chain (although entirely legitimate by current rules), I am not sure exactly the best resolution and perhaps @josdejong should weigh in. Some possibilities are:
1) Add the signatures in `types/index.d.ts` that will make this odd sort of chain that works in JavaScript type correctly in TypeScript, basically a `std(...values: number[]): MathJsChain` (and one for variance, and also corresponding tests). Not sure whether or not that will improve the error messages you mention, which I agree can be confusing.
2) Conclude that the fact that you can in effect split a 'rest' parameter between the initial `chain()` call and the subsequent command in the chain is just an undesirable side effect of how chains work in JavaScript and so we don't actually want to allow it in TypeScript. In that case, possibly this PR could be tweaked to improve the error messages that come up in TypeScript in various cases of trying to do this questionable thing, or maybe that's not necessary. If this tweaking is desired, then it would be ideal for `test:types` to verify that the desired errors are generated, but that would definitely involve re-engineering the test to have additional source files since right now definitely `types/index.ts` can't have any compilation errors, only runtime.
3) Decide that the current "splitting rest parameters" behavior is sufficiently weird that not only do we not want to allow it in TypeScript, but we'd prefer to actually prevent it altogether,  and so the chain facility on the JavaScript side should be amended so that `math.chain(2).std(3,3,4)` won't actually be interpreted as `math.std(2,3,3,4)` (but will issue some easily understood error).

Any thoughts on which alternative is best or on whether there are other options are welcome.

**Comment by josdejong** [comment]
Thanks @NattapongSiri for this PR, appreciated 👍 

To me, splitting rest parameters in a chained call, like `math.chain(2).std(3,3,4)`, is something we should not want/do in practice. So I would say let's just make sure it's not supported in the TypeScript definitions: that is option (3) of the ideas of @gwhitney. Does that make sense @NattapongSiri, @gwhitney ?

**Comment by gwhitney** [comment]
OK, so to be clear, option (3) was the one in which I proposed we completely disable `math.chain(2).std(3,3,4)` from meaning `math.std(2,3,3,4)` even just in pure-JavaScript use of mathjs. Is that the preferred direction to go here? That's a much more extensive change than just what's in this PR (which affects TypeScript only), and it's a breaking change to mathjs. So in this case perhaps we'd want to (a) accept/merge this PR, since it would then be compatible with the planned behavior for javascript mathjs, (b) file a separate issue that such "split rests" should not be allowed by chain, and (c) work up a PR that resolves the new issue in time for v11? If so I am happy to work or collaborate on some/all of (a),(b),(c) but just wanted to make sure everyone is on the same page before I embarked.

**Comment by josdejong** [comment]
hm, yeah, to be consistent we should not allow that in plain JavaScript either, but that would be serious work 🤔

Here is my reasoning:

1. Splitting rest parameters like in `math.chain(2).std(3,3,4)` is not something you need in practice, so it is OK with me to drop support for it
2. It also doesn't do harm if it _does_ work
3. We do want the TypeScript definitions to be consistent with the actual plain JavaScript behavior
4. So let's choose what is the least amount of work

Glen's option (3) that I mentioned before (https://github.com/josdejong/mathjs/pull/2474#issuecomment-1068176869) requires changing both JS behavior and TS definitions, so this is much work. So if "just" changing the TypeScript definitions to be aligned with the actual JS behavior is little work, I think that is the better option after all (Glen's option (1)).

**Comment by gwhitney** [comment]
Well, just to quantify things, here's the path I see for implementing the JavaScript side of "option (3)":

A) In typed-function, expose a function `typed.isTypedFunction(x)` (well, or use the one already in `import.js` but really it ought to come from typed-function and import should be changed to use that).

B) In typed-function, expose a function `typed.resolve(fn: typedFunction, argList: Array.<any>)` that returns the object with the specific signature and implementation function that the call `fn(argList[0], argList[1], ...)` would reach. [Note that neither A or B is a breaking change to typed-function, so that's convenient.]

C) In `chainify` in `Chain.js`, if there are any arguments in the latest call, rather than just applying fn to the args, instead call the "resolve" function from part (B). If it returns a signature that consists entirely of a single rest parameter, issue an error message that a rest parameter may not be split across a chain() constructor and a subsequent call; otherwise, apply the returned implementation function to the  assembled argument list.

That's all. So that doesn't really seem like _al_l that much work to me -- happy to do it if you like. So please just let us know. If you want to do "option (1)" then @NattapongSiri  would need to add another overload to the chain version of each of std() and variance().

I do totally respect the principle of keeping JavaScript and TypeScript in sync, i.e. discarding "option (2)". I just threw that out as a logical possibility.

**Comment by NattapongSiri** [comment]
It's ok whichever choice you made. To me, change to typescript only need few keystroke.
So my opinion is that I can make a change to accept a use case like `Math.chain(1).std(2, 3, 4)` but I feel like this should be discouraged to use.
It make code hard to read and also lead to a weird error message like what I found.

I also think that it'd have different `MathJsChain` return for value of type `number`, `MathArray`, and `Matrix`.
This way, it can be easily distinguish which step cause an error along the chain. 
There are many way to achieve this. For example, common base class of chain then specialized class for any concrete type. Another example, using type composition.  But this probably need to have a long discussion which probably out-of-scope for this PR.

**Comment by josdejong** [comment]
Thanks. Given your responses:

> So my opinion is that I can make a change to accept a use case like `Math.chain(1).std(2, 3, 4)` but I feel like this should be discouraged to use.
> It make code hard to read and also lead to a weird error message like what I found.

and

> That's all. So that doesn't really seem like _al_l that much work to me

I think you are right, this isn't a usage pattern that we would like to support. Let's then go for disabling splitting of rest parameters in both TypeScript definitions and JavaScript.

Let's address this in two separate PR's:

1. TypeScript definitions: @NattapongSiri is your PR on par or are there still changes needed to match the desired behavior?
2. We will have to implement some code to restrict this behavior in chained calls, along the lines of the proposal of @gwhitney . I have opened a separate issue to address that: #2485

**Comment by NattapongSiri** [comment]
I think there's no need for me to modify anything more as it's already did just that.

**Comment by gwhitney** [comment]
I agree with NattapongSiri, this PR is fine as it stands in light of #2485. So I will update it in preparation for one of us merging it, and make work on #2485 my top priority so it can be slated for v11.

**Comment by josdejong** [comment]
Published in `v10.4.1`

**Pull request merged**
