### PR TITLE
Added BigNumber functionality for atan2, with tests.

### PR DESCRIPTION
**Pull request by BigFav**

### CODE REVIEW

**Comment by BigFav** [comment]
So weird, I didn't touch anything that involved the error. Also weird, when I run the test on the folder or the whole suite, it fails, but if I just run the file it passes. Any possible explanations?

**Comment by josdejong** [comment]
That's odd. `cot.test.js` fails on line 61 when running node v0.10.36. Apparently there is a round-off error, which I can understand, but I don't get why it doesn't fail consistently. The test on node v0.11 does fail for a different reason, which is odd too.

**Comment by BigFav** [comment]
Like this [list of successful builds](https://github.com/josdejong/mathjs/compare/master%40%7B1day%7D...master) just makes me more confused; it said it was working that whole time. I will play with the stuff tomorrow.

**Comment by BigFav** [comment]
It's a namespace error, which makes sense...I just have to find it lo.

**Comment by josdejong** [comment]
Seen from the tests you succeeded in finding the error, so I can merge your PR?

**Comment by josdejong** [comment]
I've checked it out, everything looks fine. Thanks Favian!

**Pull request merged**
