### PR TITLE
BigNumber Constants

### PR DESCRIPTION
**Pull request by BigFav**
While testing `sin` I realized how slow `bigPi` is. I was wondering what your thoughts are on this? We can have a precomputed string for some large amount of digits (I think Wolfram maxes out at 3902 digits), in order to make more common cases efficient while not loosing the ability to theoretically compute it for arbitrary precision (if #261 gets resolved). This change alone improved `sin`'s performance in my test cases by ~40%.

If you like this idea, which constants should this be done for, and how many digits? (right now we are limited to 1015 due to the issue I previously referenced)

### CODE REVIEW

**Comment by josdejong** [comment]
Good point. Calculating `pi` is indeed very slow, takes seconds for calculating with 1000 digits. 

We should separate the concerns of calculating `pi` from that of calculating for example `sin`. Right now with every call of `sin`, `pi` is calculated again, which we can easily improve.

I think there are two options: 
- Replace the calculation of `pi` with a pre-calculated one with say 1015 digits (your current PR). This is a very simple, pragmatic approach.
  - Pro: *very* fast load time
  - Con: a little bit larger library (in kB's)
  - Con: configurable precision is limited to about 1015 digits 
- Dynamically calculate `pi` as it is right now, but put a little `memoize` function around the `.pi(precision)` function. This way, only the first request for `pi` will be slow, consecutive requests are instant.
  - Pro: no limitations to the precision  (except requiring too much CPU to be practical ;) ), provided that decimal.js also doesn't impose limitations
  - Con: first request for `pi` is slow.

**Comment by josdejong** [comment]
I've added a simple `memoize` function and use this with all BigNumber constants. That should at least improve the speed of `sin`.

**Comment by BigFav** [comment]
I don't think your 1st option represents the code I've posted. My code does not have the second con you listed, because if the precision requested was greater than or equal to 1015 (and there were no limits in decimal.js), it would simply use the formula to calculate `pi`. Also, do you mean the file will be larger, thus the library will be larger?

**Comment by josdejong** [comment]
Yes sorry, you are right: your solution is a hybrid of the two I mentioned: use the pre-calculated `pi` in case of less than 1015 digits, and calculate pi otherwise. 

There is one other easy improvement: lazy evaluate pi (using ES6 properties). Right now, pi is calculated when math.js is loaded or reconfigured. But you may not need pi at all, when for example just doing basic arithmetics with bignumbers. Would be nice if pi is calculated only as soon as you need it.

I'm not sure if it will really help a lot to pre-calculate pi for "small" precision (like the default 64 digits), as for "small" precision the calculation is relatively fast be anyway. It would help in this mid-range of say 800-1000 digits. But still, when doing calculations at that precision you probably experience slowness anyway, so removing this initial extra slowness of calculating `pi` once may not help that much. The speed of calculating `pi` is in the same order of magnitude as calculating `sin` I suppose, as they both use a Taylor expansion.

Yes I mean that the size of the library grows a little, so the question is whether this pre-calculation really improves the experience. What do you think?

**Comment by BigFav** [comment]
I had not thought about it this deeply, as I did not even realize that file size was an issue. Based on the properties menu on my Ubuntu machine, `piStr` is ~1.1 kB or 1,127 B (correct this if this is wrong). I honestly have no idea as to what consequences can come from this extra amount in file size.

As for performance, the only issue I can think of is if people are actively adjusting their precision in order to minimize slowness. If they are adjusting between very high precisions, and make calls to `sin` or another function which uses `pi`, it may cost them a noticeable amount of seconds (or do you only keep the highest precision, and then round that on lower precision calls?).

My ignorance of the importance of file size would make me favor the hybrid method; I state my ignorance up front. I'm usually pro speed lol.

**Comment by josdejong** [comment]
In the end this `piStr` will add about `1%` to the total size of the library when minified and zipped.

You typically trade both size and simplicity of code for better performance. I always try to check whether this is worth it, or whether this is a "micro optimization" which only helps in a few special cases or improves performance only little. 
Something like speeding up *all* calculations of `sin` with a factor 2 by caching BigNumber `pi` helps a lot. Also, hard-coding the results for factorial 0-21 can improve a lot as it speeds up *every* calculation of factorial in the mostly used range of input values. But making the *one-off* calculation of `pi` fast when having a precision in the range of 800-1000 is quite specific. If you execute `sin` only ten times afterwards, this initial calculation of pi is already neglectable. Also when you switch to an other precision very regularly, I think the number of different precisions being used will remain limited, so the memoize cache will probably do it's job nicely.

The hybrid solution is a smart, optimal, and performing one, but it still feels a bit overkill to me ([KISS principle](http://www.wikiwand.com/nl/KISS-principe)?).

**Comment by BigFav** [comment]
When I minify and zip, I don't get `1%`. The highest I get is `~0.34%` I cleaned up the file a bit and was too lazy too add the memoize to the piStr implementation, so it may be off by a few bytes, but this is what I got:
```
memoized, no piStr

math.min.js  - 251.4 kB (251,428 bytes)
math.map     - 320.8 kB (320,831 bytes)
math.js      - 838.7 kB (838,681 bytes)
sum          - ~1.4 MB (1,410,940 bytes)

math.tar     - 1.4 MB (1,423,360 bytes)
math.tar.gz  - 297.0 kB (297,035 bytes)
math.tar.bz2 - 250.8 kB (250,802 bytes)

-----------------------------------------------------------------
no memoize, piStr

math.min.js  - 252.4 kB (252,361 bytes)
math.map     - 320.7 kB (320,724 bytes)
math.js      - 839.1 kB (839,081 bytes)
sum          - ~1.4 MB (1,412,166 bytes)

math.tar     - 1.4 MB (1,423,360 bytes)
math.tar.gz  - 298.2 kB (298,186 bytes)
math.tar.bz2 - 251.7 kB (251,665 bytes)
```
Regardless of the percentage, I don't think I will be able to be truly convinced that `~1.2 kB` is back-breaking (maybe my age?), but I can simply accept that it is.

I find the usage of KISS to be highly suspect in this situation. If an if statement with a string slice is complicated, then PhDs are required for memoization lol.

I'm going to close this, as this doesn't really warrant further discussion (it's not that important at all lol).

**Comment by josdejong** [comment]
you are right this isn't that important, I don't have a very strong preference for any of the options. If there are good reasons to change this decision in the future it's fine with me to reconsider. 

And yes, I've studied for years on this `memoize` function ;).

**Pull request closed without merging**
