### PR TITLE
Boolean logic

### PR DESCRIPTION
**Pull request by BigFav**
Created the boolean files for `&&`, `||`, and `!`. I did not do XOR because it is the logical equivalent of `!=`. I was going to add `!` to the parser, but I'm waiting for my other request (the BigNumber bitwise) to get pulled.
#86

### CODE REVIEW

**Comment by BigFav** [comment]
It's probably better that they convert their strings to numbers, as they can probably make assumptions that we can't about their numbers, and thus can choose [what is best for them](http://jsperf.com/simple-string-to-number/2).

**Comment by josdejong** [comment]
What sort of assumptions do you mean? If someone does say `"2" * "3"` I can think of only one intention: multiplying these strings as numbers.

**Comment by BigFav** [comment]
I meant assumptions on the particular number, not the implied operation. In the link it shows that using bitwise ops to convert from string to number is by far the fastest, however it only works if the number is 32-bits large (which we shouldn't assume if we were to implement this).

**Comment by josdejong** [comment]
These type of micro-optimizations are tricky: they can be very different per browser and can completely change in the next version of a browser due to some improvements.

I think if someone needs to squeeze every bit of performance out of some algorithm, he will have to write it all by hand anyway. But offering convenient standard behavior for the average user won't hurt I think.

**Comment by BigFav** [comment]
Wow, I'm such a JS noob lol. I did some more browsers, and the [results were pretty funny](http://jsperf.com/simple-string-to-number/3).

**Comment by josdejong** [comment]
:D 

http://www.smashingmagazine.com/2012/11/05/writing-fast-memory-efficient-javascript/

> Remember to care about optimization, but stop short of opting for micro-optimization at the cost of convenience.

**Comment by BigFav** [comment]
I think I was being too "glass is half full" because this is just inconvenient and wierd lol. The one thing I would worry about is confusion of `'2' * 5` could equal `'22222` a la Python.

**Comment by josdejong** [comment]
> '2' * 5 could equal '22222' a la Python

ah, that's actually an interesting idea! We could do that...

**Pull request merged**
