### PR TITLE
Simplify nested exponentiations

### PR DESCRIPTION
**Pull request by IvanVergiliev**
I randomly stumbled upon this by noticing that the last expression I've added in the unit test (`8 * x ^ 9 + 2 * (x ^ 3) ^ 3`) doesn't simplify to `10 * x ^ 9` as expected.

### CODE REVIEW

**Comment by firepick1** [comment]
Thanks, Ivan. I will look into this.

**Comment by firepick1** [comment]
@IvanVergiliev this might not be a bug.  I wrote an exponentiation test that shows that mathjs does indeed simplify exponentation, and "x^2^3" simplifies to "x^8" as expected.  Exponentiation is right associative and this is actually critical. In the example you provided, the parentheses override the implicit order of operations and are therefore mandatory and cannot be simplified. I would recommend closing this issue. What do you think?

**Comment by ericman314** [comment]
The new rule applies specifically to the form with parentheses: `(x^y)^z = x^(y*z)` and is indeed correct. @IvanVergiliev, thanks for including tests!

I think that for `simplify` the order of the rules matters, but who's to say what the right order is? Adding new rules always has the potential to cause infinite loops or other unexpected side effects, but as all the tests are passing I think we're okay for now. @firepick1 , what do you think?

**Comment by firepick1** [comment]
Eric/Ivan, I've made a targeted fix specifically for the power rule with the parentheses. All tests pass, including the following tests:
x^2^3 is x^8
(x^2)^3 is x^6 by the power rule
Is this as expected?  (it matches Wolfram Alpha)

**Comment by josdejong** [comment]
:+1:

**Pull request merged**
