### PR TITLE
Extend std var for variable dimensions request 999

### PR DESCRIPTION
**Pull request by bnlcas**
Changed 'var.js' to accept a dimension argument so that var and std can be applied along the rows/columns of a matrix using apply.js

### CODE REVIEW

**Comment by bnlcas** [comment]
This pull request satisfies the requirements of [Issue 999](https://github.com/josdejong/mathjs/issues/999). All changes and additions have test coverage, however the automated coverage tests are detecting a reduction in coverage. This seems like an artifact of how the coverage is calculated. @josdejong what would you recommend for this?

**Comment by josdejong** [comment]
Thanks @bnlcas, looks very good and well tested. It's nice to see how little work the actual functionality is now you can use `apply`: it's just a few lines of code now :sunglasses: . 

@harrysarson can you figure out if we can set the (now failing) codecov check less strict? If not possible it's maybe best to turn the webhook off for now, at least for PR's.

**Comment by harrysarson** [comment]
Yeah, turn off the webhook I think :+1:

**Comment by josdejong** [comment]
@harrysarson ok I've made the webhook inactive for now, let's see

**Comment by josdejong** [comment]
@bnlcas the extended `var` and `std` are now available in `v5.8.0`

**Comment by bnlcas** [comment]
Awesome! Thanks guys.

**Pull request merged**
