### PR TITLE
Providing overridable Unit.isValidAlpha

### PR DESCRIPTION
**Pull request by rnd-debug**

### CODE REVIEW

**Comment by josdejong** [comment]
Looks good @rnd-debug , thanks!

Can you please write a unit test to test the new functionality?

**Comment by josdejong** [comment]
O, and I think we should document this else nobody knows that this is possible

**Comment by rnd-debug** [comment]
Ok, pushed some tests and an addition to _docs/datatypes/units.md_, assuming that this file is used to generate [https://mathjs.org/docs/datatypes/units.html](https://mathjs.org/docs/datatypes/units.html)

**Comment by josdejong** [comment]
Thanks @rnd-debug, looks good !

**Comment by josdejong** [comment]
The new function `Unit.isValidAlpha` is now available in `v7.6.0`.

**Pull request merged**
