### PR TITLE
Drop node 6

### PR DESCRIPTION
**Pull request by harrysarson**
node 6 is no longer support by node. Also add node 12 to CI.

Same as #1493 but this is a major change as we also drop node 6.

---

*Note*: target branch is modular_architecture!

### CODE REVIEW

**Comment by harrysarson** [comment]
CI will probably fail for same reason as #1493 :(

**Comment by harrysarson** [comment]
@josdejong I think it is an error with the `sin` function. Have added a new test that should fail on node 12 only.

**Comment by josdejong** [comment]
I've just merged `modular_architecture` into `develop` and switched this PR to `develop` accordingly

**Comment by harrysarson** [comment]
Merging is blocked on https://github.com/MikeMcl/decimal.js/issues/128

**Comment by harrysarson** [comment]
Can we close?

**Comment by josdejong** [comment]
I've published v5.10.0 containing the latest version of decimal.js. Also dropped node 6 from travis testing there already, though I forgot to mention it in the changelog.

I will merge this PR because of the added unit test and update in package.json

**Comment by harrysarson** [comment]
> Also dropped node 6 from travis testing there already, though I forgot to mention it in the changelog.

v5.10.0 will still support node 6 as all the changes we landed there have been tested on it. We probably should not be (officially) dropping support for a node version in a minor release.

**Comment by josdejong** [comment]
Hm yeah good point. I will add node 6 again to the travis config in the `v5` branch (nothing actually broke though)

**Comment by harrysarson** [comment]
We are unlikely to do too many more v5 releases so we could probably get without testing node 6.

**Comment by harrysarson** [comment]
But is good to make sure 😄

**Comment by josdejong** [comment]
yeah. well, it's a small change any way, already pushed to `v5` branch.

**Pull request merged**
