### PR TITLE
Delete es5-shim

### PR DESCRIPTION
**Pull request by rivercory**
https://github.com/josdejong/mathjs/pull/3275

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks! 

Can you also remove the following lines from `./_layouts/default.html`?

```js
<script src="/js/lib/es5-shim.min.js" type="text/javascript"></script>
<script src="/js/lib/es5-sham.min.js" type="text/javascript"></script>
```

**Comment by rivercory** [comment]
@josdejong Done.

**Comment by josdejong** [comment]
Thanks @rivercory ! Merging your PR now.

**Comment by josdejong** [comment]
Yes, the website could use some updates (like improving search and a more fresh, modern look). Do you have specific ideas?

**Comment by dvd101x** [comment]
Here are some discussions that might help.

https://github.com/josdejong/mathjs/discussions/2756#discussioncomment-6800530
https://github.com/josdejong/mathjs/discussions/3274#discussioncomment-10888540

**Pull request merged**
