### PR TITLE
Feat/rotate matrix

### PR DESCRIPTION
**Pull request by rnd-debug**
Related to #1160 
- [x] Implement rotationMatrix(theta, v, format)
- [x] Unit tests
- [x] Header in the code
- [x] Embedded docs
- [x] Latex support (not sure)

Questions:
- should I provide a "complete Latex support"? For the moment, `toTex` will convert to `mathrm`.

Will provide `rotate(w, theta)` as alias for `multiply(rotationMatrix(theta), w)` in another MR if this one is accepted.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @rnd-debug , this PR looks good and ready to merge 👍 . Great that you've added support for units. A function `rotate(w, theta)` on top of this will make this really interesting!

>     * should I provide a "complete Latex support"? For the moment, `toTex` will convert to `mathrm`.

I'm not sure what you mean with "complete" Latex support. Isn't `rotationMatrix` just a regular function like say `sin`? In that case we could render it just like other functions as `\rotationMatrix\left(...\right)`. Or is there a special Latex notation for rotation matrices?

**Comment by rnd-debug** [comment]
`sin` is one of the few "standard" functions, so it is recognized when we write `\sin` and will produce a nice roman font when inside an equation block.
If we try to do the same (`\rotationMatrix`) with non-standard functions, it will fail to output: we have to call `mathrm` explicitely. I don't think that there is a particular Latex syntax for rotations, so I assume we can live with the current version of `math.parse('rotationMatrix(1)').toTex()`, that produces a `\mathrm`.

A small example below:
```tex
\begin{equation}
  \begin{align*}
    \cos(\theta) \\
    cos(\theta) \\
    \rotationMatrix(\theta) \\
    rotationMatrix(\theta) \\
    \mathrm{rotationMatrix(\theta)}
  \end{align*}
\end{equation}
```
image

**Comment by josdejong** [comment]
> I don't think that there is a particular Latex syntax for rotations, so I assume we can live with the current version of

Thanks for the explanation, I agree, looks good like this 👍 . Thanks again, will merge your PR now.

**Comment by josdejong** [comment]
Available now in `v7.4.0`, thanks again.

**Pull request merged**
