### PR TITLE
chore: clone last 5 commits

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, I hope this improvement will also improve the performance. Do you have any experience in how much effect this typically has on performance?

**Comment by DanielRuf** [comment]
> Thanks, I hope this improvement will also improve the performance. Do you have any experience in how much effect this typically has on performance?

It depends on the actual diff sizes of the last 5 commits (less to calculate than in 50 commits).

**Comment by josdejong** [comment]
ok, we'll see then :)

**Comment by harrysarson** [comment]
Why would you not just clone the latest commit in rather than 5?

**Comment by DanielRuf** [comment]
> Why would you not just clone the latest commit in rather than 5?

https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth

> Please note that if you use a depth of 1 and have a queue of jobs, Travis CI won’t build commits that are in the queue when you push a new commit.

**Comment by harrysarson** [comment]
sounds good to me :smile:

**Pull request merged**
