### PR TITLE
Fix syntax error on example.

### PR DESCRIPTION
**Pull request by abranhe**
Found this syntax error on the docs, I am here just to fix it.

https://mathjs.org/docs/reference/functions/format.html

### CODE REVIEW

**Comment by gwhitney** [comment]
@abranhe I'd like to rebase this branch on the current develop so that it could be merged, but the github option to do that is not available. Did you enable "allow edits by maintainers"? If not, please could you? If that is enabled, does anyone know another reason why the "Update branch" button would not be available? Thanks.

**Comment by gwhitney** [comment]
OK, this is cleared for merging but the last step is I need to make the following addition to HISTORY.md:
```
diff --git a/HISTORY.md b/HISTORY.md
index 3ce79b89a..cb57cd546 100644
--- a/HISTORY.md
+++ b/HISTORY.md
@@ -8,6 +8,7 @@
   (#2455). Thanks @NattapongSiri.
 - Fix #1633: implement a `cumsum` function generating cumulative sums of a list
   of values or a matrix. (#1870). Thanks @hjonasson.
+- Fix typo in documentation example for `format`. (#2468) Thanks @abranhe.
 
 # 2021-03-02, version 10.3.0
 
```
I made this commit locally but I still am unable to push to your branch. Please either enable edits by maintainers or push this change to your branch. Then it can be merged. Thanks very much.

**Comment by abranhe** [comment]
@gwhitney I've updated the PR!

**Comment by josdejong** [comment]
This fix is published now in `v10.4.0`, thanks again 😄

**Pull request merged**
