### PR TITLE
Electrical units

### PR DESCRIPTION
**Pull request by ericman314**
Added electricity and magnetism units.
Added unit tests.
Updated docs.
Fixed tabs.

The latest addition to the examples shows how units are formatted in arrays: `[0 m / s, 1 m / s, 0 m / s]`. Is there any desire to factor the unit out of the array so it is output as: `[0, 1, 0] m / s`?

### CODE REVIEW

**Comment by josdejong** [comment]
Nice Job, thanks a lot Eric. How about releasing v2.1 coming weekend with your support for derived units? 

I would say the unit should *not* be factored out from the output. That would basically mean that we would have to add support for units holding matrices instead of a single value. It could be something though that an output-formatter could do to show the results in a compact, human-readable way.

**Comment by ericman314** [comment]
I was thinking the same thing using the output formatter. I'll see if I can figure that out.

**Comment by josdejong** [comment]
I don't know what a good place for this would be, *if* we want to do something about it. I'm not sure if it's that important. Typically, for web based applications, people may want to implement their own matrix viewer anyway, displaying the contents as a table. What do you think?

**Comment by ericman314** [comment]
Perhaps it's best to leave it exactly as it is represented internally so
there's no confusion.

**Comment by josdejong** [comment]
Yes I think so. If it turns out to be a much desired feature we can always decide to implement something for this anyway.

**Comment by josdejong** [comment]
@ericman314 I'm working on releasing v2.1.0 but found one of the units examples to fail:

compute molar volume of ideal gas
https://github.com/josdejong/mathjs/blob/develop/examples/units.js#L61-L74

I'm looking into it but didn't yet see the cause. Any idea?

**Comment by josdejong** [comment]
never mind I found it, it was caused by the change of precedence of implicit multiplication

**Comment by josdejong** [comment]
You've put some nice, illustrative examples together for the units btw :)

**Comment by ericman314** [comment]
Thanks and good catch! Looking forward to the release.

**Comment by josdejong** [comment]
v2.1.0 is on npm now, congrats! 

I will update the website as soon as v2.1.0 is available on cdnjs.com.

**Pull request merged**
