### PR TITLE
ES6+ setup (WIP)

### PR DESCRIPTION
**Pull request by josdejong**
See #914 

Done:

- `lib` has been renamed to `src`
- `npm run build` (creates `dist` and `lib`)
- `npm test`
- `npm run coverage`

To do:

- `npm run test:browserstack`
- `npm run test:browser`

### CODE REVIEW

**Comment by josdejong** [comment]
Now both `npm run test:browserstack` and `npm run test:browser` are not working, that may give a clue. Still have to compare with a few commits back when one of the two was working, but it's bed time now.

```
ReferenceError: exports is not defined at browser-test-config/browser-tests.test.js line 6467
```

**Comment by josdejong** [comment]
Karma is working fine now, in the karma config I had to configure webpack to use babel-loader. Will merge this PR now in develop.

@harrysarson once you have some time again it would be great if you could go through the current setup with build- and test scripts to see whether it is set up properly. I've split the unit tests now in three sections: `test`, `test-node`, and `test-dist`. Here, `test-dist` contains some tests to see whether the bundled files actually work. Right now I only execute these tests before publish since it requires bundling before you can run the tests which is relatively slow.

**Comment by harrysarson** [comment]
@josdejong cool I will take a look :)

How slow is "relatively slow"?

**Comment by josdejong** [comment]
> How slow is "relatively slow"?

Just run `npm run build` to try it out, something in the order of 15-20 seconds.

**Comment by harrysarson** [comment]
So I think it is worth running `npm build-and-test` probably only on the LTS version of node.

Although, currently `build-and-test` includes running `test:src` and `lint` which we ideally don't want to have to do twice, especially as this will be the slowest build.

**Comment by josdejong** [comment]
> So I think it is worth running npm build-and-test probably only on the LTS version of node.

Yes that will be most efficient. We should not end up with a too complicated travis setup though.

At this moment we will gain most by running all tests in parallel instead of in series (different stages). We can flatten everything and only run `npm build-and-test` for node 10.

**Comment by harrysarson** [comment]
How does #1195 look?

**Pull request merged**
