### PR TITLE
Remove Duplication

### PR DESCRIPTION
**Pull request by Josef37**
See https://github.com/josdejong/mathjs/pull/2073#issuecomment-761541198

I've opted out of changing the third case, since it was mainly initialization and - like you said - would have made it harder to understand.

### CODE REVIEW

**Comment by josdejong** [comment]
This is a very nice improvement 😎 , thanks!

What do you think should we add a unit test for the new util function `lastDimToZeroBase` which is now standalone?

**Comment by Josef37** [comment]
Tests are there now. Was faster to write them, than to discuss :smile:

**Comment by josdejong** [comment]
Looks good 😄 , thanks for adding the tests!

**Comment by josdejong** [comment]
Improvements now published in `v9.2.0`

**Pull request merged**
