### PR TITLE
fix #2603: added type definition for onUndefinedSymbol & onUndefinedFunction

### LINKED ISSUE #2603: onUndefinedSymbol  missing in TypeScript definitions
Hello, I'm trying to evaluate an expression whose scope might not contain all the necessary variables. I'd like to set null as the default value for such symbols or create a custom function that returns false if symbol does not exist.

`  console.log(math.evaluate("not c", { a: 5, b: 8 }));
`

Should return true (if possible)
I was digging up similar issues and made note of `onUndefinedFunction` and `onUndefinedSymbol` but couldn't find examples on how I can set this up once at the global level and not per node? Can someone please direct me to an example?

### PR DESCRIPTION
**Pull request by egziko**
This resolves issue #2603

Added type definition for `SymbolNode.onUndefinedSymbol` and `FuctionNode.onUndefinedFunction`

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks 👍 

Two small remarks:

1. Can you add a usage example to [types/index.ts](https://github.com/josdejong/mathjs/blob/develop/types/index.ts) to make sure the methods are usable in TypeScript now?
2. Instead of returning `any` and having to ignore linting, would it be possible to define the methods with a generic <T> and have  them return `T` instead of `any`?

**Comment by egziko** [comment]
> 1. Can you add a usage example to [types/index.ts](https://github.com/josdejong/mathjs/blob/develop/types/index.ts) to make sure the methods are usable in TypeScript now?

I've added the example
We can add an example for `onUndefinedFunction` using a fallback function, what do you think?
```
math.FunctionNode.onUndefinedFunction = (name: string) => {
  console.warn(`Function ${name} was not found, using sum instead.`)
  return (...args: any[]) => {
    return (new math.FunctionNode('sum', args.map(n => new math.ConstantNode(n)))).evaluate();
  }
}
```

> 2. Instead of returning `any` and having to ignore linting, would it be possible to define the methods with a generic  and have  them return `T` instead of `any`?

I'm not sure how can this be achieved

**Comment by josdejong** [comment]
1.  Thanks for adding the example. For an `onUndefinedFunction` example we could do something simple like: `math.FunctionNode.onUndefinedFunction = (name) => () => 42` or so it returns a function instead of throwing an exception, and then verify that the outcome is 42 (or null like the symbols example). Most important is verifying that the custom callback is invoked.


2.  > I'm not sure how can this be achieved

    I was thinking about something like `onUndefinedSymbol: <T> (name: string) => T` but I can't get that to work, so let's just return `any` then, I think it will not be a problem in practice.

**Comment by egziko** [comment]
@josdejong 
Added the requested changes

**Comment by josdejong** [comment]
Thanks @egziko for getting back to this! Looks good.

**Pull request merged**
