### PR TITLE
Added trace matrix operation

### PR DESCRIPTION
**Pull request by pcorey**
Added the trace matrix operation, abbreviated "tr". See tests for usage.

http://en.wikipedia.org/wiki/Trace_(linear_algebra)

### CODE REVIEW

**Comment by josdejong** [comment]
Nice, thanks Pete! Looks good.

How about just naming this function `trace` instead of `tr`? That's more explanatory, and if you want to use the shorter `tr` you can easily create this shortcut.

**Comment by pcorey** [comment]
Sure thing! I'll make that change in a bit.

**Comment by josdejong** [comment]
awesome!

**Comment by josdejong** [comment]
Thanks again.

**Comment by pcorey** [comment]
Thank you!

**Pull request merged**
