### PR TITLE
Big Number Format Fixes

### PR DESCRIPTION
**Pull request by mgreminger**
For some engineering notation cases, `math.format` outputs full precision for `bignumber` input when the input has 3 or more significant figures, the desired output has a precision of 1 or 2, and the coefficient of the engineering notation result has 2 or 3 digits. See the previous output below:

```
> format(bignumber(777777.77), { notation: 'engineering', precision: 1 })
'777.77777e+3'
> format(bignumber(777777.77), { notation: 'engineering', precision: 2 })
'777.77777e+3'
> format(bignumber(-.000000000777777), { notation: 'engineering', precision: 2 })
'-777.777e-12'
```

After this fix, the output becomes:

```
> format(bignumber(777777.77), { notation: 'engineering', precision: 1 })
'800e+3'
> format(bignumber(777777.77), { notation: 'engineering', precision: 2 })
'780e+3'
> format(bignumber(-.000000000777777), { notation: 'engineering', precision: 2 })
'-780e-12'
```
Tests have been added for the -12, -3, 0, and 3 power cases for both positive and negative input and all of the existing tests pass.

### CODE REVIEW

**Comment by mgreminger** [comment]
Thanks for the feedback. In the branch of code for where I was using `Number` and `toString`, the max number size is 999 (max size of a coefficient in engineering notation) and the max precision is 1 or 2 (the case of 1 or 2 precision is the only time `valueStr` results in a number less than in scientific notation from the `toPrecision` method for numbers less than 999 since insignificant zeros are not output (1e2, for example, instead of 100). However, your suggestion of sticking with BigNumber and using `toFixed` is more consistent with the surrounding code and a better solution since it doesn't rely on the particularities of `toString`.

I've incorporated your proposed changes and it does indeed work with all of the tests and solves the original issue.

After adding the constructor trick you suggested, I did notice that the original JSDoc for the `value` input parameter specified a type union of `BigNumber | string`, however `string` would generate an error in the new code (and also for the previous code since it already accesses the `.e` property and the `.mul` member function). I removed the string type since it would have generated an error in the old code and the new code. It looks like there is already a [type gaurd](https://github.com/josdejong/mathjs/blob/23cf6e8035237747f5d197e659eeeaab3996bd89/src/utils/string.js#L68) to prevent this function from being called with a string input and it looks like the same function [handles strings separately](https://github.com/josdejong/mathjs/blob/23cf6e8035237747f5d197e659eeeaab3996bd89/src/utils/string.js#L88).

**Comment by mgreminger** [comment]
I found an additional issue with format and bignumber. Setting precision to zero for 'fixed' notation results in full precision. The issue was related to treating a precision of 0 as undefined since 0 is falsy. I have added the fix to this pull request since it's related to formatting big numbers and the fix is pretty simple. If you would prefer me to split it out, let me know and I can revert the commit and create a separate pull request. 

#### Details of issue and results of applying the fix:

Old behavior:
```
> format(bignumber(1.333), {notation: 'fixed', precision: 0})
'1.333'
> format(bignumber(1.666), {notation: 'fixed', precision: 0})
'1.666'
```

New behavior:
```
> format(bignumber(1.333), {notation: 'fixed', precision: 0})
'1'
> format(bignumber(1.666), {notation: 'fixed', precision: 0})
'2'
```
With the proposed fix, the behavior of format with bignumber matches the behavior with number.

**Comment by josdejong** [comment]
Sorry for the late reply, and thanks for the updates, and for the additional fixes, nice👌 

This looks like a solid and well tested fix, merging it now.

**Comment by josdejong** [comment]
Published in `v11.8.1` now, thanks again!

**Comment by mgreminger** [comment]
Sounds great, thanks for rolling out a new version, will be incorporating into my project the next time I push out an update (I'm currently running this fix as  a patched version of mathjs). Thanks for this excellent project, much appreciated!

**Pull request merged**
