### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tomekwi**

### CODE REVIEW

**Comment by FSMaxB** [comment]
Thanks.

**Comment by FSMaxB** [comment]
@josdejong: Sorry, I accidentally merged this to master.

**Comment by josdejong** [comment]
@FSMaxB ha ha that regularly happens with me too :). Well a typo can't do harm. I've merged `master` into `develop` so `develop` is now up to date.

**Comment by tomekwi** [comment]
@FSMaxB @josdejong looks like it was my fault – I hadn’t read [this thing](https://github.com/josdejong/mathjs/blob/master/CONTRIBUTING.md) before :pensive: .

**Comment by josdejong** [comment]
you're welcome ;)

**Pull request merged**
