### PR TITLE
Removed maxArgumentCount in favor of applyCallback in `matrix.map`

### PR DESCRIPTION
**Pull request by dvd101x**
This is intended to solve #3241 and is related to #2880.

### CODE REVIEW

**Comment by josdejong** [comment]
That is a nice find and fix 😎, thanks David! All looks good to me.

Maybe neat to also add a unit test to test the `cbrt` when the input is a matrix? (In test `"should invoke a typed function with correct number of arguments (4)"`).

**Comment by dvd101x** [comment]
Thanks!

I will add the tests for dense and sparse matrices and report back.

**Comment by dvd101x** [comment]
Included the `cbrt` tests. It's ready for review.

**Comment by josdejong** [comment]
Thanks for adding the unit tests!

This PR is ready to merge, but for some reason it contains `function _mapMultiple (Arrays, multiCallback)` which should be part of #3228 and not this PR, right? I'm not sure what happened there. If you can easily fix this PR please do so, otherwise it may be easiest to create a new PR replacing this one, or we can simply merge this PR right after merging #3228.

**Comment by dvd101x** [comment]
Thanks for catching this! It was my mistake. I switched development environments to fix a conflict on #3228 and didn't notice I was on this branch.

It wasn't my intention to make any more modifications here before your review.

**Comment by josdejong** [comment]
Ah, yes, this looks better again :). 

Merging now. Really nice to fix `map(matrix)` by getting rid of these two special cases in `DenseMatrix` and `SparseMatrix` 👍

**Comment by josdejong** [comment]
Published now in `v13.1.0`.

**Pull request merged**
