### PR TITLE
[WIP] Run tests on browserstack

### PR DESCRIPTION
**Pull request by harrysarson**
This work is not yet finished but there are some things that I would appreciate feedback on:

- [x] Tests fail on IE 9 because mocha does not support this version. Either we need to also drop support for IE 9 or downgrade mocha to an earlier version. ** dropped support for IE 9 **

- [ ] Which browsers/versions to test. The current browser choices are fairly arbitrary, it would be good to have as wide a selection as possible.

- [x] Directory structure and naming. Currently all the browser (karma) files are in the `browser-tests` directory, this is confusing as `browser-tests` contains no test files (unlike `node-test` which does) maybe something like `browser-test-config` would better but that is a very long name. Feedback appreciated.

- [ ] General code reviews.

- [ ] A few tests are failing on Edge because of Error messages and rounding but these should be simple to fix.

- [x] `Object.assign` needs polyfilling on IE 11 (see #1107)

See https://travis-ci.org/josdejong/mathjs/jobs/378606424#L6340 for the browserstack test run.

### CODE REVIEW

**Comment by josdejong** [comment]
Cool, going to check out your work soon.

I think we should indeed drop support for IE9, and also IE10, since these aren't maintained by MS for a long time already.

**Comment by harrysarson** [comment]
It is worth noting that mathjs **might** work fine in IE 9 as it is mocha that is causing tests to fail, we have no way of testing this though. We should put which browser versions we support into the docs.

**Comment by harrysarson** [comment]
IE 11 does not support `Object.assign` I will open a PR to remove all the `Object.assign`'s from mathjs.

**Comment by josdejong** [comment]
Really cool being able to automatically test on even Android browsers! Thanks for all work you're putting into this Harry!

1. I'm a bit surprised by the way of putting encrypted credentials in the public .travis.yml, but if that's how it works then it's how it works. And ideally I would like to have the credentials of a project not tight to a single person but to a team. I'm not sure how we could change that but I think it's just fine to start with.
2. Can you please use exact version numbers in package.json for karma-browserstack-launcher. You can set this behavior globally for npm using `npm config set save-exact true`.
3. In the end we need explanation in the readme on how the (automated) browser testing works.
4. Which browsers to test: a general rule of thumb can be "support the latest two versions of every browser". Does that make sense? We don't need to be very strict perse, just see what makes sense. And since we're advertising with support for IE9+, well, if the tests work and we can simply keep it working without any effort it doesn't do harm.
5. I agree that renaming `browser-test` to `browser-test-config` is more clear.

**Comment by harrysarson** [comment]
Thanks for the review :)

> 1. I'm a bit surprised by the way of putting encrypted credentials in the public .travis.yml, but if that's how it works then it's how it works. And ideally I would like to have the credentials of a project not tight to a single person but to a team. I'm not sure how we could change that but I think it's just fine to start with.

For reference: https://docs.travis-ci.com/user/environment-variables/. We could also set these sensitive variables directly in the travis repository settings. I don't think we can avoid setting to a single person unless you created a mathjs email adress and account that way.

> 2. Can you please use exact version numbers in package.json for karma-browserstack-launcher. You can set this behavior globally for npm using npm config set save-exact true.

Sorry, my bad.

> 4. Which browsers to test: a general rule of thumb can be "support the latest two versions of every browser". Does that make sense? We don't need to be very strict perse, just see what makes sense. And since we're advertising with support for IE9+, well, if the tests work and we can simply keep it working without any effort it doesn't do harm.

Should we test both versions, or just the oldest one. More versions means longer test run times as browserstack will only let us run so many tests at once.

> 5. I agree that renaming browser-test to browser-test-config is more clear.

Cool, I will change.

**Comment by josdejong** [comment]
1
 > We could also set these sensitive variables directly in the Travis repository settings.

Good idea, I like the idea of using the environment variables that you can set via the Travis UI instead of committing them in the code. I think we indeed simply have to use one of our accounts, there is no such thing as team wide roles/credentials as far as I can see.

5 Yes, testing could take a lot of time for so many browsers. Shall we simply start pragmatic with the latest version of all browsers, and maybe IE9 as an extra? We can always add more.

**Comment by harrysarson** [comment]
> Good idea, I like the idea of using the environment variables that you can set via the Travis UI instead of committing them in the code. I think we indeed simply have to use one of our accounts, there is no such thing as team wide roles/credentials as far as I can see.

I have removed these from `.travis.yml` and (hopefully) set them in the travis repository settings instead.

> maybe IE9 as an extra? We can always add more.

Could we merge this PR without IE 9 and then maybe add in a separate PR?

**Comment by josdejong** [comment]
> Could we merge this PR without IE 9 and then maybe add in a separate PR?

Sure! Let's start simple

**Comment by harrysarson** [comment]
Okay, I think this is now ready. See #1111 for the tidied up version I would like to merge into develop.

**Comment by josdejong** [comment]
👍

**Pull request closed without merging**
