### PR TITLE
Added intersection function

### PR DESCRIPTION
**Pull request by kv-kunalvyas**
Computes:
- Line and line intersection in 2D and 3D
- Line and plane intersection in 3D

Also created folder `geometry` for `intersect.js`

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Kunal! This will be a useful addition

A few remarks:
- can you you please add unit tests for the function?
- can you change the code to 2-space indentation?

**Comment by kv-kunalvyas** [comment]
I am writing the unit tests for the function using other test cases as reference. I wanted to know if there is a way to test the code before I commit. I have tested the sub-functions individually, but I can't figure out a way to test the whole thing to see what it returns. 
I need the outputs to write the cases in the unit test and to be sure of its correctness.

**Comment by FSMaxB** [comment]
You can run the test cases with `npm run test` as described in this projects README. For that to work you need nodejs and need to locally install all of the dependencies by running `npm install` from inside the mathjs directory.

If you want to have an interactive console to test your changes, you can use `bin/repl.js` as described here: https://github.com/josdejong/mathjs/blob/develop/docs/command_line_debugging.md

**Comment by kv-kunalvyas** [comment]
Thanks @FSMaxB, I now better understand how this is working. However, I need help again, getting the following errors when I run `npm run test`:

untitled

It can't find the intersect function. I have written the test file in `~/mathjs/test/function/geometry/intersect.test.js`. The function is present at `~/mathjs/lib/function/geometry/intersect.js`. I created the `geometry` folder in . 
Are there other locations where I need to add something for this to run without the TypeError? If not, what could be wrong here?

**Comment by FSMaxB** [comment]
This means that in your test cases you are calling a function that is not defined. (in line 8, 12 16 and 20 in the file `test/function/geometry/intersect.test.js`.

**Comment by kv-kunalvyas** [comment]
You are right. It got fixed when I included the path for the function in `lib/math.js`. In my latest commit, I have written a few unit tests that assure that the code is working properly.

**Comment by josdejong** [comment]
Thanks for adding unit tests Kunal, looks good. In the future we can expand the unit tests further to test for all sorts of edge cases (like dealing with zero, positive/negative values, etc).

**Pull request merged**
