### PR TITLE
Qr implementation

### PR DESCRIPTION
**Pull request by HarrySarson**
I have what I think to be a working implementation of the QR decomposition which works for real and complex numbers. Addresses #808

### CODE REVIEW

**Comment by HarrySarson** [comment]
Oh dear, the function is not attaching its self to the math object. I think there must be some file that hasn't been committed

**Comment by josdejong** [comment]
Thanks a lot Harry, and sorry for my very late reply. Your PR looks great, neat code, neat tests. 

There is one thing that I saw: the results for both Q and R contain values with opposite signs than when I execute the same QR decomposition with Octave/Matlab and an online tool [like this one](http://comnuan.com/cmnn0100e/). I guess there is some convention in there?

**Comment by HarrySarson** [comment]
I read on Wikipedia that:
> If A is invertible, then the factorization is unique if we require that the diagonal elements of R be positive.

So I went for making the diagonal elements positive (multiplication and division by `conjSgn` in lines 195 and 219 in the code). I could try removing the multiplication/division to see if the values would be the same as matlab.

**Comment by josdejong** [comment]
I've also checked the behavior of wolframalpha, which gives the same result as yours:

http://www.wolframalpha.com/input/?i=QR+decomposition+%7B%7B15,42%7D,%7B20,81%7D%7D

If *all* major math applications would choose a specific convention I would like to follow that, but apparently that's not the case (unless you can find something about it). I have a slight preference for following the behavior of Matlab, but if you think that the current behavior is best it's fine with me. What do you think?

**Comment by HarrySarson** [comment]
Following Matlab would be nice, but I have looked and can't find any description of the convention followed by matlab - I think the matricies are simply left as they are after doing the reflections.

I tried removing the multiplication/division from the `qr` function but it still does not give the same result as matlab (they must use a different algorithm) so I am not sure how we can make the function produce the same results.

**Comment by josdejong** [comment]
Thanks for trying. An option could be to just negate the output but that sounds weird and unfounded. Matlab probably has a different algorithm or something. Ok let's just keep it this way then shall we?

**Comment by HarrySarson** [comment]
The signs of the matrices shouldn't make a difference for any applications of the qr decomposition so I would be happy to leave it as is.

**Comment by josdejong** [comment]
Indeed, agree. Thanks again, will merge your work now.

**Pull request merged**
