### PR TITLE
Matrix exponential

### PR DESCRIPTION
**Pull request by ericman314**
Implementation of the matrix exponential. NOT tested with sparse matrices or with complex-valued matrices.

### CODE REVIEW

**Comment by josdejong** [comment]
Nice Eric, looks good! 

For SparseMatrix input I think we can simply convert to DenseMatrix and return that, until someone implements a version for SparseMatrix. Or convert back to SparseMatrix in the end.

**Comment by ericman314** [comment]
Thanks. You are correct on all counts. I'll commit new changes. `findParams` and `errorEstimate` could be optimized even further but I'll save that for another day.

**Comment by josdejong** [comment]
Nice improvements!

@ericman314 what is the status of this PR? I think we still need to add support for SparseMatrix (simply convert to DenseMatrix), besides that everything looks good to go right?

**Comment by ericman314** [comment]
Yes I think adding support for sparse matrix and unit tests is all we need.

**Comment by josdejong** [comment]
@ericman314 would it be possible for you to finish this PR? Just need to make sure the function works with SparseMatrix input too (that probably already works) and add a few unit tests for that. 

And one more thought: for consistency it should return an Array when input is an Array I think, right now the function always returns a DenseMatrix if I'm not mistaken.

**Comment by ericman314** [comment]
Thank you for the reminder. I'll try to work on it this week.

**Comment by josdejong** [comment]
Thanks!

**Comment by ericman314** [comment]
I did a little research, and I found that the exponentials of sparse matrices are usually not themselves sparse. So I can't see any benefit to performing the calculation as a SparseMatrix, since it would lose its sparcity. So I guess we will simply convert a SparseMatrix to a DenseMatrix, do the regular calculation, and convert it back to a SparseMatrix? And likewise with 2d arrays?

**Comment by josdejong** [comment]
> So I guess we will simply convert a SparseMatrix to a DenseMatrix, do the regular calculation, and convert it back to a SparseMatrix? And likewise with 2d arrays?

Yes I think that is the right approach.

**Comment by ericman314** [comment]
Sorry, I will try to get to it soon.

**Comment by josdejong** [comment]
Thanks. If you have time of course!

**Comment by ericman314** [comment]
You were right about being 95% done. It was all of about three lines to finish it off. I think it should work right, it's been a few months since I've done any real work on the library so I'm a bit rusty.

**Comment by josdejong** [comment]
:joy: that's even easier than I had expected.

Can you please make one small change? Change
```js
      if(A instanceof SparseMatrix) {
        R = new SparseMatrix(R);
      }

      return R;
```
such that (a) in the future we cannot accidentally insert new code between the change of R to SparseMatrix and returning it, and (b) use `type.isSparseMatrix` instead of `instanceof SparseMatrix` so the function will also work with matrices created in a different instance of mathjs, something like:
```js
      if(type.isSparseMatrix(A)) {
        return new SparseMatrix(R);
      }
      else {
        return R;
      }
```
or 
```js
      return type.isSparseMatrix(A)
          ? new SparseMatrix(R);
          : R;
```

**Comment by ericman314** [comment]
Ah, good point. Thanks for the feedback.

**Comment by josdejong** [comment]
:+1: thanks Eric

**Comment by josdejong** [comment]
`expm` is now available in v4.3.0

**Comment by FabienFellay** [comment]
Thank you guys!

**Pull request merged**
