### PR TITLE
Fixed tonne and candela units, added bel and dB

### PR DESCRIPTION
**Pull request by mcvladthegoat**
This PR implements #1209 and #1043

In a few words:
- added new `BASE_UNITS.SOUND_VOLUME` base
- added bel and decibel units
- added tonne (equals to t)
- fixed candela prefixes

### CODE REVIEW

**Comment by mcvladthegoat** [comment]
@josdejong i think it's ready to merge :)

**Comment by josdejong** [comment]
Thanks Vlad, looks good!

@ericman314 can you add these units to [MathUnit](https://github.com/ericman314/UnitMath) too?

**Comment by ericman314** [comment]
Will do.

**Comment by ericman314** [comment]
I'm actually a little unsure about adding `decibel` and `dB`. They are not units in the strict sense. They actually represent ratios between physical quantities on a logarithmic scale, and for that reason alone you can't do regular arithmetic with them. For example, if one machine produces 90 dB of sound while running, then two machines running produce 93 dB, not 180 dB. If we implemented it the same way we do other units, then arithmetic would be meaningless.

There are actually different kinds of dB, depending on the quantities you are measuring. For power, dB = 10 log(P2/P1). But for voltage, dB = 20 log(V2/V1). Since power is proportional to voltage squared, the 20 makes the dB come out the same in each case.

Implementing dB rigorously could occupy an entire library of its own. It could certainly pull in a unit library as a dependency to provide physical quantities. Basically there would be a function where you give two physical quantities, or a single quantity if there is a universally accepted reference level, and the function returns the dB level. Then you could even do arithmetic with the dBs if you want, and the library would give physically meaningful results. I think that could be very useful.

**Comment by josdejong** [comment]
That is a very valid point @ericman314. 

It's a bit similar to temperature conversions between C, F, and Kelvin: that is not a linear but affine relation. And in this case its even a logarithmic scale. Tt definitely needs to be treated in a special way, but I'm not sure that it's _that_ complicated. We could limit `decibel` to only allow `add` and `subtract`, and not allow mixing with other units for example to limit the complexity.

@mcvladthegoat what do you think? I think Eric has a good argument, and in order to make `decibel` really usable we should go a (big) step further, or postpone implementing it for now until we have a clear plan.

**Comment by mcvladthegoat** [comment]
@ericman314 @josdejong Thanks a lot for comments. I apologize for the mistake. I read carefully the article about decibel definition and properties and found that it is wrong to do basic arithmetic with **field** and **power** levels.
I guess first of all I have to make a new pull request without "decibel code". @josdejong correct me if I wrong

**Comment by josdejong** [comment]
No need to apologize, this is simply new insights :)

@mcvladthegoat yes I suggest we remove the decibel support you just added (we can keep tonne). I can do that if you want but a PR would be welcome too. Then we can go back to the drawing board :)

**Comment by mcvladthegoat** [comment]
Ok, doing it right now :) I keep tonne and candela.

**Pull request merged**
