### PR TITLE
Support pow() as an argument for derivative()

### LINKED ISSUE #1259: pow(x,2) failing in math.derivative method
Derivative of `derivative("x^2", "x")` works fine but `derivative("pow(x,2)", 'x')` throws an error.

After debugging, I found that it fails in `funcArgsCheck` as the number of Args is `!= 1`. I guess the `,`(comma) between `x` & `2` in `pow(x,2)` is splitting the string.

Can you please help? Below are the links to MathsJs notepad with the above equations.

Url: http://mathnotepad.com/#contents=N4IgzgLghhCmIC5RlgG1gYwgSwPYDtFRt8ATWAD0QCYAacaAJwkQAZ7Yy2BfesDRrlSoAKrgAOiAMy8QlcY1hgwefGEQBtUADcoqAK7wEIco2y6c22AAoAOiAoA9avdoACexXsBKEPQC2sNBE3Lw6eoaIJrBmFuY29uK4AO7WFLTU3q5uAOQUOb4BQVAhYSC6BkYgfiCBwUihtOGVUTV1JQ3cALr0VowqBNL0%2BuKkMLCkUdSsAIwAHAC0rACcCzPLIjMArAgALLsI0wB0rFJbAFog3EA

screen shot 2018-09-19 at 16 44 25

### PR DESCRIPTION
**Pull request by sam-19**
Add support for the pow() function as an argument for math.derivative().

Fixes #1259.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @sam-19 ! Looks good. 

Can you write a unit test to double check the expected behavior and prevent future regressions?

**Comment by sam-19** [comment]
Sure, I will look into it! May take a couple of days, my schedule being what it is right now.

**Comment by sam-19** [comment]
I have duplicated the pre-existing tests for power operators. The tests in fact revealed that using pow() yields some added benefits (at least in my opinion):
Calling `derivative('pow(x^3 + x, 5x + 2)', 'x'))` instead of `derivative('(x^3 + x)^(5x + 2)', 'x')` returns
(x ^ 3 + x) ^ (5 x + 2) * ((3 * 1 * x ^ (3 - 1) + 1) * (5 x + 2) / (x ^ 3 + x) + (5 * 1 + 0) * log(x ^ 3 + x)) instead of
(x ^ 3 + x) ^ (5 x + 2) * ((3 * 1 * x ^ (3 - 1) + 1) * (5 x + 2) / (x ^ 3 + x) + (5 * 1 + 0) * log((x ^ 3 + x)))
stripping one set of redundant braces from the log().
Same goes for `derivative('pow(x + 2, 1)', 'x')` vs `derivative('(x + 2)^x)` and possibly other examples, where braces can be removed from around the first argument.
Equal results can be achieved by adding the braces around the arguments in pow().

**Comment by sam-19** [comment]
There is a check that keeps failing despite my efforts to bring the branch up to date. I think it may not be a problem on my side. Let me know if there's something else I need to fix.

**Comment by josdejong** [comment]
Thanks @sam-19 , looks good! The failing unit tests had indeed an other cause.

I think the extra parentheses for `^` may be needed to make sure we don't mess up precedence of operators in the exponent, but it could also be that it's simply redundant and we could improve the derivative of `^`.

**Pull request merged**
