### PR TITLE
Added BigNumber support for distance() and intersect() functions

### LINKED ISSUE #991: derivative fails if MathJS configured to use big number
Please see this example: https://jsfiddle.net/mc0fgvxt/
If MathJS is configured to use big number the `derivative` function always fails by throwing an exception:

`TypeError: Unsupported type of value "BigNumber"`

### LINKED ISSUE #992: distance and intersect functions fail if MathJS configured to use big numbers
This similar to #991 but has to do with arrays. 
Please see this self-explanatory example for `distance` function: https://jsfiddle.net/c216nods/1/
The same applies for `intersect` function. Unless every numeric literal is casted to `number` they always fail.

### PR DESCRIPTION
**Pull request by ovk**
This PR fixes  #992 . 
`distance` and `intersect` functions from geometry package now can work with big numbers.

### CODE REVIEW

**Comment by josdejong** [comment]
Nice work @ovk , looks good!

There is one more easy improvement that you can do: right now, the functions `distance` and `intersect` work for `number` and `BigNumber`, but not for `Fraction`. By replacing the `_isNumber` function with the built-in `isNumeric` function, everything should work out of the box for any available numeric types. An additional unit test to validate Fractions would make it complete then :).

**Comment by ovk** [comment]
@josdejong I thought about `fraction` but it seemed to me a bit unrealistic that someone would use these functions with fraction type. `distance`, for example, always does `sqrt` which would have to force the conversion to either number or BigNumber. So from practical standpoint it makes no difference whether you convert fractions to number/BigNumber before feeding it to `distance/intersect` or `distance/intersect` does it for you during calculation.

I can implement it for the sake of API completeness and consistency though. But it raises one question: if you feed `distance` or `intersect` with fractions, should it produce `number` or a `BigNumber`?

**Comment by josdejong** [comment]
Ah, you're right. That's a good point. I thought like it would be convenient to at least accept Fractions as input, though you cannot output fractions since we use functions like `sqrt`. Right now `sqrt` throws doesn't accept fractions: it forces you to choose to convert to either a number or BigNumber. I think that's indeed the behavior that we want. 

I'm not sure if we should extend `distance` and `intersect` with a special error message in case the input is a Fraction, that maybe really helpful. Right now the error message will be something like "Values should be numbers", maybe we should change that to "Values should be numbers or BigNumbers"? Or keep the messages as is, and apply the `isNumeric` function and let the `sqrt` error message for Fractions bubble up? What do you think?

**Comment by ovk** [comment]
I think we should modify error messages for intersect/distance to something like you said ("Values should be numbers or BigNumbers"). Otherwise it might be confusing because the `sqrt` error message doesn't tell you much: `TypeError: Cannot implicitly convert a Fraction to BigNumber or vice versa. Use function bignumber(x) to convert to BigNumber or fraction(x) to convert to Fraction.`. Especially for the cases where no conversion is needed, like calculating distance between (0, 0) and (1/2, 0).

**Comment by josdejong** [comment]
Makes sense. Updating the error messages in intersect/distance is the most clear solution I think (else you get indirect error messages from functions used inside intersect/distance). Would be great if you could update the error messages!

**Comment by ovk** [comment]
Sure, I'll do it later today

**Comment by josdejong** [comment]
:+1:  no hurry

**Comment by ovk** [comment]
@josdejong I updated the error messages as we discussed.

**Comment by josdejong** [comment]
Thanks Oleg!

**Pull request merged**
