### PR TITLE
Fixed simplify to recognize named constants

### LINKED ISSUE #838: Derivative doesn't recognize constants like pi and e
The function `derivative` currently doesn't handle built-in constants like `pi` and `e`:

```js
math.derivative('e^x', 'x') // Uncaught Error: Invalid symbol in rule: e
```

and sometimes a weird indirect error is thrown: 

```js
math.derivative('log(x, 10)', 'x') // Uncaught Error: Invalid symbol in rule: e
```

What is a good way to deal with built-in constants?

### PR DESCRIPTION
**Pull request by tetslee**
This fixes #838.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, nice job! 

Just thinking: currently your solution checks against the list `['true', 'false', 'e', 'pi']`, which is a good start. We do have more constants built-in though. What's a good solution to handle all of these? Maybe just check whether some symbol is defined in the `math` namespace? Or really keep it a controlled list like it is now and expand then when needed? (`simplify` simply doesn't support *everything* of math.js anyway)

**Comment by tetslee** [comment]
I changed it to do a combination of your suggestions - for SymbolNodes in the rule patterns, assume that anything in the `math` namespace is intended as a constant, but also keep a list of supported constants and throw an error if the constant is not supported.

The only problem is if a constant is later added to the math namespace that conflicts with one of the wildcard letters (n, v, _p, c, C). Not sure what to do about that other than adding another test.

**Comment by josdejong** [comment]
Indeed, that's a good point. I think your current solution is a good start: start with a list of known constants. We can always extend this list later on or make it smarter if needed.

I think your PR can be merged as it is now, ok? It's a solid improvement.

**Comment by tetslee** [comment]
OK, merge it as it is.

**Comment by josdejong** [comment]
:+1: thanks

**Pull request merged**
