### PR TITLE
Use codecov to monitor code coverage

### PR DESCRIPTION
**Pull request by harrysarson**
It might be nice to track the coverage of mathjs's tests.

Saying that I am not a fan of the comments codecov sometimes puts into pull requests so we should avoid those if possible.

What do you reckon?

### CODE REVIEW

**Comment by harrysarson** [comment]
Definitely not a fan of the comments - surely they can be disabled though

**Comment by josdejong** [comment]
Fine with me :+1: a bit more awareness about coverage will not do harm, though I don't think we should religiously strive for the magic 100%.

**Comment by josdejong** [comment]
Let's give it a try and see if we like it :)

**Comment by harrysarson** [comment]
If you put 

```yaml
comment: off
```

at https://codecov.io/account/gh/josdejong/yaml I think it will stop codecov commenting.

**Comment by josdejong** [comment]
I've added that configuration, let's see if it makes a change.

**Pull request merged**
