### PR TITLE
Basic quantile implementation and tests (see issues #305 and #354)

### PR DESCRIPTION
**Pull request by BigFav**
There is also an implementation that assumes the input is sorted in ascending order, to maintain an O(1) runtime.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Favian! Two remarks:

- Maybe camel case naming (`quantileSeq` instead of `quantile_seq`) is better to keep it consistent with the rest of the library.
- I was thinking, right now you implemented two functions: `quantile_seq.js` and `quantile_sorted_seq.js`. Would it make sense to present this as a single function, to which you can pass an extra boolean argument to specify whether to sort or not? (Or an object `{sort: boolean}` as last argument)? And if not, I personally would favor `quantileSeqSorted.js` here.

**Comment by BigFav** [comment]
I've been coding too much in non-Java languages recently lol (I went back and changed the variables, but forgot to change the methods).

The reason I did it this way was because it was easy, and this function has quite a bit of optional arguments. I'll try to smash them all into one and add the extra functionality tonight.

**Comment by josdejong** [comment]
Ok cool. But please stay critical in whether this makes the functions esier to understand/use for the user or not. Too much arguments can complicate things too.

**Comment by BigFav** [comment]
This function is usually quite versatile though, where there aren't many arguments, but the arguments can take different forms (e.g. the probability can be singular, a list, or a value indicative of a range). Here is the Matlab API which I was planning on following (excluding the `dim` parameter for now).

http://www.mathworks.com/help/stats/quantile.html

**Comment by BigFav** [comment]
Just re-read your comment. It merging the files via argument will definitely make the code more complex, but that should be expected as it would be an optional argument vs. passing in a boolean because it being implicitly defined in the function name.

**Comment by BigFav** [comment]
How would you feel about only allowing an Array input for the data numbers? Instead of also allowing `quantileSeq(a, b, c, ..., prob)`? It always gets converted into an array anyway, and (I think) that would ease the conversion into `v2`.

**Comment by josdejong** [comment]
> How would you feel about only allowing a collection input for the data numbers?

Good idea, that makes sense and makes the implementation easier. I think in practice you only use this function when working with large sets of data (already available in an Array), and you will not call the function with individual data points anyway.

**Comment by BigFav** [comment]
Yeah, and it's not like it saves memory, since we have to read it from `arguments` and put it in an Array anyway. It's been updated.

**Comment by josdejong** [comment]
wow, the final result looks very neat and simple, thanks!

**Comment by BigFav** [comment]
For accounting purposes lol: #305 #354

**Pull request merged**
