### PR TITLE
explicity list files to be included in npm package

### PR DESCRIPTION
**Pull request by harrysarson**
Rather than add everything to the npm package it is better to only add the nessary files.
This commit lists the files to include based on https://docs.npmjs.com/files/package.json#files

Note that to test this you would have to publish an npm module and manually check that it works.

I propse adding this to v5 #1045.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, I've never used this config to include folders. So far I'm used to specifying which files have to be excluded using `.npmignore`. I think it's a better default to include files by default, what do you think?

See this commit: https://github.com/josdejong/mathjs/commit/8c702f6f8e9d1f3c5d87dfa946e12fbcf96ee1e6

**Comment by josdejong** [comment]
BTW would your PR include the README.md, LICENCE, HISTORY.md, etc?

**Comment by harrysarson** [comment]
Ah I didn't realise mathjs already ignored files. 

I would argue that it is better to *not* include files by default. For example when I added the `node-test` directory it did not occur to me that I should be adding it to an ignore list, it is likely in the future more files/dirs will be added to the top level of the mathjs repo and I think it is better to have to intensionally include them in the build rather let them slip through.

> BTW would your PR include the README.md, LICENCE, HISTORY.md, etc?

image

Eitherway this is no longer a breaking change and it is simply replacing `.npmignore` with the `files` field in the `package.json`.

**Comment by josdejong** [comment]
Makes sense. Ok let's go for the `files` approach then and remove the `.npmignore` file.

Can you update this PR to remove the `.npmignore` file?

I think the list with files should become:
```
CONTRIBUTING.md
HISTORY.md
LICENSE
NOTICE
README.md
bin
core.js
dist
docs
examples
index.js
lib
src
package.json
```
Can you add the missing files to the `files` list (like bin, core.js, index.js)?

**Comment by josdejong** [comment]
Oh, and Travis is not happy because the package.json contains a trailing comma which is not allowed in JSON.

I'm really happy with Travis :D

**Comment by harrysarson** [comment]
`index.js` is included by default as it is the `main` field in `package.json`, would you like me to included explicitly aswell?

**Comment by josdejong** [comment]
Thanks!

I thought you where busy these weeks?...

**Comment by josdejong** [comment]
I've fixed the merge conflict

**Comment by harrysarson** [comment]
oh yeah, I am. I better get back to writing my report  :(

**Comment by josdejong** [comment]
> index.js is included by default as it is the main field in package.json, would you like me to included explicitly aswell?

well, it should go right because `main` points to it following the docs. On the other hand, it may be more clear add it and make it explicit.

**Comment by josdejong** [comment]
> oh yeah, I am. I better get back to writing my report :(

lol I will not disturb you anymore, study should go first

**Comment by josdejong** [comment]
I've added the index.js file, all is done now I think (waiting for Travis which has issues today...)

**Pull request merged**
