### PR TITLE
Bug: When mapping an OperatorNode implicit status is lost

### PR DESCRIPTION
**Pull request by HarrySarson**
See failing test in commit 332ecf3d

### CODE REVIEW

**Comment by HarrySarson** [comment]
Aw travis is a bit confused I will try again

**Comment by josdejong** [comment]
That's odd. Looks like travis has trouble with git:

```
fatal: Couldn't find remote ref refs/pull/1028/merge
The command "eval git fetch origin +refs/pull/1028/merge: " failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/1028/merge
The command "eval git fetch origin +refs/pull/1028/merge: " failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/1028/merge
The command "eval git fetch origin +refs/pull/1028/merge: " failed 3 times.
The command "git fetch origin +refs/pull/1028/merge:" failed and exited with 128 during .
Your build has been stopped.
```

**Comment by HarrySarson** [comment]
Yeah I wanted travis to run on the two commit seperately, but I think I `git push --force`ed one too many times. #1029  worked though.

**Comment by josdejong** [comment]
:+1:

**Pull request closed without merging**
