### PR TITLE
Added missing types 'largerEq' and 'or' in OperatorNodeMap

### PR DESCRIPTION
**Pull request by ajinkyac03**
Resolves https://github.com/josdejong/mathjs/issues/2638.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Ajinkya 👌 

Do you have an idea how we can make sure this map stays up to date with the implementation in `types/index.ts`?

**Comment by josdejong** [comment]
Not directly, I would have to dive into it. If it's not easy to do then let's leave it as it is for the time being.

**Comment by josdejong** [comment]
@ajinkyac03 so shall we leave it as it is right now without extra tests and merge this PR?

**Comment by ajinkyac03** [comment]
@josdejong for now I think it should be merged. You can take call.

**Comment by josdejong** [comment]
👍  sounds good, thanks again.

**Pull request merged**
