### PR TITLE
Removed the incorrect mail of mine

### PR DESCRIPTION
**Pull request by DIVYA-19**
Two mails of mine are mentioned. I removed the incorrect/unnecessary mail address

### CODE REVIEW

**Comment by gwhitney** [comment]
I will go ahead and merge this into develop, so that the email you don't want is removed, but we are going to run into an issue going forward as the AUTHOR list is generated automatically from the commit history. So @josdejong are you able to do "surgery" on the git history so that this wrong email is not re-generated in the future? I am afraid that's beyond my git skills...

**Comment by josdejong** [comment]
Its far beyond my git skills too 😂. I did some googling and found this: 

https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

I gave it a try but didn't manage to fix it (got stuck in a huge amount of merge conflicts whilst rebasing). I'll give it another try soon.

**Comment by DIVYA-19** [comment]
Thanks for sharing. If the branch is existing, that would work. But it's not there that's the issue.

**Comment by josdejong** [comment]
I did some experiments. Does the following "solution" make sense? See PR #2533

**Pull request merged**
