### PR TITLE
Feature/specify import require paths

### PR DESCRIPTION
**Pull request by GreenImp**
### What it changes

There are three main parts of this PR:

1. Add `.js` extension to all the `import` statements in the `src` directory.
    This makes it ES module compliant, as file extensions are [required for ESM](https://nodejs.org/api/esm.html#esm_mandatory_file_extensions), and work for CommonJS as well.
    When scripts are compiled to CommonJS or ESM it retains the file extension in the `import` / `require` statements.
    _I did try to get Gulp to be able to change the extension to `.mjs` for ESM and `.cjs` for CommonJS, but couldn't find a way of doing it._
    _Instead, I had to settle with adding a `package.json` file in the compiled ESM directory to specify the `type: module`, the inverse of the example here: https://2ality.com/2019/10/hybrid-npm-packages.html#variant%3A-avoiding-.mjs It can't be a bad idea if he's suggesting it_ :wink:
2. Adds [conditional `exports`](https://nodejs.org/api/esm.html#esm_conditional_exports) property to the `packages.json` file, which tells node 12+ which files to use, depending on whether you're using `import` or `require`.
  _On node < 12, it will fallback to the `main` property of the `package.json` as it currently does, so there should be no difference there._
3. Changes the Gruntfile so that all compiled scripts are now under a single root directory, `lib`, rather than several different ones.
    We now have:
    - `/dist` -> `/lib/browser/`: The scripts suitable for browser use
    - `/lib` -> `lib/umd/`: The CommonJS / UMD scripts
    - `/esm` -> `/lib/esm`: The ES module scripts

It also removes the root `/number.js` file, as the `exports` points directly to the compiled ones.

### What it fixes

This aims to fix https://github.com/josdejong/mathjs/issues/1928 when trying to use mathjs ESM directly in node, without a package bundler.
Currently, node either tries to load the CommonJS versions and doesn't like it or, if you specify an ESM script it complains about the lack of file extension.

It also attempts to fix the issue https://github.com/josdejong/mathjs/issues/1766 although there's currently an [outstanding issue with Jest](https://github.com/facebook/jest/issues/9771), where it doesn't understand the `exports` property.
However, once Jest _does_ support `exports`, these changes should work for Jest as well, fixing that issue.
In the meantime, you should be able to work around it by being specific with the `import` path:

- `import mathjs/lib/esm/number.js` should work as the `package.json` tells us it's an ESM file.
- `import mathjs/lib/umd/number.js` should also work as it uses CommonJS `require` anyway.

### How it's tested

- I have made sure that `npm run build` still completes successfully, and that the tests all still run and pass (locally, and they also pass in Travis).
- I've tested the changes manually in a separate project, by creating both an `.mjs` and `.cjs` file, importing mathjs and running scripts.
- I've also run it through a bundler (Rollup) and it all still works.
- The automated Travic tests seem to assert that Webpack handles things correctly.

**These changes are very much breaking changes.**

_I'm more than happy to discuss this PR, and happy to make any changes._

### CODE REVIEW

**Comment by GreenImp** [comment]
I can see some of the tests have failed. I'll take a look at them tomorrow.

**Comment by GreenImp** [comment]
I've got the tests passing now.

**Comment by josdejong** [comment]
Wow. Impressive job, thanks a ton for all your effort! This was something I loved to get sorted but I couldn't see the trees for the forest, I'm really happy with it. I'm back from holiday now and finally had time to look into your work.

Must have been a huge amount of work to add all the file name extensions, or did you have some tool for that?

> These changes are very much breaking changes.

:joy: yes

About your points 1, 2, and 3: it makes sense to have all the file extensions as .js with the `"type": "module"` in `package.json`. And the `"exports"` field is really awesome! Good plan to move all output files under `/lib`. I think though that `/lib/umd/` only contains commonjs files, not umd, so maybe we should name it `lib/cjs`. The only place where we have an UMD bundle is under `/lib/browser/`

Feedback:

1.  This is an opportunity to remove the non minified bundle `math.js` and rename the minified bundle `math.min.js` to `math.js` (there is no reason to have the non-minified bundle).
2.  This moving around of all the build folders index files is a serious breaking change. It would be neat to replace the old, removed index files with a file containing just a `console.error('...')` explaining that this file is removed and explain which file should be used now.
3.  I think we can remove some more files from the `"files"` list in `package.json`: `core.js`, `index.js`, `number.js`.
4.  I think we can exclude the `src` folder from the `"files"` list too: a copy of it is in `/lib/esm` now, it is just duplicate I think, right?
5.  In `package.json`, the fields `unpkg` and `jsdelivr` still point to the old `./dist/math.min.js` and should point to `lib/browser/math.min.js` I think.
6.  Are there things that we need to update in the docs?
7.  After checking out your PR and building and testing the library locally, I got a lot of linting errors because there where still old files in `lib` and `es`. It would be neat to keep the `clean` function in the gulpfile backward compatible, still remove `dist`, `es`, and everything in `lib`. What do you think?
8.  Would there be value in also adding the .js file extension to all imports in the unit tests? Currently we need transpiling before we can run the tests with mocha (`--require @babel/register`). Maybe it's possible to run mocha with es modules without transpilation. That could speed up running unit tests quite a bit, and also make it easy to run a single test file with mocha without having to specify the transpilation arguments.
9.  Maybe we can rewrite the node.js examples into esm, or is that too early?
10. Like you, I tested by importing the mathjs library in a separate test project and try to load as esm (see [test_mathjs_esm.zip](https://github.com/josdejong/mathjs/files/5095792/test_mathjs_esm.zip)). It didn't work for me though: when trying to run the .mjs files.

    When running an esm nodejs script I get an error like:

    ```
    $ node .\test.mjs
    import { sqrt } from 'mathjs'
             ^^^^
    SyntaxError: The requested module 'mathjs' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
    ```
    I'm probably overlooking something obvious. Any idea?
    
    And when trying to load into a browser as module, I get this error:

    ```
    Uncaught TypeError: Failed to resolve module specifier "typed-function". Relative references must start with either "/", "./", or "../".
    ```
    Which makes sense to me, I suppose all dependencies must also be called via real paths (no relative node.js specific paths). I'm not sure if we should try to make this work in browsers: loading the library like this leads to almost 1000 requests which is not really something you want to do in a real world application.

**Comment by GreenImp** [comment]
* (1) and (2) Correct! Points 1 and 2 need to be done. If you're happy to do point 1 after the PR has been merged, that would be really appreciated. And I'll look into point 2 now.
* (8) That's a good speed increase!
    This PR sets the packages `type` property to `commonjs`. This is mainly because the gruntfile is written in commonjs and Gulp has no understanding of ESM. I tried setting the `"type": "module"` and renaming the gulplfile to `gulpfile.cjs`, but Gulp will only look for a `.js` extension and there's no way to change it (I can't find a link now, but the official devs aren't planning on supporting it).
    I think a reasonable solution would be to add a `package.json` file inside the tests directory, like we've got in the `/lib/esm/` directory, that tells node it's ESM. That seems to work.
    ```json
    {
      "type": "module"
    }
    ```
* (10) I'm glad that's working for you now!

**Comment by josdejong** [comment]
- (1) ok I'll address removing the non-minified bundle right after merging this PR (to prevent any merge conflicts)
- (2) would be great if you can pick that up backward compatibility messages, thanks!
- (8) I tried out creating a nested package.json in the test folder but it looks like mocha doesn't play nice with that. 

    I have the idea that I'm misunderstanding somthing: when I set `"type": "module"` in the root package.json, we would fix the mocha issue. But then I'm not able to load the library in a regular nodejs+commonjs setup, do you have the same? I would expect that it should be possible to get this combination working. I would love to make ESM first class, and CJS second class, but all should work out of the box with commonjs too.

    Besides that we have to make the right, future-ready decision on the `type` in package.json, I think we can refactor the test into ESM separately from this PR to keep things focused. Unless you're in for doing that too straightaway :). 

- (11) Just another idea on this whole matter: we could also consider publishing two libraries: `mathjs` and `mathjs-es` (that's for example what Lodash does but even that can give issues, see this topic: https://github.com/lodash/lodash/issues/4800). That is not ideal, but if ESM and CommonJS are biting each other too much this at least is a possibility.

**Comment by GreenImp** [comment]
Hey, sorry, I've not had the chance to get back to this for a while.

* (1) Fab!
* (2) Which files do you want to have the messages?
* (8) That's odd, I'm sure I had that working. I'll try again and see.
  
  Setting `"type": "module"` in the root package.json should work fine for both ESM and CommonJS (The `"exports": {...}` property tells node where to look). What issue are you seeing?
  
  The problem that I had, was that Gulp doesn't seem to be compatible with ESM projects, because the gulplfile is written in CommonJS, but has a `.js` extension - if the type is module, node expects `.js` to be ESM.
* (11) I think splitting into two libraries could cause confusion, with people installing the wrong one, and potentially increase maintenance.

**Comment by GreenImp** [comment]
Okay, I've re-checked point 8, and you're right it does have issues, using the nested package.json in the `test` directory.

Firstly it doesn't like the lack of extension in the imports. So I added them.
But then it doesn't like that the `src` directory uses ESM, as the library is still declared as CommonJS.
So I tried adding a package.json in the `src` directory, with `"type": "module"`. But it then complains as some of the source files seem to use CommonJS style exports:

e.g. in `src/bundleAny.js`:
```javascript
module.exports = /* #__PURE__ */ defaultInstance
```

If you set the root package.json to `"type": "module"`, you're correct that CommonJS won't work with the code in this PR; you'll need to add a `package.json file to the `lib/cjs` directory like:

```json
{
  "type": "commonjs"
}
```

Currently it's the other way around, and we have one in the `lib/esm` diretcory.

**Comment by josdejong** [comment]
> Hey, sorry, I've not had the chance to get back to this for a while.

No problem at all! Take it easy. I guess we're in the same boat 😉 

- (2) It would be good to replace the contents of the deleted index files with a `console.error` explaining what's going on and what to do:

    ```
    main/es5/index.js
    main/es5/number.js
    main/esm/index.js
    main/esm/number.js
    number.js 
    ```

- (8) Ahhh, of course! Having `"type": "module"`  in the root package.json, and `"type": "commonjs"` in a new file `/lib/cjs/package.json` folder works for regular node.js. That makes sense. I've tested it on node 14, 12, and 10, and in all cases the "old" commonjs import works, and the esm import works on 12 with flag and 14 without flag.

    I would love to go for an ESM first approach. Do you see any drawbacks/issues in going for `"type": "module"` in the root package.json? What is your take on this?

- (11) I agree. And as far as I can see now the hybrid solution that you've worked out works like a charm 👍 

- (12) I think it would be good to write a few tests to validate that all the entries work, both for ESM and CJS, and with full library or just plain number support. I can look into that if you want.

**Comment by josdejong** [comment]
FYI: I've changed the base of this PR to be merged into `v8` (next breaking version) instead of `develop`. See #1960.

**Comment by GreenImp** [comment]
* (2) Thinking about this; those files aren't in the `exports` list in the package.json file, so if you try to import any of them, node will throw an error like:
  > Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './main/es5/index.js' is not defined by "exports" in /var/www/mathjs-test/node_modules/mathjs/package.json imported from /var/www/mathjs-test/test.mjs
  
  Except for `math/number` (Without the extension), which will still work, as the `exports` points to the lib version.
  
  If you want the `console.error`s, the files will have to be added to the `exports` list, which I'm happy to do. Although I wonder if the error message above is enough of a hint, if it's explained somewhere in the docs?
* (8) The only downside I can see is the the gulp build doesn't work. If the gulpfile can be written using ESM (There's lots of `require` - not sure if they can be replaced with `import`, or if Gulp will run it if you do), or if it can be replaced with an ESM compatible bundler (e.g. Webpback, Rollup), then I think it would be a good idea to move to an ESM first approach.
* (12) To be honest, I've not really looked at the tests, other than ensuring that they still pass. So I'd appreciate it if you could take a look at that.

**Comment by GreenImp** [comment]
I've just found this: https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles/
And this: https://github.com/gulpjs/interpret/issues/65

Which suggests that Gulp _does_ support ESM, if the gulpfile is named as `gulpfile.esm.js`. But there's no way of specifying that it's commonjs, inside an ESM library.
I'll have a play and see if I can get an ESM gulpfile working.

**Comment by josdejong** [comment]
- (2) It's good that there is a clear error, but I prefer putting a bit of effort on our side to give an error message which also explains the user what to do, so the user doesn't have to google to figure out what's going on (it's frustrating enough already when upgrading a library has breaking changes). So yes, please add those 5 files temporarily to the `exports` list and create a console.error in the files offering an explanation.

- (8) good point about the gulpfile, I hadn't thought about that yet. I expect this is solvable. Would be great if you can give it a try, and if you're stuck I can give it a try too. I think it's worth it to go ESM first now. 

    Is it maybe possible to rename the gulpfile to `gulpfile.cjs`, and change the package.json scripts like:

    ```
    "build": "gulp",
    ```
    such that we pass this file explicitly:
    ```
    "build": "gulp --gulpfile gulpfile.cjs",
    ```
    ?

- (12) 👍 I'll have a look into that after merging your PR.

**Comment by GreenImp** [comment]
* (2) Okay, will do.
* (8) Okay, that's new to me! I couldn't find the CLI arguments in the gulp docs, but just found the readme on the Github repo. Wish I'd seen that several weeks ago!
  I've tried that out and it works like a charm. I'll make changes to have it ESM first..

**Comment by GreenImp** [comment]
I've got this mostly working when making the root package.json `"type": "module"`.

I'm having issues with the `src/bundleAny.js` file, because it's written in CommonJS.
I've tried changing the extension to `.cjs` with some success, and I can then successfully build everything. But the tests now fail, because `bundleAny` uses `require` to import ES Modules:

> Must use import to load ES Module: /var/www/mathjs/src/factoriesAny.js
> require() of ES modules is not supported.
> ...
> Instead rename factoriesAny.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /var/www/mathjs/package.json.

So I tried changing it to use `import`, as I thought node supported `import` of an ESM from a CJS file, but alas:

> SyntaxError: Cannot use import statement outside a module

However, on my test project that includes the local repo, I can run both ESM and CommonJS without issues. So it looks like it's only a problem with the tests.
If we can et the `bundleAny` file converted to ESM, then that will probably fix the issue, but I'm not certain how to replicate the export it has, and your comment there seems to suggest you had similar issues:

> // TODO: not nice having to revert to CommonJS, find an ES6 solution

**Comment by josdejong** [comment]
Ai! I see the problem. If I remember well I didn't find a solution to export dynamic output using ES6, or maybe it was that I couldn't get treeshaking working. 

Let me give it a try finding a solution for this. I'm amazed that the library itself indeed does work despite this single commonjs file, only the build/test seem to have issues.

**Comment by josdejong** [comment]
I expect to be able to look into it coming Wednesday.

**Comment by josdejong** [comment]
I have an idea to turn this into a proper ES file: generate all the exports explicitly. Will require a small new build script similar to those other scripts generating index files etc, shouldn't be hard. Let me try that out coming Wednesday!

**Comment by josdejong** [comment]
I now understand why the library works but the tests don't: the `bundleAny.js` file is only used in tests and to generated the browser bundle, it's not used in the ES or CJS output.

**Comment by josdejong** [comment]
It was quite a puzzle but I think I've got everything working. 

I've merged this PR into a new branch in the mathjs repo and created a PR: https://github.com/josdejong/mathjs/pull/1962

Still a few open ends, but getting there 😅

**Comment by GreenImp** [comment]
That's fantastic! Looks good.
Does this mean that this PR is no longer necessary?

**Comment by josdejong** [comment]
Your PR is merged only this page doesn't yet know it because your work is still in a separate feature branch. I expect it to be marked as "merged" by Github automatically once we've merged this feature branch.

**Comment by josdejong** [comment]
I've just published `v8.0.0`, thanks again for all your work Lee!

This PR should be marked as merged already, I'm not sure why it doesn't. Will close the PR now, all your code is in `master`.

**Pull request closed without merging**
