### PR TITLE
Improve API documentation

### PR DESCRIPTION
**Pull request by hgupta9**
**The following improvements have been made:**
- Certain classes annotated with JSDoc compatible tags
- JSDoc2Md used to generate documentation markdown files for Complex, Unit, DenseMatrix, SparseMatrix, Index, Range, ResultSet and FibonacciHeap
- List of classes created with links to the JSDoc generated files (`class_api.md`), and is currently the only way to access the JSDoc-generated files
- `densematrix.md` and `sparsematrix.md` have their constructor sections removed since the new operator is not the correct way to create those objects (I checked the constructors for all the other types and they look fine)
- `acre` and `hectare` units have been added, as well as common aliases for some surface units

**The following changes have been made:**
- API for Complex numbers moved into a new section "API" on the same page
- API for Units moved into a new section "API" on the same page
- Unit reference moved into the `units.md` file

Please tell me if this is fine, and if any changes are required before it gets merged. Thanks.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @hgupta9, looks great. I'm glad with the improvements and extensions you made.

Two little things before we can merge:
- I see a few broken links on the Classes page: Unit, Fraction, Complex etc. links to `docs/api/units.md` instead of `docs/datatypes/units.md`.
- Can you please redo your PR to the `develop` branch instead of master?

**Comment by josdejong** [comment]
ow, and the tests on Travis-CI are failing, we should fix that too of course.

**Comment by hgupta9** [comment]
Thanks. Great you like it. I'll fix the links, but to redo the PR on the develop branch means I should fork the develop branch and diff in my changes again? I'll do it but just confirm first.

I don't know what is travis, and I couldn't figure out if it was the MD verifier or the JS verifier. I have no idea what to "fix".

**Comment by josdejong** [comment]
You can indeed merge hgupta9/master into hgupta9/develop, then merge josdejong/develop into hgupta9/develop to have everything up to date, then create a PR from hgupta9/develop to josdejong/develop. You may get some minor merge conflicts. Alternatively, you can manually copy the files you created/updated on your disk into a fresh clone of the develop branch and do a fresh commit and PR with the changes.

Travis-CI runs the unit tests of math.js, you can go to Travis-CI to check out the terminal output to see what's wrong. You can execute the unit tests for math.js on your own machine by running

```
npm install
npm test
```

All tests should succeed of course :)

**Comment by hgupta9** [comment]
Can I check whats wrong from here?

https://travis-ci.org/josdejong/mathjs/builds/111680046

**Comment by josdejong** [comment]
Indeed, you can click one of the four build jobs to see the terminal output

**Comment by josdejong** [comment]
It's easier though to test locally, this should give you the same error, then you can start debugging to see what's wrong.

**Comment by hgupta9** [comment]
It seems to be something with the aliases I added. Its failing at this line : 2670 of Unit.js

	  // Create aliases
	  for (var name in ALIASES) {
		/* istanbul ignore next (we cannot really test next statement) */
		if (ALIASES.hasOwnProperty(name)) {
		  var unit = UNITS[ALIASES[name]];
		  var alias = Object.create(unit);
		  alias.name = name;
		  UNITS[name] = alias;
		}
	  }

**Comment by hgupta9** [comment]
And do you mean I run *this* on my PC?

> npm install mathjs
> npm test mathjs

**Comment by josdejong** [comment]
Yes, run the unit tests on your own machine and debug and fix what's going wrong before doing a PR. Just for clarity I've added this to the [CONTRIBUTING.md](https://github.com/josdejong/mathjs/blob/develop/CONTRIBUTING.md).

Maybe it's easiest for you to create two new, fresh pull requests and pull them to `develop`:
- One PR containing the new docs
- One PR containing the new unit aliases (these changes are probably the cause of the failing unit tests)

**Comment by hgupta9** [comment]
Continued in https://github.com/josdejong/mathjs/pull/593

**Pull request closed without merging**
