### PR TITLE
fix #2607: improve type definition for createUnit

### LINKED ISSUE #2607: Improve TypeScript definitions of createUnit
`createUnit` function can take as second parameter of type `Unit` but it's missing from type definition

createUnit

I'm using the example mentioned in the docs 
https://mathjs.org/examples/browser/currency_conversion.html.html

https://github.com/josdejong/mathjs/blob/b9586ab33d7cc0eef984b247a359e92772af720d/src/type/unit/Unit.js#L3133

### PR DESCRIPTION
**Pull request by egziko**
Resolves issue #2607

This improves the type definition for `createUnit` function 
I also added an example using `Unit` as definition

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @egziko , this looks good!

Can you please add a usage example in [types/index.ts](https://github.com/josdejong/mathjs/blob/develop/types/index.ts) to make sure the syntax indeed works in TypeScript? (and to guard against future regressions)

**Comment by cope** [comment]
I believe the [documentation](https://mathjs.org/docs/datatypes/units.html) does not match the method signature anymore?

**Comment by josdejong** [comment]
I've looked through the docs and it seems right? Which singature is missing in the docs?

**Comment by josdejong** [comment]
Ah, you're right, I see the optional property `baseName` was missing from the `UnitDefinition` interface. I've added it (not yet published). Thanks for reporting Predrag.

**Pull request merged**
