### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by ericman314**
Basic working simplify function. It uses a term rewriting system. See these:

http://stackoverflow.com/questions/7540227/strategies-for-simplifying-math-expressions
https://en.wikipedia.org/wiki/Symbolic_computation#Simplification

Rules are written using a grammar understandable by `math.parse`, where the first character of each `SymbolNode` in the rule determines the type of `Node` that it will match. The lhs of each rule is matched recursively to subtrees within the expression to be simplified, then the subtree is replaced with the rhs of the rule with the various parts of the original tree substituted in. I've added a few basic rules which I hand-tailored to simplify things like `math.eval(derivative(x*x*x*x))` and so forth. The real strength of the `simplify` function will come from crafting the right rules.

I've left some debug `console.log` statements in so you can see what's happening better. I haven't done any docs or unit tests yet, and I will also need to add a bunch more rules.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, this is quite cool and works great. Nifty idea to create the rules by parsing them from a string, that makes it very easy to write human-readable rules.

A few things I came across:

1. I entered the following (the current outcome of `derivative(3x^2+5x+2, x)`):

  ```
  simplify(3 * 2 * 1 * x ^ (2 - 1) + 5 * 1 + 0)
  Simplified 3 * 2 to 6
  Simplified 6 * 1 to 6
  Simplified 2 - 1 to 1
  Simplified x ^ 1 to x
  Simplified 5 * 1 to 5
  Returning 6 * x + 5 + 0 from simplify
  6 * x + 5 + 0
  ```
  So it looks like there is another optimization possible: the last `5 + 0` is not simplified.

2. In the end of `derivative`, we want to call `simplify` and return that as a result by default.

3. We need to give the usage syntax some more thought: In practice you can to do things like:

  ```
  > derivative(3x^2+5x+2, x)
  6 * x + 5
  ```
  but you probably want to do things like (not supported):

  ```
  > expr = 3x^2+5x+2
  3 * x ^ 2 + 5 * x + 2
  > derivative(expr)
  6 * x + 5
  ```

  Just brainstorming, maybe we can aim for a syntax that can be used like this:

  ```
  > x = symbol('x')
  x
  > expr = 3x^2+5x+2
  3 * x ^ 2 + 5 * x + 2
  > derivative(expr)
  6 * x + 5
  > expr2 = 5x + 3x
  5 * x + 3 * x
  > simplify(expr2)
  8 * x
  ```

  or:
  ```
  > expr = parse('3x^2+5x+2')
  # ... use `expr` in derivative and simplify
  ```

  This needs some more thought. See also https://github.com/josdejong/mathjs/pull/386#issuecomment-107676861

Shall we merge your work so far into `algebraic_differentiation`?

**Comment by ericman314** [comment]
Yes, as `algebraic_differentiation` is experimental I think it's appropriate to merge, even though there is a lot more work to be done with it.

After doing more research, it looks like this is not a trivial problem at all. Most of the literature though is paywalled or written in formal language so abstract I haven't the slightest clue how to read it.

It seems the biggest issue is the associativity and commutivity of addition and multiplication. Take this for example:

`x^2 * y * z * x`

`x^2` and `x` should be combined to `x^3`, but what if the expression were represented internally as `((x^2 * y) * z) * x`? The `x^2` is nested two levels down and the rule matcher can't find it. Mathematica transforms expressions like this into flat structures, sort of like `times(x^2, y, z, x)`, which means you could sort and then combine adjacent terms. I'm still thinking about how to do this with the rule syntax it uses now.

**Comment by josdejong** [comment]
It's an interesting challenge :)

Indeed you either have to flatten consecutive operators/functions like `add` and `multiple`, or you have to create some utility that allows you to traverse up and down in a non-flat tree.

**Comment by Lakedaemon** [comment]
math.js parses expressions into trees that are computer friendly (facilitates computations)
We humans use commutativity and associativity (and human intelligence) to interact and parse expressions into simpler flattened trees
Computer : ((a*b)*c)   becomes [*,[*,a,b],c]
Human  : a*b*c    becomes   [*, a,b,c]

Humans use * and + rather than / and -

There migt be value (simplify, interaction) into functions that transforms a computer tree into an equivalent human tree and back 

For example, I wrote some code to :
1) parse an mathematical expression into a tree
2) display the expression, the TeX output (via mathJax) and the tree (thanks to vis and hierarchcal layout)   
3) vis allow us to select multiple nodes of the tree
4) we could then apply some rewriting rule to change the tree and update displays

Yet, with the (computer friendly) tree built by math.js  changing ((a+b)-c) into (-c) + a+b though doable feels really weird for the standard math student

5) mathJax has a TeX command that allows to set ids on mathJax Html/mathml markup.
This allows clicking on a part of a mathJax displayed equation and map it to a part of the source TeX equation.
I'm not sure if math.js is able to produce this special TeX command though :/
see here : https://groups.google.com/forum/#!topic/mathjax-users/fRGv6pcCXiA

6) there might be value in a function that transforms a math.js tree into a mathml tree (to short circuit mathJax) and simplify interaction
At this time, it is possible to do math.ps tree to TeX to mathJax internal representation to mathml (through toMathml() method)

**Comment by ericman314** [comment]
Thank you all for the input. I'll give it a try this week.

**Comment by ericman314** [comment]
Sorry for taking so much time; I haven't given up. I'm to the point where an expression is reorganized into a flat form with dummy `FunctionNodes` `plus` and `times`. But I'm still working out the best way to apply rewriting rules to a flattened tree. The rewriting rule matches only a subset of the flattened tree, rather than the entire tree, which is making things non-trivial.

@josdejong, can I recommit to this PR or do I need to create another one?

**Comment by josdejong** [comment]
Thanks for the update. No problem at all if things take time, we don't do deadlines here ;) 

I think indeed that if you add new commits to your `simplify` branch they will automatically be added to this PR, and if not, it shouldn't be too hard to create a new PR.

**Pull request merged**
