### PR TITLE
Fixed molar mass of C12

### PR DESCRIPTION
**Pull request by ericman314**
This was the only other mistake I found.

### CODE REVIEW

**Comment by ericman314** [comment]
Also, this is unrelated, but the formatting on the docs here http://mathjs.org/docs/datatypes/units.html got a little messed up somehow. Not sure what happened.

**Comment by josdejong** [comment]
Thanks for reviewing my code, I should have asked you *before* the release... I will do another check myself tonight and then do a bugfix release.

The formatting issue is a markdown thing (could be related to the markdown parser red-carpet), you can circumvent this issue by putting an empty line before the start of a code block. I already fixed that in `develop`.

**Comment by josdejong** [comment]
@ericman314 I just released v2.1.1 on npm. I checked the physical constants once more and even found a third error. Everything should be correct now.

**Comment by ericman314** [comment]
Awesome!

**Pull request merged**
