### PR TITLE
Simplify units before returning numeric value

### LINKED ISSUE #901: Unit's .toNumeric() incorrect immediately after calculation with mixed units
When doing calculations with mixed units, such as multiplying feet and meters, .toNumeric() returns an incorrect value immediately after the calculation. Once .formatUnits() has been called on the result, .toNumeric() returns the correct value.  

An example at http://jsbin.com/wusavigugi/edit?html,js,output shows that 
```
    const a = math.unit(1, 'ft').multiply(math.unit(1, 'meter'))
    document.write(a.toNumeric() + '<br>');
    document.write(a.formatUnits() + '<br>');
    document.write(a.toNumeric() + '<br>');
```

outputs
```
1
meter^2
0.3048
```

### PR DESCRIPTION
**Pull request by AlexanderBeyn**
This should close #901 . There is a separate issue breaking unit tests when run all at once, which I'll be filing shortly.

### CODE REVIEW

**Comment by AlexanderBeyn** [comment]
#903 explains the test issue, which appears as
```
  Unit
    constructor
      ✓ should create square meter correctly
    toNumeric
      1) should simplify units before returning a numeric value


  1 passing (33ms)
  1 failing

  1) Unit toNumeric should simplify units before returning a numeric value:

      AssertionError [ERR_ASSERTION]: 1e-8 deepEqual 0.01
      + expected - actual

      -1e-8
      +0.01
      
      at Context.<anonymous> (test/type/unit/Unit.test.js:259:14)
```

**Comment by josdejong** [comment]
Thanks @AlexanderBeyn for this fix ! And sorry for the late reply - I'm just back from holidays.

One question: shouldn't `this.simplifyUnitListLazy()` be called on top of the `toNumeric()` method instead of halfway? Or call `other.simplifyUnitListLazy()` instead of `this.simplifyUnitListLazy()`? Since we're dealing with `other` only in this method, and other can be replace in the first 
`if (valuelessUnit) {...}` statement.

**Comment by AlexanderBeyn** [comment]
You're absolutely right. I've updated the pull request to use `other` instead of `this`.

**Comment by josdejong** [comment]
Thanks for updating. 

The code looks ok, though the unit test that you've added for this specific use case is failing, can you check that out?

**Comment by AlexanderBeyn** [comment]
I've changed to use mass squared instead of length squared for the units, but this test still feels brittle because of the issue described in #903.

**Comment by josdejong** [comment]
Thanks for the fix. The non-deterministic behavior of units indeed make unit tests a bit fragile.

**Pull request merged**
