### PR TITLE
created digits to calculate number of digits of a number

### PR DESCRIPTION
**Pull request by vicky1999**
To calculate the number of digits in a number. 
<b>Syntax:</b>
    math.digits(x)

<b>Accepts:</b> Number and BigNumber     
<b>Returns:</b> Number of digits in the number

<b>Examples: </b>
     math.digits(100)  -----------> returns 3
     math.digits(0)  ------------->  returns 1
     math.digits(50) -------------> returns 2
     math.digits(501232) ------->  returns 6

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Vignesh for your PR!

A function like `digits` can sometimes be handy, though I'm a bit in search for use cases for this function. Do you have some? I have the feeling that this function is not needed a lot. Also, when needed it is a one-liner `String(Math.round(value)).length` or your approach with log10, so there is no deal-breaker if you have to write it yourself. What do you think?

**Comment by vicky1999** [comment]
Yes, but I thought of finding it faster rather than converting the number to string and then finding the length.

**Comment by josdejong** [comment]
Yes, if you need it it's indeed faster to have it ready-made for you instead of having to create it yourself 😄. 

I have to keep a balance between adding useful functions but also preventing the library from turning into bloatware where you can't see the forest for the trees. At this moment I think the function `digits` is too much of an edge case to add to the library, but if it turns out to be an often requested feature we can always reconsider it. Is that ok with you?

**Comment by vicky1999** [comment]
Okay. cool.

**Comment by josdejong** [comment]
:+1:

**Pull request closed without merging**
