### PR TITLE
Add support for single quotes strings

### PR DESCRIPTION
**Pull request by jean-emmanuel**
This seems to do the job :) (feature request #816)
Edit: basically I just duplicated the double quotes string step, inserted it into the pipeline

### CODE REVIEW

**Comment by harrysarson** [comment]
Currently `'` is the congugate and transpose operator.

It would be great to allow single quote delimited strings but only if we can make it work in whilst keeping the current behaviour of the unary `' ` operator. 

This PR  currently breaks the existing behaviour. Languages like MATLAB have both meanings of `' ` so I think it should be possible.

**Comment by jean-emmanuel** [comment]
I totally missed that point because surprisingly the tests all passed, damned !

**Comment by jean-emmanuel** [comment]
There seems to be tests for the transpose operator that pass fine with this PR, are there more complex cases that fail ?

**Comment by harrysarson** [comment]
Ah okay, if all tests are passing then maybe we are good :smile:

Definitely worth checking for edge cases though.

**Comment by josdejong** [comment]
Thanks @jean-emmanuel . 

Hm, yeah there was the issue with single quotes `'` being used for transpose. I will look into your PR soon and think about if there are any edge cases or conflicts with the transpose.

**Comment by josdejong** [comment]
@jean-emmanuel your implementation looks neat! I had expected this to be tricky because of conflicts with the transpose operator `'` but this doesn't collide at all! It makes sense, since the transpose can only come after something, whilst a string enclosed in single quotes is the start of something.

Thanks!

**Comment by josdejong** [comment]
Even `'2''` works: the transpose of the number 2 as string :joy:  :+1:

**Comment by harrysarson** [comment]
Nice :smile: it would be worth adding a unit test for this.

**Comment by jean-emmanuel** [comment]
Great, thanks a lot ! :-)

**Comment by josdejong** [comment]
Single quotes are now available in `v5.1.0` and I really love them :D

**Pull request merged**
