### PR TITLE
Issue457

### PR DESCRIPTION
**Pull request by johnmarinelli**
(https://github.com/josdejong/mathjs/issues/457)

First draft for the engineering notation feature.  The algorithm is a bit ugly and I want to clean it up, but I wanted to make sure that everything else was good.  I think I may have written too many tests; let me know if you want me to remove some.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks John, nice! Thanks for adding so much unit tests. Cannot do any harm right?

I don't have any remarks here, so as soon as you feel like the implementation is in good shape we can merge it.

I've been struggling with these algorithms too (`toFixed`, `toExponential`, `toPrecision`), to me they still feel too verbose for what they do. Feels like there should be a way to simplify the code. I did go for processing as string to prevent tricky round-off errors you get when processing as number. Anyway if you see ways to improve the code let me know :).

**Comment by johnmarinelli** [comment]
@josdejong great!  I'll leave a comment here when I'm satisfied with the code.

**Comment by johnmarinelli** [comment]
@josdejong i shortened the function up a little bit, but I think the logic of it is clearer now.  Let me know if you have any comments!

**Comment by josdejong** [comment]
Thanks looks good. I think though that the `describe.only(` in the tests should be changed to `describe(`.

One little remark: for better readability I would split line 76 in two, it does do too much for it's own good:
```js
var decimalVal = c.slice(decimalIdx).reduce(function(p, n) { return p + n }, 0) === 0 ? '' : '.' + c.slice(decimalIdx).join('');
```
could become something like:
```js
var decimalSum = c.slice(decimalIdx).reduce(function(p, n) { return p + n });
var decimalVal = decimalSum === 0 ? '' : ('.' + c.slice(decimalIdx).join(''));
```
or maybe something like this:
```js
var decimals = c.slice(decimalIdx).join('');
var decimalVal = decimals.match(/[1-9]/) ? ('.' + decimals) : '';
```

**Comment by johnmarinelli** [comment]
@josdejong totally agree with line 76; I split it up.  and removed the .only from the test.

Let me know if you have any questions/comments.

Happy holidays!

**Comment by josdejong** [comment]
Thanks John! Happy holidays :)

**Comment by josdejong** [comment]
@johnmarinelli I just added some missing docs for the engineering notation (see #645), and I noticed that this notation outputs trailing zeros:

```
math.format(12400,  {notation: 'engineering'}); // outputs '12.400e+3'
```

Shouldn't the trailing zeros be removed?

**Pull request merged**
