### PR TITLE
Add kip unit

### PR DESCRIPTION
**Pull request by hgupta9**
I've added the kip/kips unit as requested by @olimortimer in https://github.com/josdejong/mathjs/issues/554

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Harsh!

**Comment by olimortimer** [comment]
Thanks @hgupta9 

Forgive my ignorance, but how do I build that change into `dist/math.js` ?

**Comment by josdejong** [comment]
The change will be available in the first next release. 

Until then you can clone or download the github library and built the library yourself as described here: https://github.com/josdejong/mathjs#build

**Comment by olimortimer** [comment]
Thanks @josdejong

**Pull request merged**
