### PR TITLE
Update SetCartesian documentation

### PR DESCRIPTION
**Pull request by fieldfoxWim**
When values of a set or array have a meaning e.g. price, age or measurement, it is important that after the calculation you can refer the values back to their original meaning.
The `setCartesian` method does a sort, losing the original positions of the values, making a referral to the original meaning impossible.

It took me days to figure this out as I thought it was a bug in my code.

Maybe there is a good reason for sorting, so I added it to the documentation.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Wim! Sorry to hear you lost so much time here. I'm not sure if there is a special reason to sort the sets. @Nekomajin42 do you still remember?

**Comment by josdejong** [comment]
@fieldfoxWim I see the linter is complaining about trailing spaces, can you remove those?

**Comment by fieldfoxWim** [comment]
@josdejong I have removed the trailing spaces.

**Comment by josdejong** [comment]
Thanks 👍

**Pull request merged**
