### PR TITLE
Bugfix for bignumber divided by unit

### PR DESCRIPTION
**Pull request by ericman314**
Addresses #1269.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for the quick fix @ericman314 !

I think we could use the function `numeric` here, see https://github.com/josdejong/mathjs/blob/develop/src/type/numeric.js. This function is not yet exposed but I think we can use it like:

```js
    'Unit, number | Fraction | BigNumber': function (x, y) {
      const res = x.clone()
      // TODO: move the divide function to Unit.js, it uses internals of Unit
      const one = numeric(1, config().number)
      res.value = divideScalar(((res.value === null) ? res._normalize(one) : res.value), y)
      return res
    },
```

**Comment by ericman314** [comment]
I finally found a good way to do the division between a Unit and a number/BigNumber/Fraction, which doesn't suffer from loss of precision as a result of inverting the unit's value before calling `multiplyScalar` (it just uses `divideScalar` instead), and thus it doesn't require converting the unit's value to match the denominator's type, so that solved most of the issues.

While I was fiddling with `divideScalar.js`, I took a look at `numeric.js` and started to fill it out a bit more, and it kind of turned into a generic conversion function that can convert a string, number, BigNumber, or Fraction into a number, BigNumber, or Fraction. The function is now exposed in the mathjs namespace, although I think `convert` would be a better name for it now, only because it would be probably be used for that purpose by the end user:

```js
convert(fraction(1, 7), "BigNumber")
// 0.1428571428571428571428571428571428571428571428571428571428571429
```

It's actually just a wrapper around the individual conversion functions `number`, `bignumber`, and `fraction`. Since it's nearly an entirely new function after all the changes I made I'm okay with adding the `convert` function in addition to the exiting `numeric` function, although it does do basically the same thing.

**Comment by josdejong** [comment]
That's really neat, converting a Fraction to a BigNumber! Nice improvement.

We may indeed rethink the name of the function `numeric` and make it public, but we can do that separately from this PR. My thought was that this function is somehow symmetric with the function `isNumeric`, and that it is a function to _create_ a numeric value of some type in the first place from a string or any other numeric value. It would be great if we make passing the second argument (type) optional, and use `config().number` as default.

**Comment by josdejong** [comment]
@ericman314 I think it's better to expose `numeric` only after we have decided in a proper name. Will hide it again in the release I'm doing now.

**Comment by josdejong** [comment]
O wait a second, if the function it not exposed it's not easy to load it in a unit test. I will change it to an obscure place `math.type._numeric` for now so we can release this bug fix, let's decide upon a name soon.

Qua naming: I like both `convert` and `numeric`, though I have a slight preference for `numeric` since it describes at least that it has something to do with numeric values, whilst `convert` is quite a vague and generic name which doesn't say much.

**Pull request merged**
