### PR TITLE
Add usolveAll and lsolveAll methods

### LINKED ISSUE #1748: usolve misses solutions
The [`usolve`](https://mathjs.org/docs/reference/functions/usolve.html) function can only find solutions of non-degenerate matrices. On degenerate ones, it automatically sets the free parameters to zero, only returning one solution out of many. For null `b` it only returns null vectors as a result. Example:

```javascript
M = [[-2,3,5],[0,-1,2],[0,0,0]]
b = [0,0,0]

math.usolve(M, b)
// returns [[0], [0], [0]]
// correct result [5.5, 2, 1]
```

(Also, the returned array is two-dimensional for some reason.)

**EDIT**: Related to #1168. Since all non-square matrices are degenerate.
**EDIT**: Also true for [`lsolve`](https://mathjs.org/docs/reference/functions/lsolve.html) and [`lusolve`](https://mathjs.org/docs/reference/functions/lusolve.html).

### PR DESCRIPTION
**Pull request by m93a**
Fixes  #1748, needed for #1743 

In this pull request, I implement [an algorithm](https://www.overleaf.com/read/csvgqdxggyjv) that generalizes front- and back-substitution. Similar to [`usolve`](https://mathjs.org/docs/reference/functions/usolve.html) and [`lsolve`](https://mathjs.org/docs/reference/functions/lsolve.html), `usolveAll`  and `lsolveAll` return **an array** containing the vectors that make up an [affine basis](https://en.wikipedia.org/wiki/Basis_(linear_algebra)#Geometry) of the solution space. This means that all valid solutions can be expressed as an [affine combination](https://en.wikipedia.org/wiki/Affine_combination) of these vectors.

**Example usage:**
```typescript
const M = [[0,1,2],[0,1,1],[0,0,0]]
const b = [2,2,0]
math.usolveAll(M, b)
// [ [[0], [2], [0]], [[1], [2], [0]] ]
```

Previously, `u`-, `l`- and `lusolve` thrown an error when no solution existed. I kept it this way for now, but I'm tempted to return an empty array instead, as there is nothing *bad* or *wrong* about the case when a system doesn't have a solution, and throwing an unnecessary error might force users to write a lot of surplus try-catch blocks.

### CODE REVIEW

**Comment by josdejong** [comment]
Sounds good, thanks Michal! I'll review your work soon. 

Makes sense to not throw an error but return an empty array when there are no solutions. 

Thinking aloud here: we could also think about introducing two versions of the functions like `usolve`: one returning a single solution (the old behavior), and one returning all solutions. Or pass an optional flag as third argument to specify whether you want one or all solutions back.

**Comment by josdejong** [comment]
The code looks very neat Michal, nice job 👍 . There are indeed still extra tests needed to test the new functionality. 

I'm curious to hear your ideas about either changing the behavior of `usolve`, `lsolve` and `lusolve`, or introducing new functions or options somehow in a backward compatible way. I'm not sure if there are still use cases for the old behavior or not.

**Comment by m93a** [comment]
Initially I thought there's no advantage in only finding one solution. But when I think about it again, for very large matrices with low rank, the difference in both computation time and memory usage would be noticable. So you're right, it would be probably best to expose methods for both "find one solution" and "find all solutions".

About the API: I'm strongly for creating a new method instead of making one function with options. A robust API should only have few return types for a method :)

Later today, I'll revert the changes to `usolve`, `lsolve` and `lusolve` and make new methods `usolveAll` and `lsolveAll`.

**Comment by josdejong** [comment]
Makes sense that there will be a performance hit for finding all vs just one solution.

> About the API: I'm strongly for creating a new method instead of making one method with options. A robust API should only have few return types for a method :)
> 
> Later today, I'll revert the changes to usolve, lsolve and lusolve and make new methods usolveAll and lsolveAll.

Sounds like a good plan to keep the methods separate 👍 .  The names `usolveAll` and `lsolveAll` are very clear, and if we reference ("See also: ..." in the comments) it should be clear that these methods exist.

**Comment by m93a** [comment]
Haha I did that, but in the meantime something broke. I tried pulling your commit with `git pull --rebase` but now every test fails 😂️

Could you please help me out with this one? Prior to pulling, all the tests were successful.

**Comment by josdejong** [comment]
😂  Good to hear you figured it out.

> EDIT 3: How do I fix the one error in Travis?

The new function should be added to the following index file so it will be bundled: https://github.com/josdejong/mathjs/blob/develop/src/factoriesAny.js

**Comment by m93a** [comment]
I have done that already: https://github.com/josdejong/mathjs/pull/1916/files#diff-97a500a8c25160352eb28525e7d37613
The problem that causes Travis to fail is that I haven't generated docs for the new functions. And I don't know how to…

**Comment by josdejong** [comment]
Ahh, sorry. There is indeed also the embedded docs. Those are located in the folder:

https://github.com/josdejong/mathjs/tree/develop/src/expression/embeddedDocs/function/algebra

And the index file of the embedded docs is: 

https://github.com/josdejong/mathjs/blob/develop/src/expression/embeddedDocs/embeddedDocs.js

I should make those error messages more explanatory, sorry.

**Comment by josdejong** [comment]
@m93a did you see my latest comment? Want me to fix the embedded docs?

**Comment by m93a** [comment]
Sorry, I didn't have time to reply earlier. All set and ready to merge, sir! 😁️

**Comment by josdejong** [comment]
> Sorry, I didn't have time to reply earlier.

No problem at all! I have the same issue regularly 😄  

Thanks for the updates, will merge your work now.

**Comment by josdejong** [comment]
Published now in `v7.3.0` 🎉

**Pull request merged**
