### PR TITLE
Separate tests that depend on node

### PR DESCRIPTION
**Pull request by harrysarson**
#### Adds new directory 'node-test' for tests which require node.
This is a first step towards being able to run tests in a browser.

1) I am not sure the best place to put these tests - adding a `test/node` directory hid hid these tests and mades running all the other tests except the node ones too hard. If anyone can think of a better place that would be grand.

2) I had to make one actual change as `npm test` was failing due to two different tests (one of which I had just created) were importing the same function into `mathjs`. I added `.create()` to prevent these tests from changing global state.

---

Edit: I have moved the tests from `./test/node` to `./node-test` so that webpack could be configured to not bundle them when creating browser tests. I updated the description to reflect this change.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @harrysarson , these are nice steps in the right direction!

Just thinking aloud: you've now split the node tests into a separate folder. An other way could be to split by file name extension, like `slu.node.test.js` or something like that. Would that make sense or is that just more complicated?

If I now execute `npm test`, the tests under `node-test` are not executed anymore. Would it make sense to have `npm test` still run all tests (node and browser)?

**Comment by josdejong** [comment]
Thinking about it, I think I like the separate folder `node-test` better than file extensions like `*.node.test.js`, this makes it really explicitly.

**Comment by harrysarson** [comment]
> If I now execute npm test, the tests under node-test are not executed anymore.

Ooops, this was not my intention and the reason I originally put these tests in `test/node` was to ensure that they were run. This can though be fixed fixed by changing the command line args to mocha.

> An other way could be to split by file name extension, like slu.node.test.js 

The way that I have implemented browser tests (see #1099) makes it hard to exclude test files when running in the browser so I would prefer the separate directory approach here.

**Comment by josdejong** [comment]
Sounds good, let's go for the separate directory approach. 

Can you fix the arguments of mocha in your PR such that it executes all tests again?

**Comment by harrysarson** [comment]
As of f620fae all tests should now run :tada:

**Comment by josdejong** [comment]
great! Stupid question. shouldn't
```
"test": "mocha test --recursive test node-test"
```
be:
```
"test": "mocha test node-test --recursive"
```
?

Looks like there the folder `test` is listed twice

**Comment by harrysarson** [comment]
:man_facepalming: 

Oops, my bad. Thanks for picking this up, is now fixed in 4e56faaa

**Comment by josdejong** [comment]
:+1:

**Pull request merged**
