### PR TITLE
New function 'isNaN'

### PR DESCRIPTION
**Pull request by FSMaxB**
See #673 .

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Max, looks good!

**Comment by FSMaxB** [comment]
Is there something that I missed? I think there might be missing JSON in `lib/expression/docs/function` or is that autogenerated?

**Comment by josdejong** [comment]
Ah, good point. I've added the file.

Sorry for the late reply, I've had a busy period last months which is almost done now. After the summer vacation period I will finally have time again to work on math.js and other spare time projects. Really looking forward to that.

**Comment by josdejong** [comment]
I've just released v3.3.0 containing the `isNaN` function.

**Pull request merged**
