### PR TITLE
Feature: Implementation of Moore–Penrose inverse function

### LINKED ISSUE #1563: Calculating psuedoinverse of a matrix
It is possible to add function to create inverse of not square Matrix?

### PR DESCRIPTION
**Pull request by HanchaiN**
Fix #1563

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @HanchaiN , your PR looks good 👍 . It supports numbers/bignumbers and array/DenseMatrix/SparseMatrix. It is well tested and documented. 

I see though that one test _"should return the Moore–Penrose inverse of non-invertable matrices"_ is failing, I suppose you want to work out support for that? And are there other things that you want to address?

@gwhitney do you have any inputs on this PR?

**Comment by gwhitney** [comment]
I haven't really looked as it is still marked "draft" by the author. I did notice the examples use invertible square matrices; there definitely should be examples with rectangular and with singular square matrices.

**Comment by HanchaiN** [comment]
Currently, those tests exist (Line 72, 81 of `pinv.test.js`). Still, other algorithms may be needed to pass those tests and make them ready for review.

**Comment by gwhitney** [comment]
Fair, but also some of the _examples_ (in the embedded docs and full jsdoc-style docs that generate the web docs) should also show that the pseudoinverse covers those cases. Thanks! Let us know when you think it's up to par for review.

**Comment by HanchaiN** [comment]
Some precision errors are causing the test to fail. If it's alright, validation tests may be skipped and the return values will only be tested with the expected returns of the inputs.

**Comment by gwhitney** [comment]
This is starting to really shape up, thanks! I haven't looked it over in detail yet, but a few things first:

1) The default accuracy of approx.deepEqual is very mild -- only 0.0001 -- so please see how small an EPSILON you can use in all of the approx calls and still get a pass; hopefully it is something much smaller.
2) Please don't just turn off your very nice checks that pinv gives a valid pinv when a target pinv is supplied in the test. Instead, please leave them in, and to deal with the fact that you get non-matching almost-zeros in symmetric locations, in just the Hermitian tests add 1 to all entries on both sides (with math.add(..., 1)) before testing approx.deepEqual. That will swamp the difference in the tiny zeros. (In the complex case as in the next item, you _might_ have to add 1+i instead of just 1, but try with just 1 first.)
3) Your pinv claims to handle complex entries in the argument matrix, but there are no tests of this case; please add some. 
4) Perhaps you should also add a much larger nonsquare matrix with entries you simply choose at will or generate in some crazy way, and test it without the target pinv, just to make sure it is returning a valid pseudoinverse for a more hefty example (since that's one of the main applications).

Thanks! I'll take a more detailed look when you've had a chance to respond to these requests.

**Comment by HanchaiN** [comment]
Fixed the tests, thanks.

**Comment by josdejong** [comment]
Thanks @HanchaiN for the latest updates. Looks good 👍

**Comment by aapocketz** [comment]
How do I call this from typescript?

**Comment by josdejong** [comment]
It looks like we forgot to add the TypeScript definition. Glen opened an issue to address this #2627. Of course you can always use `// @ts-ignore` to work around it for now.

**Comment by aapocketz** [comment]
Thanks so much I ended up casting it to any and it worked, but the ts-ignore is a good tip.

**Pull request merged**
