### PR TITLE
Treat UnaryMinus around ConstantNode as "c" and not "v" when Simplifying

### PR DESCRIPTION
**Pull request by thatcomputerguy0101**
"v" used to match things like -5, which is clearly constant, but not a ConstantNode. Although not the suggested solution, this is a fix to issue #1406, where more of the issue is described. This was accomplished by editing the statements that match for c and v so that they treat UnaryMinus wrapped ConstantNodes the same as ConstantNodes.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @thatcomputerguy0101 for picking this up!

Can you write some unit tests to verify your fix?

I'm a bit hesitant to adding such special rules for `unaryMinus` in simplify. It feels a bit fragile and could (in the future) lead to hard to understand behavior since the rules are only followed under "certain" circumstances. Is there a special reason you solved the issue this way? Did you also try out simply creating a rule for `-c`?

**Comment by thatcomputerguy0101** [comment]
The reason why I did it this way was that I didn't have a large familiarity with the tree matching process, but after the fact, I realized that it also helps when other rules use negated constants (usually -1, as in rules 15, 21, and 23) or negated generic values (-n, as in rules 12, 17, 20, and 22) so that they still match their constants. If I were to do this by creating a rule for -c, matching a negative constant in a rule would very likely no longer work. The only other solution I see working is changing the parser to parse the unary minus with the constant and changing simplify so that -n and -c can match constants if they have a negative value. I feel that the other solution gets much more complicated due to the downhill effect of changing the tree.

As far as unit tests go, I added two new tests, one for testing the functionality of the feature that I added, the other for testing whether the problem above exists.

**Comment by josdejong** [comment]
Thanks for adding the tests @thatcomputerguy0101. I noticed that `x ^ (-1)` already works though in the current version of simplify, do you have an example that currently doesn't work and _does_ work with your fix?

I have the feeling that the best and most robust solution would be to solve this in `simplify`, since the parser may not be the only source that generates node trees: you can create and manipulate them yourself.

I did a little bit of experimenting by adding the following code to `simplifyCore`, which actually replaces a unary minus containing a constant with the negated constant:

```js
  function simplifyCore (node) {
    if (type.isOperatorNode(node) && node.isUnary()) {
      const a0 = simplifyCore(node.args[0])

      // ...

      if (node.op === '-') { // unary minus
        // ...

        if (type.isConstantNode(a0)) {
          return new ConstantNode(unaryMinus(a0.value))
        }

        // ...
      }
```
This works, but is overwritten by changes made by the `simplifyConstant` rule, which turns negative values into a unary minus operator and a positive constant :D. I guess this is because quite some rules depend on this explicit structure of a unary minus operator node containing a constant. 

So I start to understand why you propose your solution, though it feels a bit like we're fixing an unfortunate side effect  of parsing how the rules are parsed: we cannot express a negative constant in the rules, it's parsed as a unary minus. Would it make sense to look into fixing this by adjusting the way the rules are parsed? After parsing a rule, replace unary minus containing a constant with the negated constant?

**Comment by thatcomputerguy0101** [comment]
The reason why I added the test for `x ^ (-1)` was that it has the negated constant that I was worried might get messed up with other solutions (essentially, those unit tests should be able to be used for other solutions to verify their functionality). I think that this was the easiest way to fix the problem, but the best way would be to change the parser so that the `-` followed by a constant would be parsed as part of the constant. If that was done, then simplify would just have to have a special rule when `-c` or `-n` is encountered and compared to a constant node as well as the function so that when equations are simplified to a state where a unary minus is wrapping a constant, it continues to work. I can try to make it work this way, but there would be many more things that needed changed, resulting in a higher likelyhood of other bugs being introduced.

**Comment by thatcomputerguy0101** [comment]
I also feel that this is better to fix through the code evaluating the rules and not in a rule itself in cases where the default ruleset is overwritten or not used, such as when a custom ruleset is passed as the second argument of simplify.

**Comment by josdejong** [comment]
@thatcomputerguy0101 sorry for the late reply, it's sometimes hard to find enough time to keep up with all github issues.

>  I was worried might get messed up with other solutions

That's exactly my concern too. Before diving into this I didn't know, but now I understood now that the current solution normalizes all inputs (both rules and expression) to postive ConstantNodes wrapped in a unary minus. And at the end, replaces these again with negative ConstantNodes. So that should be consistent and well working behavior.

I'm a bit confused now what we're actually trying to solve in #1406, what the actual problem is. Can you give a code example of what does not work as you expect with the rule parsing right now?

**Comment by josdejong** [comment]
Rereading your comments https://github.com/josdejong/mathjs/issues/1406#issuecomment-464354098 now I understand the case again. So I think it boils down to:

1. for both rules and expressions, a negative constant is always parsed a unary minus containing a positive constant
2. normalization: when simplifying, first all negative constants are replaced by a unary minus containing a positive constant
3. the issue now is: when applying a rule, the outcome may contain a negative constant again, like `-(1 / 2) a` becomes `(-1 / 2) a` becomes `(a * -1) / 2`. So, the constants may not be normalized anymore, causing not all rules to match correctly.

So I think we can try a few different directions:

1. Your first approach, implementing a special case for matching negative constants as being equal to a unary minus containing the positive constant. I'm a bit hesitant about this approach, it feels a bit like fixing a symptom instead of the underlying cause.
2. Make sure the outcome of rules is always normalized again: run the simplifyConstant rules after every applied rule or something like that.
3. Change the whole normalization approach: normalize unary minus containing a positive constant node with a negative constant. This may cause breaking changes but could be worth it.

@thatcomputerguy0101 can you do some more experimentation on how these approaches work out in practice?

**Comment by thatcomputerguy0101** [comment]
Number 2 I get how to implement, but at what point would I be implementing number 3? Integrating what is currently the `unaryMinus` operation as a `negated` data value/negated constant value on the node that it would be wrapped around (and then integrating a fix for old node trees)? Or just doing that for `ConstantNode` nodes?

For testing and comparison of these solutions, are there any other functions that would be likely affected that couldn't be fixed by removing a negative special case?

**Comment by josdejong** [comment]
I haven't entirely thought through the Number 3. It would replace UnaryMinus+Constant into a Constant with negative value. I don't have high hopes for it though: it would change normalization behavior, but still we have to make sure everything stays normalized. 

I have a good feeling about Number 2 as that really resolves the root of the issue (expression not being normalized after applying rules).

**Comment by thatcomputerguy0101** [comment]
I know it's been a while, but I have decided to come back to this. Thinking about it from a fresh perspective, I think that the best way to handle this would be to introduce new nodes that match different parts of the equation. I gave a shot at redoing the available classifications, my results listed below.

- 'n' - Any node
- 'c' - A constant literal (5 or 3)
- 'ce' - A constant expression (-5 or √3)
- 'v' - A variable; anything not matched by 'c' (-5 or x)
- 'vl' - A variable literal (x or y)
- 've' - A variable expression; anything not matched by 'ce' (x or 2x)

Of course, the letters chosen could be changed. They were just what came to mind. I also tried to keep 'n', 'c', and 'v' true to their current implementations to maintain compatibility. I thought about also adding an inverse for 'vl', but I couldn't think of any sensible categorization for it.

**Comment by thatcomputerguy0101** [comment]
One important thing with the solution of adding more node types is that it allows different expressions to 'opt-in' to different definitions of a constant and non-constant. This means that if one context doesn't care about a negative sign and another does, they can each use the corresponding definitions (in the case above 'ci' and 'cl') and happily process their equations without resorting to a custom function processor.

**Comment by josdejong** [comment]
That's an interesting idea @thatcomputerguy0101, introducing more variables in the rules. This is really a long time ago :)

I think we should be careful introducing a lot of new types of variables for the rules, it can also become confusing. We should only add what is actually used by quite some rules. Have you thought trough already how these new rule variables that you propose can be used to solve the original issue with unary minus?

An other idea: since you can also provide a `function(node: Node) -> Node` as rule, we can already try out your idea without having to introduce the rule variables like `ce` right away. To get a feel for it. We can do an experiment by creating some helper functions and writing rules as a JavaScript function like :

```js
function isConstantExpression (node) {
  // ... returns a boolean
}

function myRule (node) {
  return isConstantExpression (node)
    ? ... // simplify one way or an other
    : node // leave untouched
}
```

**Comment by thatcomputerguy0101** [comment]
I haven't entirely thought through the use case for each of these. They just arose out of what I thought made sense for different node classifications. As far as I can tell, it is far simpler to make a text-based rule than a function-based rule, so I thought that more options (within reason) were better. As for the uses I have so far:

- `n` - General node, matches anything
- `c` - Compatibility + cases where a number of a specific sign is wanted (eg. `v^(-c)`)
- `cl` - Logical alias for `c`, so same use cases
- `ci` - Wherever a number of either sign is wanted (my original use case)
- `ce` - Not entirely sure, it just made sense to have
- `v` - Compatibility
- `vl` - Possibly formatting rules? Seems useful by description, but I have nothing specific
- `vi` - Whenever a number of either sign is not wanted, also makes sense for some of the reordering rules
- `ve` - Also not sure, but probably useful if `ce` is

As for fixing the original issue, the `ci` and `vi` pair would function similarly to the `c` and `v` logic of this PR. This means that `ci` matches both ConstantNodes and UnaryMinus-wrapped ConstantNodes and vi doesn't. The difference between my newly proposed solution and the one in this PR is that the new solution maintains compatibility and provides options depending on the use case.

I do agree that it would be good to create helper functions for each of these before going through the effort of implementing the node logic. I'll probably start work on those once there is tentative confirmation on the node-set.

It might also be good to combine this with applying simplifyCore after every rule that changes the tree instead of once every cycle to maintain a consistent behavior. However, shifting simplifyCore out of the rule loop may cause incompatibilities with programs that change its behavior.

**Comment by josdejong** [comment]
> As far as I can tell, it is far simpler to make a text-based rule than a function-based rule, so I thought that more options (within reason) were better.

Yes definitely! I was just thinking aloud about what may be the easiest way to do an experiment with this. It would be nice to do an experiment, see how these extra rule variables work out in practice if we apply them to the existing rule set. I find it hard to imagine all just in my head :). I'm not sure about the exact types of rules that we actually need, a small experiment would help I think.

Where I have a bit doubt is that I'm not sure if this really solves the underlying issue that we originally had. I still have the idea the improving normalization would be very helpful too. 

One question: with "'ci' - An integer literal (5 or -3)", do you really mean integer values only, so `-5.2` would not be a match for `'ci'`?

Are there actual cases where you would like to use `cl` over `ci`, or do we always want to use `ci`?

I have to say I don't have all this matter fresh in my head anymore :)

**Comment by thatcomputerguy0101** [comment]
In relation to the original issue, this solution provides an alternative that, to me, is 100% acceptable. (I am the author of the original issue after all, so I know the problem best.)

However, improving normalization definitely won't hurt anything new, so in my opinion, I might as well improve that too. The one problem that I can identify is that it might break compatibility with anything that copies or modifies the `simplifyCore` rule. I don't know how common it is to modify that rule, so I have no clue how big of a breaking change that would be. I imagine that the `simplify` function would have a new option, either in the options object or as an argument. This would be a boolean to either enable `simplifyCore` (the default) or to disable it. When enabled, it would be applied automatically at the start of `simplify`, then each time after a modification is made through the rules.

`ci` being an integer literal was just a name that came to mind. I did intend for it to include decimals, so I have updated the description accordingly. Might there be some more applicable shortened name for it?

For a case where `cl` is necessary, I imagine `ci` not matching a ConstantNode if wrapped in a unary minus, only the pair as a whole. This makes it necessary for some other method if there is a need to match a minus-wrapped constant specifically. While the default ruleset doesn't make use of that anywhere, there could be a rule that takes negative constant exponents and makes them into fractions. This would be implemented with the following: `{l: 'n ^ -cl', r: '1 / n ^ cl'}`.

**Comment by thatcomputerguy0101** [comment]
The initial version of the additional rules are up at [my account](https://github.com/thatcomputerguy0101/mathjs/tree/more-simplify-rules). Currently, the only changes made were in a new wildcards.js file in the simplify/util/ directory. That file contains functions that are supposed to detect the proposed rules. In the case it isn't clear, the correlation is as follows:
- `isConstantNode` for `c`, `cl` and not `v`
- `isVariableNode` for `vl`
- `isNumericNode` for `ci` and not `vi`
- `isConstantExpression` for `ce` and not `ve`

`isConstantExpression` probably has several missing cases since I don't know exactly what it's input range will be. Also, I allowed units by using `isUnit`, but I'm not sure if that will ever be encountered since units are parsed as `SymbolNodes` by `mathjs.parse`.

**Comment by josdejong** [comment]
Thanks @thatcomputerguy0101 

About improving normalization: good point about backward compatibility and breaking changes, we should be careful in that respect. But would this solve your original issue, when `unaryMinus` containing a `ConstantNode` would be replaced with a ConstantNode having it's value negated? If not, let's leave it out of this discussion. If it does solve the issue, we can think through if the change would yield breaking changes, and if we would like to make the normalization optional or not.

The `isUnit` in your commit will indeed never occur, there is no `UnitNode`, and units are parsed into a `ConstantNode` having a `Unit` as value.

**Comment by thatcomputerguy0101** [comment]
I believe that a change to normalization where constant nodes can’t be wrapped by unary operators would solve my issue. However, it might be difficult for the program to maintain that normalization. Currently, `simplifyCore` does the opposite. Also, it is possible that simplification operations could change a complex operation into a `ConstantNode` which, if the resulting node happens to lie within a `unaryMinus`, would break normalization until `simplifyCore` is run again. I have a feeling that there are other similar cases where normalization is temporarily broken, which when combined with the (minor) breaking change of custom rules that match `-c` not working anymore, results in a solution that I believe shouldn’t be used.

The change I was thinking about for normalization keeps the current normalization standard for the node tree while (hopefully) making the system more rigorous. With the current system, I believe one rule can put the tree in a wired state that could then cause a later rule to make an incorrect change if it is encountered before `simplifyCore`. The change to fix that would be to run `simplifyCore` (or a replacement function) after every rule that makes an edit. However, since I have never actually encountered this problem, it may be better to wait until an actual case of it is found before a fix is made. Additionally, since that problem is only loosely related to this issue, discussion about it should probably be moved to a new issue.

I have fixed the `isUnit` problem in the code I created. If there are no other obvious exceptions, am I clear to start work on changing how nodes are checked?

**Comment by josdejong** [comment]
> I have a feeling that there are other similar cases where normalization is temporarily broken

That is a good argument. I think you're right in that the rules will work more robust when they do not rely on normalized expressions. Applying a rule may indeed lead to a de-normalized structure again. Life would be way easier though if you _could_ rely on having a normalized structure before every rule that you apply. Can it be a solution to run a normalization step after every rule that is applied? (just trying to think through an alternative solution)

**Comment by thatcomputerguy0101** [comment]
If you feel that having `unaryMinus` operations stored within the value of a `ConstantNode` would be better for the normalized state, a similar approach to the one in my previous posts could be taken. The difference would be creating a new normalization function based off of `simplifyCore` to run after every rule that results in a modification. For my idea of that solution, the normalization function would be an extra configuration argument to `simplify` that defaults to the normalization portion of `simplifyCore`.
With either choice for normalization, I think it would be better to have that general logic keeping the normalization in check. Do you have any suggestions for what the normalization scheme for `simplify` should be? From my understanding, most normalization is currently handled by `simplifyCore`, but `simplifyCore` also does low-resource simplification preventing it from being a suitable drop-in normalization function.

**Comment by thatcomputerguy0101** [comment]
If you feel that having `unaryMinus` operations stored within the value of a `ConstantNode` would be better for the normalized state, a similar approach to the one in my previous posts could be taken. The difference would be creating a new normalization function based off of `simplifyCore` to run after every rule that results in a modification. For my idea of that solution, the normalization function would be an extra configuration argument to `simplify` that defaults to the normalization portion of `simplifyCore`.
With either choice for normalization, I think it would be better to have that general logic keeping the normalization in check. Do you have any suggestions for what the normalization scheme for `simplify` should be? From my understanding, most normalization is currently handled by `simplifyCore`, but `simplifyCore` also does low-resource simplification preventing it from being a suitable drop-in normalization function.

**Comment by josdejong** [comment]
Hm. There is currently no "normalization" step, except that you can maybe consider every simplification step also a normalization step 😄 . There is a "two stage" process where `simplifyCore` is fast and limited, and `simplify` is more extensive but slow. This need not necessary be the case but is how it is now. Thinking about it more I do not see a clear solution in that direction, I think your proposal makes sense and will give a robust and straightforward solution.

> I have fixed the isUnit problem in the code I created. If there are no other obvious exceptions, am I clear to start work on changing how nodes are checked?

Ok then lets go for it, you've convinced me 👍 . I'm curious to see how the new node classifications will work out in practice.

**Comment by thatcomputerguy0101** [comment]
The additional wildcard rules are now in PR #1915. However, I did encounter a weird issue when working on it; whenever I ran `npm run build`, it would partially crash my computer forcing me to restart. Fortunately, it still built successfully so I was able to run my tests.

**Comment by josdejong** [comment]
Thanks! I'll review your PR soon.

**Comment by gwhitney** [comment]
This appears to be superseded by #1915 and so should be closed?

**Comment by josdejong** [comment]
Yes, let's close this PR in favor of #1915.

**Pull request closed without merging**
