### PR TITLE
Prefix the cli test with 'node' so it works on windows

### PR DESCRIPTION
**Pull request by Veeloxfire**
Shouldnt provide any issues for other systems I hope but we'll see what the various checks think

### CODE REVIEW

**Comment by Veeloxfire** [comment]
for #1806

**Comment by Veeloxfire** [comment]
This looks a bit weird but it crashed because it failed to download nodejs not because the build failed so Im undoing and then redoing the commit to reset it and hope it doesnt crash this time

**Comment by Veeloxfire** [comment]
After some googling this seems to be an issue with node so Im going to leave this for a bit

**Comment by harrysarson** [comment]
Test fails look spurious to me, have tried restarting the build

**Comment by Veeloxfire** [comment]
Seems to be an error with nodejs servers maybe https://github.com/nodejs/node/issues/

**Comment by harrysarson** [comment]
Yeah, the node servers are having a bad day. Repeated use of the retry button has got this PR green for us.

**Comment by josdejong** [comment]
Thanks @Veeloxfire !

**Pull request merged**
