### PR TITLE
Range with units

### PR DESCRIPTION
**Pull request by dvd101x**
This includes some refactoring and included the capability to use units in range

### CODE REVIEW

**Comment by josdejong** [comment]
So easy 😎 

I think this is ready to be merged after we've merged #2995.

One remark: I think we do have to update the type definitions of `range`, can you have a look at that?

**Comment by dvd101x** [comment]
Yes, I think it should be ok now.

**Comment by dvd101x** [comment]
Yes of course, I don't understand index.d.ts very well, I hope it's ok.

**Comment by josdejong** [comment]
Thanks for the update, the type definitions are correct now 😄 .

**Comment by josdejong** [comment]
Published now in `v11.9.0`

**Pull request merged**
