### PR TITLE
Reduced callback

### PR DESCRIPTION
**Pull request by dvd101x**
Hi Jos,

This is an idea to split the function `applyCallback` in a way that instead of checking the logic on each iteration, it provides a reduced or simplified callback with the intention that each iteration runs faster.

It's currently implemented on `map`, `forEach`, `filter`, `dense` (.map and .forEach) and `sparse` (.map and .forEach)

Here are the results
name | mean v13.1.1  [ms] | std v13.1.1  [ms] | mean PR [ms] | std PR [ms] | Improvement
-- | -- | -- | -- | -- | --
square | 16.32 | 0.71 | 15.6 | 0.65 | 4.41%
map function | 18.27 | 0.53 | 15.81 | 0.53 | 13.46%
map typed single| 54.76 | 0.65 | 30.96 | 0.65 | 43.46%
map typed multiple | 95.53 | 0.63 | 47.91 | 0.4 | 49.85%
mapDense function | 24.03 | 0.41 | 21.48 | 0.54 | 10.61%
mapDense typed single | 69.36 | 0.59 | 36.69 | 0.54 | 47.10%
mapDense typed multiple | 101.42 | 0.52 | 53.45 | 0.52 | 47.30%
mapSparse function | 20.43 | 0.56 | 16.41 | 0.7 | 19.68%
mapSparse typed single | 64.6 | 0.6 | 31.9 | 0.66 | 50.62%
mapSparse typed multiple | 96.45 | 0.72 | 48.84 | 0.65 | 49.36%

The results show a higher improvement for typed functions as it does some tricks with the signatures that are applied from the beginning. For regular functions the main improvement is that it doesn't check if they are typed on each iteration.

This PR is missing updates on jsdocs and it's not implemented on the transform functions.

## Appendix

Ran on an M1 MacBook Air on Safari
Squaring 500 x 500 random numbers and taking a sample of 100 trials with a warmup of 10 trials.

```js
const table = document.querySelector('#tests')

const size = [500, 500]
const a = math.random(size)
const aDense = math.matrix(a, 'dense')
const aSparse = math.matrix(a, 'sparse')

test('square', () => math.dotPow(a, 2))
test('map function', () => math.map(a, x => x**2))
test('map typed', () => math.map(a, math.typed({'number':x => x**2})))
test('map typed m', () => math.map(a, math.square))
test('mapDense function', () => aDense.map(x => x**2))
test('mapDense typed', () => aDense.map(math.typed({'number':x => x**2})))
test('mapDense typed m', () => aDense.map(math.square))
test('mapSparse function', () => aSparse.map(x => x**2))
test('mapSparse typed', () => aSparse.map(math.typed({'number':x => x**2})))
test('mapSparse typed m', () => aSparse.map(math.square))

function test(name, fn) {
    const results = testFunctionPerformance(name, fn, 10, 100)
    print(`<td>${name}</td><td>${results.mean.toFixed(2)}</td><td>${results.stdev.toFixed(2)}</td>`)
}

function testFunctionPerformance(name, fn, warmupIterations = 10, testIterations = 100) {
    // Warm-up phase
    for (let i = 0; i < warmupIterations; i++) {
        fn();
    }

    // Measurement phase
    const times = [];
    for (let i = 0; i < testIterations; i++) {
        const start = performance.now();
        fn();
        const end = performance.now();
        times.push(end - start);
    }

    // Statistics calculation
    const mean = math.mean(times);
    const stdev = math.std(times);

    return {
        name,
        mean,
        stdev
    };
}

function print(string){
    const row = document.createElement('tr')
    row.innerHTML = string
    table.append(row)
}
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>math test new</title>
    <script src="../mathjs/lib/browser/math.js"></script>
    <!--
        <script src="https://unpkg.com/mathjs@13.1.1/lib/browser/math.js"></script>
    -->
</head>
<body>
    <h1>Test new</h1>
    <table >
        <tbody id="tests">
            <tr><th>name</th><th>mean [ms]</th><th>std [ms]</th></tr>
        </tbody>
    </table>
</body>
<script src="mathTest.js"></script>
</html>
```

### CODE REVIEW

**Comment by josdejong** [comment]
This makes a lot of sense, thanks David. I can confirm that this PR makes these functions much faster. I also see that Firefox is doing better than Chrome, that is interesting to know.

I see you created your own benchmark suite. It may be easier to add a new file to the [/test/benchmark](https://github.com/josdejong/mathjs/tree/develop/test/benchmark) folder, alongside the other benchmarks (they use the [`benchmark`](https://www.npmjs.com/package/benchmark) library.

**Comment by dvd101x** [comment]
Thank you, Jos!

I will look into `test/benchmark`

The comparison between Firefox and Chrome is very interesting.

I will include the missing tests for transform functions, jsdocs and tests for utils during the weekend.

**Comment by josdejong** [comment]
I just realize there is another PR putting effort in improving `map` and `forEach`: #3251. Let's make sure to align/unify the efforts.

**Comment by dvd101x** [comment]
Hi Jos,

The main changes are applied and this is ready for review.

The speed results for the parser show comparable improvements.

reduced callback

> **PD:** I had an issue while attempting to run [/test/benchmark](https://github.com/josdejong/mathjs/tree/develop/test/benchmark) with an error due to 'sylvester'
```
TypeError: sylvester.Matrix.datatype is not a function
```

## Data
name | mean [ms] | std [ms] | this mean [ms] | this std [ms]
-- | -- | -- | -- | --
square | 3.35 | 0.48 | 3.37 | 0.49
parser square | 2.74 | 0.72 | 2.42 | 0.5
map function | 2.31 | 0.46 | 2.48 | 0.5
mapDense function | 3.49 | 0.5 | 3.33 | 0.47
mapSparse function | 2.73 | 0.55 | 2.47 | 0.5
parser map function | 2.47 | 0.52 | 2.41 | 0.49
parser mapDense function | 3.49 | 0.5 | 3.45 | 0.5
parser mapSparse function | 3.07 | 0.7 | 2.84 | 0.44
map typed | 6.9 | 0.59 | 4.46 | 0.5
mapDense typed | 10.14 | 0.75 | 5.82 | 0.56
mapSparse typed | 9.5 | 0.56 | 5.01 | 0.52
parser map typed | 9.68 | 0.51 | 5.02 | 0.57
parser mapDense typed | 10.64 | 0.56 | 6.08 | 0.56
parser mapSparse typed | 10.05 | 0.86 | 5.68 | 0.87
map typed m | 13.78 | 0.73 | 7.36 | 0.48
mapDense typed m | 15 | 0.62 | 8.47 | 0.52
mapSparse typed m | 13.96 | 0.4 | 7.58 | 0.55
parser map typed m | 14.43 | 0.62 | 7.56 | 0.54
parser mapDense typed m | 15.36 | 0.52 | 8.69 | 0.56
parser mapSparse typed m | 14.54 | 0.7 | 7.72 | 0.51

**Comment by josdejong** [comment]
wow great visualisation 😎. This PR looks really good, I like that you managed to replace all these `recurse` functions with a unified solution. And the performance improvements are of course great. Nice job David!

> **PD:** I had an issue while attempting to run [/test/benchmark](https://github.com/josdejong/mathjs/tree/develop/test/benchmark) with an error due to 'sylvester'

Someone accidentally changed `sylvester.Matrix.create(fiedler)` into `sylvester.Matrix.create(fiedler, sylvester.Matrix.datatype())` recently and someone else didn't spot that when reviewing [#3235](https://github.com/josdejong/mathjs/pull/3235/files#diff-bedda4091ef77b17308fd4f05ceae219a062a7b9c0a572e3024bca3786d25674) 😉 . I've fixed it now.

Two feedbacks:

1. Do you still want to add a file with some tests to the benchmark section? (not a requirement for me)
2. Not a big deal, but I'm not entirely sure about the name `simplifyCallback`. The name makes sense but I myself directly associate that with the `simplify` function. How about a name `preprocessCallback` or `optimizeCallback`? If you have a strong preference for `simplifyCallback` though I'm fine with that.

**Comment by josdejong** [comment]
I've updated the benchmark `/test/benchmark/map.js`. If you want you can extend it with some tests for `forEach` or create a separate file for that.

**Comment by josdejong** [comment]
This `test/benchmark/map.js` gives the following results, confiming what you found: it doubles the performance of `map`.

```
# develop

abs(genericMatrix)                         x 54,106 ops/sec ±0.59% (96 runs sampled)
abs(array)                                 x 620,327 ops/sec ±0.51% (95 runs sampled)
abs(numberMatrix)                          x 48,865 ops/sec ±1.48% (92 runs sampled)
genericMatrix.map(abs)                     x 21,191 ops/sec ±0.62% (95 runs sampled)
numberMatrix.map(abs)                      x 19,951 ops/sec ±2.38% (94 runs sampled)
map(genericMatrix, abs)                    x 20,971 ops/sec ±0.56% (93 runs sampled)
map(numberMatrix, abs)                     x 20,036 ops/sec ±0.82% (93 runs sampled)
map(array, abs)                            x 21,609 ops/sec ±2.15% (93 runs sampled)
map(array, abs.signatures.number)          x 20,754 ops/sec ±2.60% (90 runs sampled)
genericMatrix.map(abs.signatures.number)   x 50,100 ops/sec ±1.08% (92 runs sampled)
numberMatrix.map(abs.signatures.number)    x 45,769 ops/sec ±0.94% (92 runs sampled)

# reduced-callback

abs(genericMatrix)                         x 55,721 ops/sec ±0.73% (92 runs sampled)
abs(array)                                 x 617,838 ops/sec ±1.74% (92 runs sampled)
abs(numberMatrix)                          x 50,944 ops/sec ±0.73% (93 runs sampled)
genericMatrix.map(abs)                     x 42,582 ops/sec ±0.68% (93 runs sampled)
numberMatrix.map(abs)                      x 40,060 ops/sec ±0.57% (93 runs sampled)
map(genericMatrix, abs)                    x 42,728 ops/sec ±0.55% (95 runs sampled)
map(numberMatrix, abs)                     x 39,682 ops/sec ±0.78% (94 runs sampled)
map(array, abs)                            x 48,888 ops/sec ±1.21% (92 runs sampled)
map(array, abs.signatures.number)          x 49,144 ops/sec ±0.85% (96 runs sampled)
genericMatrix.map(abs.signatures.number)   x 57,944 ops/sec ±0.66% (94 runs sampled)
numberMatrix.map(abs.signatures.number)    x 53,214 ops/sec ±0.64% (96 runs sampled)
```

There is one big outlier here: `abs(array)` is more than 10x faster than all other map combinations. I have opened a separate issue to discuss this, see #3262. I think it's best to first merge this PR before diving into this new optimization opportunity, one thing at a time 😁 .

**Comment by dvd101x** [comment]
Wow!

Thanks for the thorough performance check!

After some review of #3262 I agree with you, one thing at a time. First this PR and then #3262.

**Comment by josdejong** [comment]
@dvd101x any thoughs on the latest two feedbacks in https://github.com/josdejong/mathjs/pull/3256#issuecomment-2328222417 ? Besides that the PR is ready.

**Comment by dvd101x** [comment]
Oh sorry. I only read the latest comment and didn't noticed there where previous ones. 

Thanks for fixing the benchmark tests! Now they work for me.

1. Yes, I will add some.
2. Valid points, I agrre. I will change the name.

**Comment by dvd101x** [comment]
Btw. During the day I had a chance to read your comments more thoroughly and I understand what you mean about the changes that generated the Sylvester error 😅.

Someone should get better sleep to avoid making unintended errors. 😇

**Comment by dvd101x** [comment]
Hi Jos,

This PR is ready for review.

While working on this PR I found some interesting stuff that I would like to bring to your attention:
- I found some opportunities to merge other recurse functions, like the ones in collection.
  - Thought maybe the recurse functions should be on collection instead of array.
- I noticed that forEach doesn't accept `matrices` in develop as it's recurse function accepts only (value, index). 
   https://github.com/josdejong/mathjs/blob/0f87a7b6c3456166cf355d8fc768a8fc9063847e/src/function/matrix/forEach.js#L48
- While working on the benchmark of `forEach` I noticed it works different in develop than in this PR. The printed output shows an object on develop and I don't know why.
- I had some ideas to optimize the callbacks further while working on #3262, I tried implementing them in this PR with fewer changes and I had some promising results. I could continue here or in a new PR.

**Comment by dvd101x** [comment]
Thanks!

**Comment by josdejong** [comment]
Published now in `v13.2.0`

**Pull request merged**
