### PR TITLE
setops v4

### PR DESCRIPTION
**Pull request by Nekomajin42**
- using sort() again
- update the tests with unsorted input

### CODE REVIEW

**Comment by Nekomajin42** [comment]
Yep, I messed up my branches again. Sorry.

**Comment by josdejong** [comment]
:+1: looks ready to merge. 

Lets await the discussion in #837 before merging OK?

**Comment by Nekomajin42** [comment]
Ok.

**Comment by josdejong** [comment]
I will merge now, the discussion looks settled. We still have to make changes in `develop` according to the outcome but that will hardly impact the implementation of the set functions (simply a matter of calling the natural sorting version of `sort`. 

Thanks again!

**Pull request merged**
