### PR TITLE
Implicit multiplication

### PR DESCRIPTION
**Pull request by ericman314**
Modifies precedence of implicit multiplication, addressing #792.

I've screwed up package-lock.json. Any idea how to remove it from my PR?

### CODE REVIEW

**Comment by FSMaxB** [comment]
Find the commit where it was added, do an interactive rebase `git rebase -i v4` and put `edit` in front of that commit. Also `drop` in front of the commits where you try to remove it.

Then when the rebase stops, 'git reset HEAD^', this will undo the commit. Then `git checkout package-lock.json` and `git commit' where you type in the commit message again. After that `git rebase --continue`

**Comment by FSMaxB** [comment]
And in case of panic: `git rebase --abort`.

**Comment by josdejong** [comment]
It's ok with me to leave the changed package.json in the PR, no need to spend time there.

**Comment by ericman314** [comment]
Thanks, @FSMaxB, but in my case panic has long since given way to resignation. Now that I know about package-lock.json I'll make sure not to stage it in the future.

**Comment by josdejong** [comment]
@ericman314 first, I'm really impressed and very happy that you managed to pull this off, this is a really tough challenge.

Some feedback points:

1. The extensive documentation is very clear!
2. In the examples table in the docs, I think `1 / 2i ` is duplicate with `3 / 4 mm` (we could keep both). Can you add two mor examples? `pi / 2 pi` and `J/mol K`? I think then we show all the special combinations with.
3. It's a neat implementation, easy to follow!
4. Inside `parseRule2`, there is quite some copying of `token`, `token_type`, `comment`, `index`, and `c` going on. Maybe you can create helper functions for this? Something like 

    ```js
    var id1 = storeState()
    // ...
    rewindState(id1)
    ```
5. The unit tests on implicit multiplication are really improved this way :thumbsup: 

The cases that still surprised me a bit when going through the unit tests are: 

- `8/2a/2 -> ((8/2)a)/2`. I understand this one and I think we should keep it like this
- `2^3a -> (2^3)a`. Should implicit multiplication have higher precedence than power. I think we should keep it like this

**Comment by FSMaxB** [comment]
> 2^3a -> (2^3)a. Should implicit multiplication have higher precedence than power. I think we should keep it like this

I think this will just confuse people again and we will get more issues.

This is kind of late for the discussion, but maybe there should be a distinction between implementation with and without space in between.

I think always giving implicit multiplication without space a higher precedence, even over power might be a good heuristic.

**Comment by josdejong** [comment]
Letting behavior depend on whether there is a space or not is an interesting idea. I think we've discussed it somewhere, I didn't explore into that direction because I expect that this will result in confusing, unpredictable behavior.

**Comment by ericman314** [comment]
@josdejong, good suggestions. I will make those changes.

@FSMaxB, I agree that `2^3a` looks like it should be parsed as `2^(3*a)`. The idea of using whitespace to alter the parsing is intriguing, but I would hate to start a precedent that we would regret later. As far as I know, no other parts of the parser are aware of whitespace except for `parseBlock` which separates expressions by newlines. As Jos said, it could very well become confusing. And the question until now has always been about the relative precedence of different kinds of multiplication. Elevating implicit multiplication above power is a radical step up from that. If we make too many changes at once, even for a major release, it might confuse a lot of people.

Thanks for sharing the video. Well done and very informative!

**Comment by FSMaxB** [comment]
We'll see what people make of these changes. Learned lessons can then be applied in v5 XD

**Comment by josdejong** [comment]
> We'll see what people make of these changes. Learned lessons can then be applied in v5 XD

:D agree

I think the current version of Erics implementation is the nicest we can get. Let's go for the behavior as it is right now.

**Comment by josdejong** [comment]
@ericman314  I see you last two commits, looks good! Ready to merge?...

**Comment by ericman314** [comment]
Yes it is ready.

**Comment by josdejong** [comment]
:+1:

**Pull request merged**
