### PR TITLE
Changed expressions/syntax in docs to represent the actual result of string operations.

### PR DESCRIPTION
**Pull request by HarrySarson**
The comments now represent the result of each line of code.

I added some extra lines to show the value of the string `a` after each modification to it.

### CODE REVIEW

**Comment by HarrySarson** [comment]
I am not convinced that this is the best way to do it, but at least it is correct

**Comment by josdejong** [comment]
Thanks for finding this. How about changing the comment to:

```js
parser.eval('a = concat("hello", " world")'); // String, "hello world"
parser.eval('size(a)');                       // Matrix [11]
```

**Comment by HarrySarson** [comment]
Comment changed :), I also removed the first `parser.eval('a');` as it is unnecessary and clutters the example.

Reading the docs, when a property in an object is changed the whole object is returned. This is presumably why who ever wrote the example assumed the whole string was returned when a character was set in the string. Therefore it might be worth adding an explicit mention that only the range/character changed is returned.

**Comment by HarrySarson** [comment]
This fixes #743

**Comment by josdejong** [comment]
Thanks!

**Pull request merged**
