### PR TITLE
function to compute mode

### PR DESCRIPTION
**Pull request by kv-kunalvyas**
- wrote a function that computes the most frequently occurring value
- wrote basic test cases
- added an entry for the function in lib/math.js

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks! 

A few remarks:

- Could you please add more unit tests for edge cases like when there isn't a single data value which has the most occurrences (like `mode(1,2,3)`), or when an empty array is passed, when a multi dimensional array is passed, etc.
- I think the problem with your merge #398 is that you're still on the old `v1` develop branch, whilst I've recently moved the develop branch of `v2` to `develop`, see https://github.com/josdejong/mathjs/issues/279#issuecomment-109763419. Can you please adjust the function `mode` for math.js v2? You can check out other methods to see the difference in structure.

**Comment by kv-kunalvyas** [comment]
In merge #398, I had made a pull request to merge `josjejong/mathjs develop` to  `josjejong/mathjs master` (yes, I am still a beginner to github).

However, I worked with adjusting the old format code in `mode.js` to the new format, and I am getting an error **TypeError: undefined is not a function**. When I received this error in the previous version of develop, I added an entry in `lib/math.js` and that fixed it. But now, I saw in the updated branch that the file isn't there anymore. I notice `index.js` has replaced it.

 I'm unable to figure this out. So, one way I think this should work is to close this pull request, and fork a fresh copy of the repository and make a pull request again.

**Comment by josdejong** [comment]
It may be easiest to take an existing function as example and create the function `mode` from this. Indeed the files are now indexed per category in [`index.js`](https://github.com/josdejong/mathjs/blob/develop/index.js), and individual functions are indexed in an index.js per category, like [`lib/function/statistics/index.js`](https://github.com/josdejong/mathjs/blob/develop/lib/function/statistics/index.js). The signature of the factory functions has changed to exporting a function `factory (type, config, load, typed) {...}` and exporting the function `name` (see for example [max.js](https://github.com/josdejong/mathjs/blob/develop/lib/function/statistics/max.js#L91-L92)). All functions are now created as a `typed-function`, which takes away the type-checking burden from the functions, you can see how to use it from other math.js functions or from the [docs](https://github.com/josdejong/typed-function).

**Comment by kv-kunalvyas** [comment]
Created a new pull request #417. Closing this one.

**Pull request closed without merging**
