### PR TITLE
Add transform for jsinspect report

### PR DESCRIPTION
**Pull request by Josef37**
#2054 pointed out duplication analysis with jsinspect, but I couldn't handle that one big output.

This routine will transform the output. Each duplication result now has its own markdown file, where you can more easily view the different instances.

If you're using VSCode you can easily see a preview of those markdown files with the `yzhang.markdown-all-in-one` extension (hitting `Ctrl+Shift+V` for preview of current markdown file).

### Usage
```
# make sure pwd is project root
npx jsinspect -t 50 -r json ./src > ./jsinspect/report.json
node ./jsinspect/transform-report.js
```
Browse the different results within VSCode using "Markdown all-in-one" extension.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Josef for your work!

If I understand it correctly, this script turns the output from jsinspect into some better readable form? I'm not sure if this script needs to be part of the source code of mathjs, it feels a bit like this is a once-in-a-while analysis. 

Did you already look into the cases that jsinspect comes up with? Do you have some ideas to improve the code based on the jsinspect outputs?

**Comment by Josef37** [comment]
> If I understand it correctly, this script turns the output from jsinspect into some better readable form? 

Yes, it really just splits each duplication into its own file.

> I'm not sure if this script needs to be part of the source code of mathjs, it feels a bit like this is a once-in-a-while analysis.

It really is a once-in-a-while thing. But I didn't want to paste the code into the issue to make using it easier.  
I should have change the target of the pull request to be a new branch.

> Did you already look into the cases that jsinspect comes up with? Do you have some ideas to improve the code based on the jsinspect outputs?

I had a look through 25 % of them.
There are many I would ignore. Like matrix transformations setting up the same algorithms with `createAlgorithm`. I guess the type system could cause some minor duplication. Maybe I should try different options in jsinspect.  
Some duplication could be avoided though. 

Would you like me to collect those duplications and attach them here (since they are only markdown files now)?

**Comment by josdejong** [comment]
Posting all duplications will not add much value at this point I think, most interesting to me is to pinpoint opportunities where we can actually improve the code. 

Trying to deduplicate all those small duplications will probably not help: the generalization would probably give more overhead and complexity than it solves. Indeed, maybe you could try to tune `jsinspect` such that it only returns larger pieced of duplicate code, removing the "noise"?

**Comment by Josef37** [comment]
> Posting all duplications will not add much value at this point I think, most interesting to me is to pinpoint opportunities where we can actually improve the code.

That's right. I thought about only posting the most important ones.

> Trying to deduplicate all those small duplications will probably not help: the generalization would probably give more overhead and complexity than it solves. Indeed, maybe you could try to tune `jsinspect` such that it only returns larger pieced of duplicate code, removing the "noise"?

I'll try that.

**Comment by josdejong** [comment]
> That's right. I thought about only posting the most important ones.

That would be nice indeed 👍

**Comment by Josef37** [comment]
Most of the bigger duplications come from variable initialization for similar algorithms (like `lSolve` and `uSolve`) or by the same calls to `createAlgorithm`.
Another source of duplication is error handling/input checking.

I've added relevant markdown output in the most recent commit, since it's faster than unzipping them for analysis.

And since comparing the issues this way is very annoying, I've created a tool where I could see them side-by-side: https://github.com/Josef37/jsinspector
The sample data are the same as above.

**Comment by josdejong** [comment]
Good idea to put your scripts in a separate, generic repo that you can use with any jsinspect output 👍 .

> Most of the bigger duplications come from variable initialization for similar algorithms (like `lSolve` and `uSolve`) or by the same calls to `createAlgorithm`.
> Another source of duplication is error handling/input checking.

So are these things that we can improve upon in your opinion?

**Comment by Josef37** [comment]
I think putting variable initializations into functions (bundling five initializations like `const algorithm10 = createAlgorithm10({ typed, DenseMatrix })`) will add too much overhead, since you have to unpack these afterwards.

The [ones I commited](https://github.com/Josef37/mathjs/tree/duplication-analysis/jsinspect/major) are worth looking at in my opinion. They are mostly inside the same file/folder and repeat concepts, rather than variables.

If you think they are worth de-duplicating, I'll give it a try (in another PR, since this one's a little crowded :smile:).

**Comment by josdejong** [comment]
Thanks. I've had a look at [all the cases you've listed](https://github.com/Josef37/mathjs/tree/duplication-analysis/jsinspect/major).


1.  `Node.prototype.toString`, `Node.prototype.toHTML`

    https://github.com/Josef37/mathjs/blob/duplication-analysis/jsinspect/major/5c0d791a21efb555d018db47d74489f898b37829.md

    I think this code could be extracted into a method `getCustomString` so you can execute `const customString = this.getCustomString(...)` twice.

2.  Seven `*.transform.js` functions

    https://github.com/Josef37/mathjs/blob/duplication-analysis/jsinspect/major/8bbb8b0b66cf5117c92dd5d0dfeec657c1741e4e.md

    This would be very nice to extract into a helper function. I think that is possible, it's quite contained piece of code and repeated 7 times.

3.  `SparseMatrix.diagonal` and `DenseMatrix.diagonal`

    https://github.com/Josef37/mathjs/blob/duplication-analysis/jsinspect/major/c81ff268315cec18450bfb62a8903e6e75ad12ba.md

    I think we can extract this into a helper function. I'm a bit in doubt though whether this would help making the code easier to understand and better maintainable or not, it's not really a piece of code that is usable on it's own. What do you think?

4.  Other cases

    https://github.com/Josef37/mathjs/blob/duplication-analysis/jsinspect/major/19f2ca8cf6cf1b26d9b075c29e313b018a752774.md
    https://github.com/Josef37/mathjs/blob/duplication-analysis/jsinspect/major/23a49e612d99aa84dd6f9ffecaf4ff18584a9106.md
    https://github.com/Josef37/mathjs/blob/duplication-analysis/jsinspect/major/b96470aaba7798b82906f6bc6d19fad9b7db123a.md
    https://github.com/Josef37/mathjs/blob/duplication-analysis/jsinspect/major/bcd39f911a3aaa7a5d7a4b1d147eee472c2532a2.md
    https://github.com/Josef37/mathjs/blob/duplication-analysis/jsinspect/major/f5a3d49c0d7e811502684627fb6799d88d3d057c.md

    I think those cases are not self contained enough, and trying to extract them will not result in simpler code. But please prove me wrong if I'm overlooking something here :)

**Comment by Josef37** [comment]
Looking at your feedback I agree. Seems like going through 100 duplication cases made me report some minor issues 😅 

I'll have a go at the first three the coming days. 

(Closing this PR since I'll open a new PR for these changes)

**Comment by josdejong** [comment]
👍 thanks

**Pull request closed without merging**
