### PR TITLE
Add axis for sum request 1244

### PR DESCRIPTION
**Pull request by bnlcas**
Changed sum.js to accept a dimension input when the first input is a matrix (this follows the architecture used in mean.js.
Updated the unit test and the documentation to reflect this change.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @bnlcas , that looks really neat! Thanks.

One thing we have to think about: in the expression parser we choose one-based indexes to have an API that's familiar for mathematicians (similar to Matlab for example). Therefore we've introduced transform functions to transform between one-based and zero-based. 

Cany you implement a transform function for `sum`? You can take `concat.js` and `concat.transform.js` as an example, this also has an optional last argument which is the dimension.
https://github.com/josdejong/mathjs/blob/develop/src/expression/transform/concat.transform.js

**Comment by josdejong** [comment]
@bnlcas have you seen my latest comments?

**Comment by bnlcas** [comment]
@josdejong, my apologies for letting this slip. I just added a sum.transform function to the branch, please let me know if there are further considerations to be had for this feature.

**Comment by josdejong** [comment]
Thanks for your update @bnlcas! I will review/test it within a few days I hope, all looks good at first sight.

**Comment by josdejong** [comment]
I did some testing @bnlcas and all works like a charm, will merge your extension now. Thanks again!

**Comment by josdejong** [comment]
Benjamin your extension of the function `sum` is now available in `v5.4.0`.

**Pull request merged**
