### PR TITLE
Add matrix datatypes in more cases

### PR DESCRIPTION
**Pull request by dvd101x**
In some cases when using the create method from a matrix, it's datatype is missing, thus if the matrix had a datatype, it gets lost.

Additionally for the function size, it probably is always of the type 'number' which modifies some tests for size. This is only included for exploration and could be removed and no tests would need modification.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks David, this is a nice fix and improvement! It makes sense to me to add proper `datatype` whenever possible, that can improve performance when operating on the matrices.

It looks like there is still one unit test that expects datatype to be undefined but now gets back `number`, can you look into that?

On a side note: I see that in this PR all CI tasks are executed twice (once for `pull_request` and once for `push`, that is a bit overenthusiastic. I guess we can improve the GitHub actions script to not run it twice.

**Comment by dvd101x** [comment]
Thanks for the review Jos!

I'm trying to solve the issue. I did solve the unit test in my local machine. When I try `npm run test:node -- --debug-docs` it doesn't throw an error anymore. I don't understand why it's still failing on CI.

Could you please aid me with that?

I could also include new tests for the datatypes, to validate that the functions maintain the datatype of the incoming matrix in cases it applies.

**Comment by josdejong** [comment]
I've been looking into this. It is hard to track down where the error originates but it is triggered by the following example line in the file of `size.js`:

https://github.com/josdejong/mathjs/blob/57611685a1fefce7b145b2e3cd430b0ce2f0c656/src/function/matrix/size.js#L18

And it is triggering because in `doc.test.js` there is code that compares the examples and the commented outcome with their actual outcome. The issue is that the actual outcome is a DenseMatrix with datatype `number`, but the script creates a DenseMatrix based on `[]` which has a datatype `undefined`. I'll figure out a proper solution for this tomorrow.

**Comment by josdejong** [comment]
Ok fixed it via cf5e8d88683777310cfb0ed9237951a4cfc5c73c 😅 

Merging your PR now.

**Comment by dvd101x** [comment]
Thanks!

**Comment by josdejong** [comment]
Published now in `v13.1.0`

**Pull request merged**
