### PR TITLE
10% matrix multiplication improvement

### PR DESCRIPTION
**Pull request by Wikunia**
It costs a lot of time to check whether `result === null`. So I changed the result to 0 at the beginning.

### CODE REVIEW

**Comment by josdejong** [comment]
He, that's a nice simplification. 

I'm not sure whether this is a safe improvement: it assumes that any data type can be added to zero (but for example you can't add zero to a Unit). In the current state of math.js this will work fine (units don't yet support multiplication), but I'm not sure whether this assumption will bite us in the future.

Note that as soon as we have support for typed matrices, and you know for example that you are dealing with a matrix only contains numbers, you can write a very simple, highly optimized loop to do matrix multiplication there (no type checking needed etc).

**Comment by Wikunia** [comment]
Yes typed matrices will be much faster. BTW one question to the docs of the matrix multiplication function: "The size of the matrices is not validated* does it mean that the funtion should throw an error if it's not possible to multiply these matrices?

**Comment by josdejong** [comment]
When you have a 2D array, it can be unbalanced, like `[[1,2], [3]]`. There are tests for this executed when you construct a new Matrix, or when you call `array.size()`. 

We should of course only validate this one time, there is no need to validate this again and again for every internal function. The comment that "The size of the matrices is not validated" just informs that this method *assumes* the input Arrays are in good shape.

**Comment by Wikunia** [comment]
Ah okay I read it like the input matrice sizes aren't validated so the function needs to check it so the other way around. And in my question I meant the multiplication size so: Matrix A is 2*3 and B is 2*3 so A*B isn't possible.

**Comment by josdejong** [comment]
Ah ok. All validation stuff and error throwing is already done beforehand in the main multiply function, so these internal functions like `_multiplyMatrixMatrix` can just assume everything is ok.

I think it will be more clear to replace the comments `The size of the matrices is not validated.` with `This function assumes input arrays have a valid size`?

**Comment by Wikunia** [comment]
Yes okay I have to look deeper into the code someday :D Would like to improve your library cause I love math and JS :D

**Comment by josdejong** [comment]
Thanks! There is lots of room for improvement of performance, and as soon as we have modularized functions as discussed in #280 for v2 of the library, it will become easy to actually improve on this. Is it ok with you to close this issue now and leave this optimization for `v2` of the library?

**Pull request closed without merging**
