### PR TITLE
Fix performance problem with deepStrictEqual

### PR DESCRIPTION
**Pull request by tomlarkworthy**
Issue #2300

deepStrictEqual was called twice for each property

### CODE REVIEW

**Comment by Yaffle** [comment]
it can be non-enumerable in a, but enumerable in b (joke)

**Comment by josdejong** [comment]
That is a really good find! Thanks Tom. 

Does this fully solve #2300, or is the custom deepStrictEqual function still much slower that the one from lodash?

**Comment by tomlarkworthy** [comment]
Pretty sure the observed performance problem was the O(n^2) complexity that I later discovered. So I would say #2300 is fixed.

**Comment by josdejong** [comment]
Nice, that's good to hear! I'll close #2300

**Pull request merged**
