### PR TITLE
refactor: :label: Add symbolicEqual function to Typescript definitions

### LINKED ISSUE #2960: Missing `symbolicEqual` from _types/index.d.ts_
Should `symbolicEqual` also appear in this file?

If this looks correct, I can open a PR with the changes:

```diff
diff --git a/types/index.d.ts b/types/index.d.ts
index 67b9d09aa..fd05af220 100644
--- a/types/index.d.ts
+++ b/types/index.d.ts
@@ -973,6 +973,21 @@ declare namespace math {
     ): MathNode
     simplifyCore(expr: MathNode | string, options?: SimplifyOptions): MathNode
 
+    /**
+     * Determines if two expressions are symbolically equal, i.e. one is the
+     * result of valid algebraic manipulations on the other.
+     * @param {Node|string} expr1 The first expression to compare
+     * @param {Node|string} expr2 The second expression to compare
+     * @param {Object} [options] Optional option object, passed to simplify
+     * @returns {boolean} Returns true if a valid manipulation making the
+     * expressions equal is found.
+     */
+    symbolicEqual(
+      expr1: MathNode | string,
+      expr2: MathNode | string,
+      options?: SimplifyOptions
+    ): boolean;
+
     /**
      *  Replaces variable nodes with their scoped values
      * @param node Tree to replace variable nodes in

```

### PR DESCRIPTION
**Pull request by juancodeaudio**
I've added the symbolicEqual function to the Typescript definitions in 'types.d.ts' inside the MathJsChain interface.

Closes #2960

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Juan!

We need to define the function `symbolicEqual` twice: once the regular definition, and once for the chained definition. Can you add both definitions? Maybe easiest is to look up the two definitions of the function `equal` for example to understand the idea.

Also, when you run `npm run lint` you can check if there are linting issues, and most of them can be fixed automatically by running `npm run format`.

**Comment by juancodeaudio** [comment]
Sure, i'll work on that!!

**Comment by juancodeaudio** [comment]
@josdejong I just added both definitions. As you said, I followed how the "equal" function is defined. Let me know whether it's complete now

**Comment by josdejong** [comment]
Thanks for the update, this is close. The function doesn't accept `MathType | string` though, but `MathNode | string`, can you change all occurrences of that? And since the function does not support matrices, it will always return a `boolean` and not `MathCollection`.

**Comment by juancodeaudio** [comment]
@josdejong thank you for the feedback. I already changed those types, hope it's ok now.

**Comment by josdejong** [comment]
Thanks for the update, all looks good 👍

**Comment by josdejong** [comment]
Published now in `v11.12.0`

**Pull request merged**
