### PR TITLE
Add time units (Issue #520)

### PR DESCRIPTION
**Pull request by owenversteeg**
As described in #520. Just a simple addition of units -- the more complex case can be considered later.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, this is a good start. I think it would be good to add a note below the reference table explaining that these new units are based on Julian years.

**Comment by owenversteeg** [comment]
Ok great, just added that note.

**Comment by josdejong** [comment]
Thanks again!

**Comment by owenversteeg** [comment]
No prob, thanks for merging!

**Pull request merged**
