### PR TITLE
Rationalize. Is it almost ready?

### PR DESCRIPTION
**Pull request by paulobuchsbaum**
Unfortunately, my workflow in this project was stupid, because never in my life I've worked in a shared project (`GitHub` or `SourceForge`). So brench, fork, clone (in that sense), pull request, push (in that sense), commit (in that sense) it was all greek words for me.

So I worked in the cloud (`GitHub` site).  I had cloned to local folder only to change the flles locally and testing locally . 

 However, I don't used the `commit` command.  I've changed the files locally, tested them using my local    `mocha ` and manually copy the changed files to my repository in the cloud.
 
Now, I guess that it is different. It's much easier, but know I know ....

Steps that I've followed:

**1)** I Downloaded `GitHub DeskTop` . I'm tired of command line mode.
**2)** I went to original ( `josdejong/mathjs`) repository
**3)** I clicked in green button `Clone or Download`
**4)** I saved the  link https://github.com/josdejong/mathjs.git 
**5)** I cloned it in `GitHub Desktop`
**6)** I created there a new  `new_rationalize` branch
**7)** I added  2 files: `rationalize.js`, `rationalize.test.js` and changed one (`index.js`)
**8)** The changed files was showed in  `GitHub Desktop` in a fancy way.
**9)** I clicked in `Commit` button in `GitHub Desktop`
**10)** I've changed the repository address for my fork (`paulobuchsbaum/mathjs`).
**12)** I've clicked in the `push` option in `GitHub Desktop`
**13)** In my cloud repository I've clicked in the `pull request` button
**14)** I wrote this message.
**15)** I clicked in `Create a Pull Request` button online
**16)** The Travis CI test was made and it's OK
**17)** Now I am here ...

Is it everything ok?

### CODE REVIEW

**Comment by josdejong** [comment]
Yeah that looks good, and Travis is happy too :)

I've changed the base to `develop`

Can you cleanup the out-commented debug code? Then everything is ready to merge I think...

**Comment by josdejong** [comment]
Thanks Paulo, mission accomplished :D

**Comment by josdejong** [comment]
@paulobuchsbaum I just came across one issue (though maybe I overlook something): detailed results for rationalizing `"2x/y - y/(x+1)"` returns an expression which has a numerator/denominator, but `numerator` and `denominator` are `null` in the detailed results?

```js
math.rationalize("2x/y - y/(x+1)", true)
// {
//   "numerator": null, 
//   "denominator": null, 
//   "coefficients": [], 
//   "variables": ["x", "y"], 
//   "expression": (2 * x ^ 2 - y ^ 2 + 2 * x) / (x * y + y)
// }
```

**Comment by paulobuchsbaum** [comment]
This expression has 2 variables, then I don't retrieve the coefficients, but I should, in any case, fill in the numerator and the denominator. I'm going to fix this now.

**Pull request merged**
