### PR TITLE
Round off errors in fix, ceil, and floor

### PR DESCRIPTION
**Pull request by ericman314**
Gracefully handles round-off errors in `fix`, `ceil`, and `floor` with values of type `number`. Doesn't work for `BigNumber` yet.

Addresses #868.

### CODE REVIEW

**Comment by josdejong** [comment]
:+1: nice! Are you also planning on implementing this for BigNumbers, so the behavior is consistent between numbers and BigNumbers?

I just realized that the relational functions for Fractions don't have nearly equal logic at all. We may want to implement a nearly equal for Fractions too. Would be a new task, not in this PR perse.

**Comment by ericman314** [comment]
For BigNumber, yes. Should we use the same config.epsilon even though
BigNumbers will have higher precision?

I don't think it's necessary for fractions since they are exact by nature.

**Comment by josdejong** [comment]
of course, you're right about fractions, no need there since the're exact representations.

As for the config.epsilon of bignumbers: I haven't thought of that so far. Currently the [nearlyEqual](https://github.com/josdejong/mathjs/blob/master/lib/utils/bignumber/nearlyEqual.js) function of BigNumbers uses the same epsilon as numbers (`1e-12` by default). For BigNumbers you indeed may want a smaller epsilon, and you can indeed configure so. I'm not sure if it's worth creating a separate epsilon for BigNumbers or do other smart things here, since it will probably also complicate things.

**Comment by josdejong** [comment]
Hi @ericman314 , any progress on this one?

**Comment by ericman314** [comment]
None yet. It would probably be ok to use config.epsilon since if the user
configures for BigNumber he can set epsilon at the same time. There will
always be instances where the default epsilon isn't good enough.

**Comment by josdejong** [comment]
Indeed, I think it is just fine to use the existing `epsilon`, keep it simple

**Comment by josdejong** [comment]
@ericman314  we should still finish this PR some day (add the same behavior for BigNumbers), it's a nice improvement!

**Comment by ericman314** [comment]
I'm going to finish this up and resubmit the changes as another PR.

**Pull request closed without merging**
