### PR TITLE
refactor(gamma function): use lanczos approximation with comments

### PR DESCRIPTION
**Pull request by kmdrGroch**

### CODE REVIEW

**Comment by kmdrGroch** [comment]
@josdejong done :) it will be a little bit slower i guess since i am using all these abstractions on top, but at least should be readable :D

**Comment by josdejong** [comment]
Looks good @kmdrGroch , thanks! 

I'm wondering, would it be useful to add extra unit tests for very large values and very small, nearby or equal to zero, around 0.5 (mentioned in the comments), or are the current unit tests just fine?

**Comment by kmdrGroch** [comment]
I will see what is already now and let you know :)

**Comment by kmdrGroch** [comment]
I have added additional 3 tests for complex numbers :)

**Comment by josdejong** [comment]
Nice, thanks a lot Bartoz 👍

**Pull request merged**
