### PR TITLE
Use exact values for US liquid volume units

### PR DESCRIPTION
**Pull request by Vistinum**
1 US gallon is defined as 231 cubic inches, which is exactly 3.785411784 L (since 1 inch is defined as 25.4 mm). Other units are defined against the gallon.

I additionally moved the duplicate definitions into aliases.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, this is a nice improvement, also with using the aliases more.

I'm a bit in doubt on whether we should publish this refinement in the unit values as a minor fix or as a breaking change. What do you think?

**Comment by Vistinum** [comment]
> I'm a bit in doubt on whether we should publish this refinement in the unit values as a minor fix or as a breaking change. What do you think?

I can see why this can be seen as a breaking change (as it did break a unit test here), but I can't think of a situation a less accurate value would actually be relied upon outside of automated testing. So I would say a minor fix, but perhaps it's better to err on the side of being more cautious.

**Comment by josdejong** [comment]
Thanks for thinking along. I'll merge it as a minor fix. The unit values didn't actually change, they are only refined with more digits. When testing with floating point numbers, we should always test with limited precision and the two tests in this PR that needed adjustment are not doing that (they do an `assertStrictEqual`).

**Comment by josdejong** [comment]
Fix published now in `v13.0.3`. Thanks again!

**Pull request merged**
