### PR TITLE
Add arcseconds to list of angle units

### PR DESCRIPTION
**Pull request by devdevdata222**
This adds arcseconds as an angle unit. Helpful to me, at least....

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, should we also add `arcsecond`, `arcminute`, and `arcmin` to make it complete?

**Comment by devdevdata222** [comment]
Good thought. arcmin makes sense. However there does not seem to be consistency in having definitions for short names and long names. I see identical definitions for 'g' and 'gram', but in the angle units, there is 'grad' but no identical definition for 'gradian'. What are your thoughts on this? That will help guide my further actions. Thanks!

**Comment by josdejong** [comment]
Good point, we could add `degree`, `gradian`, and `radian` as well. And also add their plurals to the list  `PLURALS` in Unit.js (maybe we should rename `PLURALS` to `ALIASES` for more clarity).

**Comment by devdevdata222** [comment]
Clarifying PLURALS changing to ALIASES - would that be intended to eliminate the duplicate identical definitions of 'g' and 'gram''? For example, then, there would be a single full definition for 'g', and then in aliases, 'gram' and 'grams' both point to 'g' in ALIASES? Similar, a definition for 'rad',  and then 'radian' and 'radians' both point to 'rad' in ALIASES? Thanks!

**Comment by josdejong** [comment]
We can create `degree`, `gradian`, `radian`, `arcsec`, `arcsecond`, `arcseconds`, etc as alias as these units do not have prefixes. This doesn't hold for `g` and `gram`, as these two units have prefixes (`kg`, `kilogram`, etc), and each have a different set of prefixes.

**Comment by devdevdata222** [comment]
I screwed up these changes in my repository so I reset and created a new pull request, #507. So I'm going to close this one out and we can continue the discussion from #507, sorry about that. I am admittedly a git/github newbie.

**Pull request closed without merging**
