### PR TITLE
Add "sigFig", i.e. the ability to round numbers to a given number of significant figures

### PR DESCRIPTION
**Pull request by SwamWithTurtles**

### CODE REVIEW

**Comment by josdejong** [comment]
@SwamWithTurtles I see this PR is still open. It would be great if you could redo the PR to the `develop` branch.

**Comment by FSMaxB** [comment]
The `round` function already supports this feature. The documentation is a bit misleading, but you can actually use the second parameter to specify the number of digits you want to round the value to, so this `sigFig` function is unnecessary, or am I misunderstanding something?

**Comment by josdejong** [comment]
The difference is that `round` rounds a number of digits behind the decimal point, whilst `sigFig` to a number of significant digits, so `round(0.01234, 3)` returns `0.012`, whilst `sigFig(0.01234, 3)` returns `0.0123`.

**Comment by FSMaxB** [comment]
Oh, I get it.

**Pull request closed without merging**
