### PR TITLE
Complex Roots

### PR DESCRIPTION
**Pull request by gangachris**
working on nthRoot for complex numbers. (De Moviers)

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Ganga, looks good!

**Comment by josdejong** [comment]
I've merged your PR and moved it from `v2` to `develop`, the `v2` branch was redundant but I hadn't cleaned it up yet.

Thanks again.

**Comment by gangachris** [comment]
Ok Thanks. 
I'm relatively new to this. So if i have improvements I should make a PR to develop?

**Comment by FSMaxB** [comment]
Yes, take a look at https://github.com/josdejong/mathjs/blob/master/CONTRIBUTING.md

**Comment by gangachris** [comment]
Ok. Thanks Max

**Comment by josdejong** [comment]
> So if i have improvements I should make a PR to develop?

Indeed. We're close to releasing a breaking v2, and recently switched branches (see https://github.com/josdejong/mathjs/issues/279#issuecomment-109763419). Sorry for the confusion.

**Pull request merged**
