### PR TITLE
Add CDNJS version badge in README.md

### PR DESCRIPTION
**Pull request by sufuf3**
This badge will show the version on CDNJS

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for the PR, but I would like to keep the amount of badges a bit limited. There is a badge for npm, I think that's enough.

**Comment by sufuf3** [comment]
Thanks for response.
I thought CDNJS is one of the most famous free and public web front-end CDN services which can help people choose the CDN service to reduce their host loading.
So I sent this PR.
But I respect your decision.

Many thanks.

**Comment by ericman314** [comment]
There is a link to the CDN download on mathjs.org/download.html, which the README links to, but it's easy to miss. Could it be beneficial to include the link itself on the README, perhaps in the usage section below "npm install mathjs"? Usually when I find a new library the first thing I look for is how to download it and start using it. I admit that sometimes I just want to copy a link into my <script src="..."> as fast as possible without having to think about it too hard. Not everyone will be developing for a server environment where npm install makes sense.

**Comment by josdejong** [comment]
Good idea. I've extended the download section with links to various CDN's:

http://mathjs.org/download.html#download

For example at cdnjs you can then copy either the link, a script tag etc. Is that what you mean @ericman314 ? Or do you mean more like a code example on the download page?

**Comment by ericman314** [comment]
The links on the Download page are perfect. I don't think a code example is necessary.

I also had in mind putting a download link in the README.md on GitHub, if it doesn't detract from the purpose of the README. Sometimes that's where people might land when searching for mathjs.

**Comment by josdejong** [comment]
Makes sense. I've updated the readme in the develop branch to make this more clear:

https://github.com/josdejong/mathjs/blob/develop/README.md#usage

**Pull request closed without merging**
