### PR TITLE
Extend Index implementation to support set of values

### PR DESCRIPTION
**Pull request by rjbaucells**
This is the pull request that implements the solution proposed in #367 

Changes:

- Allows the expression parser to use a set of values as a Matrix index
````
A = [...]; // MxN matrix
p = [1, 2, 3];
B = A[p,:]; // Rows 1, 2 and 3 of A
C = A[:,p]; // Columns 1, 2 and 3 of A
````

- Allows the JavaScript code to use an array as a possible dimension value for an Index (breaking change!)

````
A = [[...]]; // MxN matrix
p = [0, 1, 2];
B = A.subset(math.index(p, p)); // submatrix with rows 1, 2, 3 and columns 1, 2, 3 of A
````

- Renamed the `Index.prototype.range()` operation to `Index.prototype.dimension()` since now Index supports `Range` and `Set` instances.

- Introduced the `Set` type to represent the set of values for an Index dimension. `Set` type contains the same operations as `Range` so consuming code should not change.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, looks neat. It would be nice to support arbitrary arrays with index values again.

- I'm not sure what's exactly the added value of the new data type `Set` over using a regular `Array`. Is it that you want to cache min and max values? If there is no strong reason for it, I would prefer to keep things simple and just use an Array?
- I'm not sure if `Set` would be a good name, it will probably give confusion with the new ES6 `Set` (which is an unordered list of non duplicate values, like some other languages have too).
- We still need to think through the implications for using `Index` in JavaScript notation. I think the most common use case is to either have an index containing a scalar (single row/column), or select a range like `0:100`.

  ```js
  // old notation:
  var B = A.subset(math.index(2, [0, 99]));

  // new notation:
  var B = A.subset(math.index(2, new math.type.Range(0, 99)));
  // -> ouch! that's way more verbose and it was already too verbose :(

  // pitfall in new notation (will expand the range of the first dimension):
  var B = A.subset(math.index(2, math.range(0, 99, 1)));
  // -> what is the performance implication? 
  // -> or do we need a new utility function here? That probably works confusing too
  // -> or must `math.range` get an extra flag such that it can return a Range object?

  // just as an idea: a different notation could be:
  var B = A.subset([2, math.range(0, 99, 1)]);
  // that can be a confusing though when passing an array with index values with 
  // some replacement:
  var B = A.subset([[0, 2], [1, 2]], [[7, 7], [7, 7]]);
  ```

**Comment by rjbaucells** [comment]
Jos, 

I agree with your comments, I originally though on implementing it with an Array, that can be changed without problems. I implemented it as a new type to have the same operations as Range so the consuming code would not have to change, as an example is the Matrix implementations of `subset()` that works the same with Range or Set in the Index dimensions. Caching the min and max was something that came out as an advantage. The Set name was the first name that came out of my mind.

The JavaScript verbosity is something that I could not find a nice solution. The idea of an extra parameter to `math.range()` was something that I was going to propose as a possible solution to avoid expanding the Range values.

I think it is important to support specific indices in an Index dimension, as I mentioned before that is something I am needing for the LU and QR factorizations with full pivoting. I can implement the permutations inside those functions but I will need to replicate the code in more places or create a utility function for that and since the syntax already exists for Matlab and Scilab the correct place for the implementation is the Index type.

 A limitation of not supporting specific indices in an Index dimension is that there is no way to validate the result of LU factorization with full pivoting in the expression parser, see an example (code that I have in my [sparse branch](https://github.com/rjbaucells/mathjs/tree/v2-sparse), not ready yet):

```
A = sparse([....]); // sparse matrix
f = slu(A, 1, 0.001);  // sparse LU factorization with full pivoting, returns object with L, U, p and q where A[p, q] = L * U
````
We need to permute matrix `A` using the permutation vector p for rows and q for columns (`A[p,q]`). The workaround is create matrices `P` and `Q` out of the permutation vectors and perform the operation `P * A * Q`, thing that I think cannot be done in the expression parser (I am not sure on this one).

**Comment by josdejong** [comment]
It would be great to get this to work, I agree with you that it's an important feature to be able to seamlessly expand math.js further.

From a technical point of view I like your approach most: 
- to specify a single index, you provide a number
- to specify a range in an index, you provide a Range object
- to specify a list with arbitrary indexes, you provide an Array or "Set" or other name

I like your idea of having `Index.dimension(dim)` return either a Range, or a "Set" (or other name), both offering a similar API, I agree with you that this is important to make usage simple. I also find it important to keep the number of different data types minimal (you know how the code can explode when you introduce three types of matrices ;) ). If I'm right, the only API of the Range that is used is `Range.map` and `Range.forEach`. So, instead of your proposal of a new type `Set`, would it work out to just use an instance of `Matrix` instead? The only thing we have to do in the `Index` constructor is validate whether the matrix is a one dimensional vector (i.e. `matrix.size().length === 1`).

This change of API of Index will be a nasty one: code written for the old API may still work but give wrong results. To help people migrate, maybe we should give a deprecation warning when an Index is created with an Array containing 2 or 3 values (and thus probably means a range with start, end, step). And you should be able to turn off this deprecation warning, maybe something like `math.config({deprecationWarnings: false})`.

As for the verbosity of specifying a range, like `A.subset(math.index(2, new math.type.Range(0, 10)));`, I was thinking, maybe we can support a little string notation for this like used in the expression parser, something like:
```js
// specify a range as a string 'start:end' or `start:step:end` 
// (zero based, end excluded)
A.subset(math.index(2, '0:10');

// also support 'end':
A.subset(math.index(2, '3:end');

// support select a whole column/row:
A.subset(math.index(2, ':');

// In practice you will mostly have variables to specify the ranges start and end, 
// then it will look like:
A.subset(math.index(2, start + ':' + end);
// a bit ugly but it works...

// a totally different idea is to support an object. Still verbose but very readable
A.subset(math.index(2, {start: start, end: end});
```

**Comment by rjbaucells** [comment]
I did not go with the Matrix because I wanted to make the `Set` immutable, the same as the `Range` and `Index`. Matrix provides operations that modified the data been stored (`set()`, `subset()`, `resize()`). I did not liked the idea of having an Index dimension changing after creation while the others are fixed (thing that I think is the way it should be).

I will work on implementing the syntax you proposed next week, still we need to decide if having a mutable Index dimension is correct or not.

Let me know what you think...

**Comment by josdejong** [comment]
Good point! 

How about creating an `ImmutableSparseMatrix` which extends `SparseMatrix`, and the same for `DenseMatrix`? These implementations should throw an error when methods are invoked that would mutate the data. Or maybe create a single type `ImmutableMatrix` which can point to an existing matrix (like a facade) so you don't have to copy everything from mutable to immutable matrix when creating an Index.

**Comment by rjbaucells** [comment]
A `SparseMatrix` cannot be used as an `Index` dimension since it is always a two dimensional matrix. An easier solution would be adding a `readonly` feature to matrices that will make the Matrix instance immutable when constructed with the parameter in true. Something like:

````
var m = new DenseMatrix(..., true);
m.set(...); // throws an exception
````

Additional changes are needed on function implementations since many of those functions make access to the internal data representations `matrix._data`. We will need to check if the function modifies the matrix data and in this case check for the readonly flag (`matrix.readonly()`) and throw an exception in this case.

**Comment by josdejong** [comment]
Ah ok, so `Index` would only have to support `DenseMatrix` then (and convert `SparseMatrix` input to `DenseMatrix`. That's no problem. 

I was thinking, wouldn't we have to copy the input Array or Matrix anyway? If the user mutates a matrix after which has been passed to `Index` before, the Index would change. Same with `Range` though. Also, I think in practice people will not pass a readonly version of a `DenseMatrix` to `Index`, so a copy action may be needed anyway?

Passing a `readonly` flag to a Matrix will certainly work, and it's a pragmatic solution. However it doesn't really feel like the right place to me to put the logic for being readonly in the original `DenseMatrix` implementation. Putting a readonly "wrapper" or "facade" around a regular matrix sounds cleaner to me. But that may be personal preference. 

So I guess we can summarize the decisions as:

1. What type is stored internally in `Index` (and is returned by `Index.dimension()`)? A `Matrix`, `Array`, or new data type like `Set` or `Vector`? 
  - I prefer not introducing a new data type here, and think it's better to return a `Matrix` rather than an `Array` as it has the same utility functions (`map`, `forEach` as `Range`).
2. Do we always copy input arguments of `Index` (both `DenseMatrix` and `Range`) ?
  - I'm afraid we have to, to prevent weird side effects here. 
3. Do we extend `DenseMatrix` with a `readonly` flag, or do we implement an `ImmutableMatrix` which points to a `DenseMatrix`?
  - I don't have a very strong opinion here but lean towards an `ImmutableMatrix`.

**Comment by rjbaucells** [comment]
Conversion from `SparseMatrix` to `DenseMatrix` is not needed. A `SparseMatrix` cannot represent a Vector; it can only store two dimensional matrices, so it cannot be used as an Index dimension.

Related to the points you made...

1. We can go with the `Matrix` as the Index dimension.
2. Cloning the dimensions will be required to avoid the Index changing over time.
3. We can create an `ImmutableMatrix`, do we want it as part of the visible API, I would say no, it is not needed. We can wrap the copy of the `Index` dimension with the `ImmutableMatrix` and return it as the result of the call `index.dimension()`. For the consuming code it is a regular `Matrix`, trying to modify the internal structure (invoking `set()`) will throw an exception.

I have not found the time to work on it yet, I will update the PR soon...

**Comment by josdejong** [comment]
Ah of course, SparseMatrices are not applicable at all...

About 3: As we have to copy the input Matrix anyway, we can copy to any type of new Matrix, like a new  `ImmutableMatrix`. That makes `ImmutableMatrix` even more straightforward than I had in mind before: it doesn't have to be some special sort of wrapper on top a Matrix, but it can just extend `DenseMatrix` and override the mutable functions.

Cool, sounds good. No need to hurry though!

**Comment by rjbaucells** [comment]
I made all the changes using an `ImmutableDenseMatrix` as an `Index` dimension but found an incompatibility between the `Matrix` and `Range` APIs:

`Matrix.forEach()` invokes the callback function with three parameters, the element value, the element index (**Array**) and the Matrix instance.

`Range.forEach()` invokes the callback function with three parameters, the element value, the element index (**number**) and the Range instance.

A similar problem exists in `map()`.

The only option I see is changing the `Range` API to invoke the callback function passing an array with the index value to make it compatible with the same operation in a `Matrix` instance. We cannot do the reverse since a `Matrix` can have more than one dimension.

What do you think?

**Comment by josdejong** [comment]
Ai! Good point. 

It feels a bit quite ugly to change the `Range.forEach` API for this. It's a bit odd to have an array with one value as index (and it will cost performance). On the other hand, it's very nice when the behavior of `Range` and `Matrix` would be consistent!
The only other option is to introduce a new data type like `Vector`, which has the same API for the method `forEach` as that of `Range.forEach` (and `Array.forEach`). But that may introduce other issues, like when `Vector` would extend `Matrix`, you would have a conflicting API for `forEach` so that's not possible. But this would be most logic from a user point of view.

I think your idea to change the API of `Range.forEach` to match `Matrix.forEach` is the best option. That gives us a consistent API for all matrix like data types, and avoids having to introduce new data types.

**Comment by rjbaucells** [comment]
I have finished the implementation of an `Index` dimension as a fix set of values. The `Index` dimension in this case is managed by an instance of a new type `ImmutableDenseMatrix`.

**Comment by josdejong** [comment]
Looks neat, thanks for all your work and this discussion!

So we still have to adjust the api of Range.forEach and `Range.map`.

**Comment by rjbaucells** [comment]
I completed the changes for the `Range` type. The callback function in both functions are called with the same syntax as in `Matrix`. It is part of the pull request you just merged.

**Comment by josdejong** [comment]
Ah sorry, you are right, I just overlooked it. Nice.

**Pull request merged**
