### PR TITLE
multiply() refactoring

### PR DESCRIPTION
**Pull request by rjbaucells**
- Moved `multiply()` out of Matrix types
- Improved performance of large Matrix x Matrix multiplication (Sparse)
- Added ability to import Matrix Market matrices into tests. See [The University of Florida Sparse Matrix Collection](http://www.cise.ufl.edu/research/sparse/matrices/) and [Matrix Market](http://math.nist.gov/MatrixMarket/). We should think about providing this functionality as an optional API call.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks! You're going full speed these days :)

**Comment by josdejong** [comment]
What is the matrixmarket.js under tools about?

**Comment by rjbaucells** [comment]
It is the code to import the Matrix Market files. I add it as a tool so it is not part of the API, it has dependencies that are not part of mathjs, so you need them for Dev only. See packages.json.

**Comment by josdejong** [comment]
Interesting, I didn't knew about Matrix Market, thanks!

**Pull request merged**
