### PR TITLE
fix(simplify): Leave string constants as strings.

### LINKED ISSUE #2152: Simplify function transform a string to number, which cause some problems.
Why simplify function transform a string to number? I don't want to change the typeof value, because it may cause some problems.

```javascript
math.simplify('f("0xffff")')
// args[0]: r {value: 123}

math.simplify('"1234"')
// {value: 1234}
```

### PR DESCRIPTION
**Pull request by gwhitney**
Note that because the `size` built-in function called on a string returns
  a Matrix, which is represented in math.js expressions as an Array, this
  commit has to add ArrayNode as a dependency of `simplify` (and hence
  also of `rationalize`).

  In addition, it requires changing the handling of ArrayNodes
  and AccessorNodes in `simplifyConstant` from "unimplemented" to just a
  pass-through (since a full implementation of simplification in Arrays and
  indexing seemed beyond the scope of this change, but `simplify` must not
  throw an error on `size("foo")`). Hence, this commit also adds skipped unit
  tests for some expressions with arrays and indexing that should ultimately
  simplify.

  It also removes the skip on the test group "should not change the value of
  numbers when converting to fractions (3)" since all of those tests already
  appear to pass.

  Resolves #2152.

  Changes the behavior in #1913 from throwing an error to allowing Arrays and
  indexes but not simplifying inside them.

[Note that I intend to and will be glad to fully address #1913 once this change (perhaps with revisions as requested, of course) is merged.]

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks a lot for picking this up Glen! The code looks good. I like that you already created (skipped) tests for the future support for simplifying inside matrices 😄 .

I think the code is ready to merge, though it may be neat to remove the comment "Originally the below was wrapped with _toNumber ..." from the code?

**Comment by josdejong** [comment]
Ah, I also see the linter is complaining. You can run `npm run lint -- --fix` to fix this (I'll add a script `npm run format` for this and document it in the readme, that is missing)

**Comment by gwhitney** [comment]
Sure, that comment was mostly by way of explaining the only change that might have greater repercussions. Have eliminated it and fixed the lint (sorry I didn't notice about `npm run lint` and/or do a better job of matching the repo's conventions on the first try. Hope it's all ok now.

**Comment by josdejong** [comment]
Thanks, that looks good 👍 

It's not your fault about the linting, it happens to me too regularly, you only notice afterwards then 😁

**Comment by josdejong** [comment]
Fix is published now in `v10.1.0`, thanks again Glen

**Pull request merged**
