### PR TITLE
BugFix3301: Precedence of % (mod) is higher than * and /

### PR DESCRIPTION
**Pull request by nkumawat34**
Added the BugFix of Issue #3301 

This PR addresses the problem where the precedence of the % (modulo) operator was incorrectly treated as having higher precedence than * and /. The fix ensures that % now has the same precedence as * and /, resolving the issue caused by the functional addition for % that led to incorrect operator precedence.

### CODE REVIEW

**Review by josdejong — CHANGES_REQUESTED** [review]
THanks @nkumawat34 , impressive! I thought this would be tricky to fix.

Two remarks:

1. Can you update the Precedence table: https://github.com/josdejong/mathjs/blob/develop/docs/expressions/syntax.md#precedence
2. Can you add more unit tests to check the precedence of `%` and `mod` vs the four other operators `*` `/` `.*` and `./`  ? (precedence should be equal now)

**Comment by nkumawat34** [comment]
Please check now I updated the PR

**Comment by josdejong** [comment]
Thanks, that's a thorough est of tests 😎 

One idea: how about changing the `parseAndEval` approach to the following:

```js
function parseAndStringify(expr) {
  return math.parse(expr).toString({parenthesis: 'all'})
}

// ...
assert.strictEqual(parseAndStringify('10 % 3 * 2'), '(10 % 3) * 2')
```

Then there is no need for the explanatory comments like `// Expected as (10 % 3) * 2 = 1 * 2 = 2`? We would lose checking the actual outcome though. What do you think? (I'm ok with both, it's just an idea)

**Comment by josdejong** [comment]
Thinking about it, we could do something like this:

```js
function assertParseAndEval(expr, expectedString, expectedResult) {
  const node = parse(expr)
  assert.strictEqual(node.toString({ parenthesis: 'all' }), expectedStr)
  approxEqual(node.evaluate(), expectedResult)
}

// ...

assertParseAndEval('10 % 3 * 2', '(10 % 3) * 2', 2)
```
😎

**Comment by nkumawat34** [comment]
should i remove comments

**Comment by josdejong** [comment]
I'm ok with any of the three options: leave as is, create and use assertParseAndEval, or use parseAndStringifyWithParens. I have a slight preference for using parseAndStringifyWithParens. What do you think?

**Comment by nkumawat34** [comment]
Ok I am going with this parseAndStringifyWithParens.I think it will be better.

**Comment by nkumawat34** [comment]
done

**Comment by josdejong** [comment]
Thanks for the quick updates 👌, merging your PR now in the `v14` branch.

**Comment by josdejong** [comment]
Published now in `v14.0.0`, thanks again Neeraj!

**Pull request merged**
