### PR TITLE
matrix*vector multiplication returns a vector (TS)

### PR DESCRIPTION
**Pull request by Windrill**
Saw a parsing error on IDE for a matrix multiplication with vector. Instead of a 2D matrix multiply returns a vector which is more succinct. The original typescript definition 
`
    multiply<T extends Matrix | MathArray>(x: T, y: MathType): T
`
did not cover the case when the second (vector) type prevails. Used an additional specific template specialization:
`
    multiply<T extends Matrix | MathArray>(x: T, y: MathNumericType[]): MathNumericType[]
`
Also considered MathCollection & Unit types, seems that returning a vector does not apply.

Saw the [dense] corresponding JS function that generates a vector around _multiplyVectorDenseMatrix in function/arithmetic/multiply.js starting from 'result' accumulation.

### CODE REVIEW

**Comment by Windrill** [comment]
Found out Matrix's influence is more generic than any other MathType -- any combination of T and Matrix will result in a Matrix instead of JS array if there is at least 1 being multiplied. Matrix * MathNumericType will coerce the actual result into a Matrix.

Here's the combinations of all the MathTypes I used for testing:
`

{
  let abc : MathArray = [1,2,3,4];
  let bcd : MathArray = [[1,2,3,4],
  [2,3,4,5],
  [4,5,6,7],
  [5,6,7,8]];

  let Mbcd = math.matrix(bcd);
  let Mabc = math.matrix(abc);

  // Number
  let r1 = math.multiply(1, 2);
  console.log(r1);

  // Unit
  const a = math.unit(45, 'cm') // 450 mm
  const b = math.unit(45, 'cm') // 450 mm
  let r2 = math.multiply(a, b);
  console.log(r2);

  // 1D JS Array
  let r3 = math.multiply(abc, bcd);
  console.log(r3);
  r3[1]; // By default least promised valid syntax

  // 2D JS Array
  let r12 = math.multiply(bcd, bcd);
  console.log(r12);
  // Ambiguity easily sorted
  const multiDimensional = (x: any): x is any[][] => x.length && x[0].length;
  if (multiDimensional(r12)) {
    r12[1][1];
  }
  r12[1]; // Valid syntax for certain

  // Matrix: matrix * vector
  let r7 = math.multiply(Mabc, bcd);
  console.log(r7);
  r7.toArray(); // Matrix-es have toArray function

  // Matrix
  let r8 = math.multiply(Mabc, 4);
  console.log(r8);

  // Matrix
  let r11 = math.multiply(4, Mabc);
  console.log(r11);

  // Matrix of units
  let r9 = math.multiply(Mabc, a);
  console.log(r9);
  let r10 = math.multiply(a, Mabc);
  console.log(r10);

  // Matrix
  let r6 = math.multiply(abc, Mbcd);
  console.log(r6);

  // 2D JS Array
  let r5 = math.multiply(bcd, abc);
  console.log(r5);

  // Number
  let r4 = math.multiply(abc, math.transpose(abc));
  console.log(r4);
}
`
With modified type annotations, all expressions on top become valid.

**Comment by josdejong** [comment]
Thanks @Windrill , looks good.

Can you add the tests you pasted above into the file `types/index.ts`? That will guarantee that the types work and keep working.

**Comment by Windrill** [comment]
Hi @josdejong, sure, added these to the commit.

**Comment by josdejong** [comment]
Thanks @Windrill , looks good! I see the linting fails due to the use of `any`, can you resolve that? 

(Run `npm run lint` to check)

**Comment by Windrill** [comment]
Hi @josdejong good catch from the workflow! Configured eslinting on the repository, hope the style is valid now...

**Comment by josdejong** [comment]
Thanks @Windrill , all is green now 👌

**Pull request merged**
