### PR TITLE
Added 3D to distance

### PR DESCRIPTION
**Pull request by kv-kunalvyas**

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @kv-kunalvyas , looks neat and well tested/documented.

I'm not happy with the required third parameter `f` though, where you have to specify if you have 2D or 3D points. I think that's really cumbersome in daily use. It's easy to detect the number of dimensions automatically from the input arrays. We could even generalize the function to accept 2D, 3D, and N-D data points, it's not hard algorithm wise :)

**Comment by kv-kunalvyas** [comment]
Though this would sacrifice adding non-array/matrix as parameters, I think this is still better than having 2/3 etc as a parameter. Will add commits soon with updated code.
Thanks!

**Comment by josdejong** [comment]
> Though this would sacrifice adding non-array/matrix as parameters

What cases do you have in mind exactly which will not be possible anymore? I think you can still use all sorts of input types, all we have to do is typecheck the input type and act accordingly.

**Comment by kv-kunalvyas** [comment]
With that, I meant a case when we pass numbers as parameters like `distance(2, 3, 1, 6)`, `distance(2, 6, 9, 2, 1, 3)` etc. instead of arrays. The problem comes when implementing **pdist**. For the case `distance(5, 3, 5, 6, 9, 2)`, there would be no way to differentiate between whether to calculate distance between two 3D points or pairwise distance between three 2D points.

**Comment by josdejong** [comment]
Ah, I get your point. Do you think we should support this syntax? I think we should not support this at all, as it's a bit an ambiguous syntax. What do you think?

btw we don't need to copycat `pdist` but we can use it for inspiration and to see what sort of syntax is commonly used.

**Comment by kv-kunalvyas** [comment]
I don't mind leaving out this syntax at all. Using only arrays/matrix would be the most simplified way to use the function.

**Comment by josdejong** [comment]
Agree, sounds good then, just supporting array/matrix inputs.

**Comment by kv-kunalvyas** [comment]
Please check the latest commit. The function looks complete now.

**Comment by josdejong** [comment]
Thanks for your work, that looks quite complete :)

A few remarks:

- For consistency, the function should output an Array when the input has Arrays, and should output a Matrix when the input was a Matrix. This is quite easy to achieve, see for example [function `dot`](https://github.com/josdejong/mathjs/blob/master/lib/function/matrix/dot.js) for inspiration
- It's not entirely clear to me how we can distinguish these two signatures:

  ```js
  math.distance([[A], [B], [C]...])
  math.distance([x1, y1], [LineX1, LineY1], [LineX2, LineY2])
  ```

- I'm not sure about the last three signatures:

  ```js
  math.distance([x1, y1], [LineX1, LineY1], [LineX2, LineY2])
  math.distance([x1, y1], [xCoeffLine, yCoeffLine, constant])
  math.distance([x1, y1, z1], [x0, y0, z0, a-tCoeff, b-tCoeff, c-tCoeff]) 
  ```

  Would it make sense here to pass the arguments as an Object instead of an Array? From usage of the function it's hard for the eye to see what is passed exactly and hence in what "mode" the function will evaluate. What do you think? @devanp92 do you have any thoughts on this?

**Comment by kv-kunalvyas** [comment]
Thanks for the remarks.

1. I'll add the cases for Matrix in the next commit once we finalize the changes to be made.

2. There is a slight difference; for pairwise distance calculation (for both 2D and 3D), the parameter has to be just one array of arrays, whereas for distance calculation of a point and line, it has to be three 2D arrays(the point that's not on the line and two points that are on the line).

3. I agree it is quite flustering for a person to get introduced to this syntax of inputs. However, can you tell me more about how will this be passed as objects and if it has this implemented, can you please cite an example of an existing math.js function?

**Comment by devanp92** [comment]
@josdejong I mentioned [here](https://github.com/josdejong/mathjs/issues/418):

> We could create types for a plane and point and then in the distance function, type check them, then pass them to the according function like so:
> distance(x, y) {
> // if x is a plane and y is a point - distanceBetweenPlaneAndPoint(x, y)
> // if x is point and y is point - distanceBetweenPoints(x,y)
>  ...

I agree that overloading the function multiple times is quite cumbersome. I think the best way is to either pass them in as objects:

    var point = {
        x: 1,
        y: 2
    }

OR as a Point/Plane object (which we would need to create). We could even create an interface for this object (called location or reference) which we implement in the Point and Plane objects. 

However, it is confusing to pass in any object the user creates and try to figure out if its a point or plane. The reason being, there are 3 ways (that I know of) to define a point or plane: Cartesian, Parametric, and Polar.

**Comment by josdejong** [comment]
@kv-kunalvyas about 3: the syntax could looks something like this, which is more verbose and less magic:

```js
math.distance([10, 10], {xCoeffLine: 8, yCoeffLine: 1, constant: 3})
```

@devanp92 thanks for your input. We could indeed create a few separate functions here, though I would really like to keep the amount of functions limited. Just thinking aloud: `distance`, `distanceLine`? But still, it may be just fine to have one function `distance` when the parameters are more clear by passing objects.

Indeed besides accepting points as an array like `[x, y]` and `[x, y, z]`, we could also support objects like `{x: 1, y: 2}` and `{x: 1, y: 2, z: 3}`.

I would rather not implement special types for planes and points but use regular arrays and objects instead. Use some simple ducktyping to check the type of the input.

**Comment by kv-kunalvyas** [comment]
In the latest commit, I've added the functionality for accepting objects. Examples of additional kinds of input supported are:
    
- `math.distance({pointOneX: 4, pointOneY: 5}, {pointTwoX: 2, pointTwoY: 7})`
- `math.distance({pointOneX: 4, pointOneY: 5, pointOneZ: 8}, {pointTwoX: 2, pointTwoY: 7, pointTwoZ: 9})`
- `math.distance({pointX: 1, pointY: 4}, {lineOnePtX: 6, lineOnePtY: 3}, {lineTwoPtX: 2, lineTwoPtY: 8})`
- `math.distance({pointX: 1, pointY: 4, pointZ: 7}, {lineOnePtX: 6, lineOnePtY: 3, lineOnePtZ: 4}, {lineTwoPtX: 2, lineTwoPtY: 8, lineTwoPtZ: 5})`
- `math.distance({pointX: 10, pointY: 10}, {xCoeffLine: 8, yCoeffLine: 1, constant: 3})`
- `math.distance({pointX: 2, pointY: 5, pointZ: 9}, {x0: 4, y0: 6, z0: 3, a: 4, b: 2, c: 0})`

I think this way of taking inputs is much better in addition to arrays, especially for cases like point to line in 3D where there are many input variables to work with. I've also added appropriate test cases that cover all additional major possibilities. If you can suggest better key names for any of these, let me know.

**Comment by kv-kunalvyas** [comment]
untitled
I don't understand why the travis build failed. It's in the `mode.test.js` file which I haven't edited in a long time. And `npm test` is running fine on my system.

**Comment by FSMaxB** [comment]
Maybe it's because Travis isn't testing you actual commit.

When testing pull requests, Travis does a merge first and then tests the merged state.

**Comment by FSMaxB** [comment]
Now I found out how to reproduce this locally. When you delete your `node_modules` directory and reinstall all the dependencies, suddenly the test fails.

This even fails on master!

I created a separate issue: #477

**Comment by josdejong** [comment]
Thanks @kv-kunalvyas , your PR looks good. And sorry for the delays caused by this issue with `typed-function` (which is fixed now).

**Comment by kv-kunalvyas** [comment]
@josdejong and @devanp92 thanks for the help with this and also for your patience. I'm always glad to contribute!

**Pull request merged**
