### PR TITLE
Implemented iterative eigenvalue finder for eigs

### LINKED ISSUE #2179: Implement iterative eigenvalue finder for eigs
The current implementation of `eigs` relies on `usolveAll` to find eigenvectors. This often fails because of numerical errors. A more robust approach would be to use an _iterative_ algorithm. The easiest one in this case would be the [inverse iteration](https://en.wikipedia.org/wiki/Inverse_iteration) algorithm. The gist of the algorithm is this:
1. Take a random vector _b_.
2. Let _A_ be a matrix and _k_ an approximation of its eigenvalue.
3. The expression _( (A − kE)⁻¹ )ⁿ b_ converges to an eigenvector as _n → ∞_.
4. Instead of actual inversion, which is a costly operation, we can perform an implicit inversion using `usolve` _bₖ = (A − kE) bₖ₊₁_.

The relevant code is [here](https://github.com/m93a/mathjs/blob/patch-eigens/src/function/matrix/eigs/complex.js#L418).

### PR DESCRIPTION
**Pull request by m93a**
Fixes #2179. There are no changes in the API.

### CODE REVIEW

**Comment by m93a** [comment]
@josdejong I've merged my first PR! Did I do it right? 😁️

**Comment by josdejong** [comment]
Really nice that you managed to implement this @m93a ! 

So with this solution, `eigs` is much more often able to find a solution, right?


> @josdejong I've merged my first PR! Did I do it right? 😁️

yes good busy 😄 . Generally, I think it will be good to review each others work before merging it, to ensure high quality and consistency etc, shall we do that next time?

**Comment by m93a** [comment]
> Generally, I think it will be good to review each others work before merging it, to ensure high quality and consistency etc, shall we do that next time?

Sounds good to me! 👌

**Comment by josdejong** [comment]
Published now in `v9.4.2`, thanks again!

**Pull request merged**
