### PR TITLE
Fixed ui issue with table on Function typeof detail page of mathjs website

### PR DESCRIPTION
**Pull request by adityasharma7**
Added css for table and td/th to make it fixed inside its container

Check following URL for the issue:
http://mathjs.org/docs/reference/functions/typeof.html

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for the fix Aditya, appreciated!

**Comment by josdejong** [comment]
hm, I see now that this gives the tables under parameters and and return types a different styling too, which looks less clear now:

image

I've added some zero width white spaces to the contents of this table, and reverted the 100% table width again, how do you like the result? http://mathjs.org/docs/reference/functions/typeof.html

**Comment by adityasharma7** [comment]
>  hm, I see now that this gives the tables under parameters and and return types a different styling too, which looks less clear now:

Indeed I missed on that

>  I've added some zero width white spaces to the contents of this table, and reverted the 100% table width again, how do you like the result? http://mathjs.org/docs/reference/functions/typeof.html

Looks like a more promising solution :+1: 
Thanks @josdejong :smile:

**Comment by josdejong** [comment]
:+1:

**Pull request merged**
