### PR TITLE
Fix #2412: let function diff return an empty matrix when the input contains only one element

### LINKED ISSUE #2412: Edge case: `diff([1])`
Currently, `math.evaluate('diff([1])')` returns `[1]`. It seems to me that to be consistent with `diff()` called on any array of length > 1 (where it returns an array of length one less than the input), the value of `diff([x])` ought to be `[]` no matter what x is. In other words , there are _no_ consecutive differences of a list of length 1. (`diff([])` would continue to produce `[]` as it currently does; there are also no consecutive differences of a list of length 0.)

If there's agreement that the current behavior is anomalous and should be corrected, I will be happy to supply the small PR needed to fix.

Incidentally, it seems to me that issue #1634 asking for diff in the first place can be closed.

### PR DESCRIPTION
**Pull request by josdejong**
See #2412

### CODE REVIEW

**Comment by gwhitney** [comment]
@josdejong did you want me to review/merge this, or will you merge it yourself?

**Comment by josdejong** [comment]
@gwhitney thanks, Yeah, I lost sight of this PR. It would be nice if you can have a short look if it makes sense to you, it's a very small PR.

**Comment by gwhitney** [comment]
Looks good to me, nice and simple. Added some 2-D tests. The only reason I didn't go ahead and merge this is I am not 100% clear on the definition of a "breaking change". This PR changes a prior, _tested_ outcome of a mathjs function. So does that mean it is a breaking change, and so should be slated for v11 rather than merged into develop now? As far as I am concerned, feel free to go ahead with either as appropriate, or let me know which one and I will do it.

**Comment by josdejong** [comment]
Will merge this into `v11`, better safe then sorry :)

**Pull request merged**
