### PR TITLE
Fixing argument check in randomInt

### PR DESCRIPTION
**Pull request by devanp92**
Fixing case with no arguments referenced [here](https://github.com/josdejong/mathjs/issues/381).

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks! Could you maybe also add a unit test for this to prevent future regressions?

**Comment by devanp92** [comment]
Looking at the documentation, randomInt() returns an integer between 0 and 1. However, if the bound of randomInt() is [min, max), then wouldn't it always return 0?

**Comment by josdejong** [comment]
Ah, you're right. Ok then let's remove the `randomInt()` signature then. Can you update your PR accordingly?

**Comment by devanp92** [comment]
I need to reverse the commits for distribution.js and distribution.test.js (since it was correct the first way), but the documentation needs to updated.

**Comment by devanp92** [comment]
This PR can be closed.

**Comment by josdejong** [comment]
Yes exactly, only an update in the docs is needed then. If you want I can do it too. 

Thanks!

**Comment by josdejong** [comment]
I've updated the docs on `randomInt`

**Pull request closed without merging**
