### PR TITLE
Improve type definitions of function `hypot`

### PR DESCRIPTION
**Pull request by Hudsxn**
Addressed silentmissile's comment in:
https://github.com/josdejong/mathjs/issues/3125

### CODE REVIEW

**Comment by Hudsxn** [comment]
Yeah sure, i'll go through and add that now :)

**Comment by Hudsxn** [comment]
That's been addressed now buddy. :)

**Comment by josdejong** [comment]
Thanks, looks good 👌

**Comment by josdejong** [comment]
Your fix is published now in `v12.3.1`, thanks again.

**Comment by Hudsxn** [comment]
Not a problem bud! Happy to help :)

**Pull request merged**
