### PR TITLE
Updated copyright year dynamically.

### PR DESCRIPTION
**Pull request by Koshux**
Updated the copyright year to be dynamic instead of requiring a PR each time.

### CODE REVIEW

**Comment by josdejong** [comment]
That is a nice one indeed.

I like to automate that, but I think it would be better to insert the right year during a build step, not at runtime. What do you think?

**Comment by josdejong** [comment]
Closing this PR now, please create a new one if you manage to get the year generated during a build step

**Comment by Koshux** [comment]
Apologies, I did not realise you had replied. Let me look into the configured build steps and revert back to you. On the top of my mind however, I personally do not see any advantages over moving it to the build steps.

**Comment by josdejong** [comment]
Thanks!

> On the top of my mind however, I personally do not see any advantages over moving it to the build steps since the year would automatically update whenever the page loads rather than whenever a release is pushed.

In general I think it is best to do as much pre-processing as possible: serving plain HTML is more robust and faster than requiring JS for it. It can for example be helpful for Search Engine Optimization (SEO) if the page is directly readable. It's for a reason that there is a big interest now in techniques like server side rendering, and solutions like AstroJS.

**Comment by Koshux** [comment]
Most definitely however I came across some content recently that Google actually allows JS to be executed due to the larger demand for frameworks. Whilst SSR is still largely better for SEO, SEO in itself is based on search engine techniques specific to the company. Google recently announced that changes will be coming to SEO because of LLM and dependency on dynamic content. 

https://searchengineland.com/google-to-cut-thousands-of-search-quality-rater-jobs-after-dropping-contract-with-appen-436739

So yes I agree but also we have to keep in mind that some JS is still fine to keep if it serves better. Not in this case particularly but generally speaking :)

**Comment by josdejong** [comment]
Yeah true. Still, I like prefer simple static content when possible, keep it simple :).

I had a look to see if we can fill in the date when generating the site ([see StackOverflow](https://stackoverflow.com/questions/59336890/automatically-set-date-in-the-front-matter-of-a-jekyll-page)), and this is possible 🎉, see commit https://github.com/josdejong/mathjs/commit/f4bb24d1f45c7af2baaa76857f0ce6bc0a5fe99e. So the year is now automatically kept up to date.

Thanks for triggering this issue and thinking along!

**Pull request closed without merging**
