### PR TITLE
Improved readability of combinations.js by explicitly writing out two loops

### PR DESCRIPTION
**Pull request by waseemyusuf**

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, that looks good @waseemyusuf .

The long list with commits is indeed not normal. Can it be that your branch `waseemyusuf:develop` is not up to date with the latest `josdejong:develop`? Maybe you have to pull the latest version of `josdejong:develop`?

**Comment by harrysarson** [comment]
I clicked a button (I did not realise that it would make that commit for me).

However, I do not think the long list of commits is a problem as we can squash them when we merge. :+1:

**Comment by josdejong** [comment]
@waseemyusuf the PR itself is ready to merge, but it would be nice if you first try to solve the long commits list?

**Comment by waseemyusuf** [comment]
It seems that after forking the repo it is important to create a new branch for my edits instead of editing the default branch right away. For now, just to prevent unrelated old commits to appear, I:
1. did a hard reset to the commit just before my first commit to the project
2. pulled all new updates including my own past contributions from upstream
3. finally added the required new commit by `cherry-pick`.

But from next time I'll make sure to make pull requests from a new branch which will be for contributions only.

**Comment by josdejong** [comment]
I don't fully understand it, I'm no git expert, but this looks better Waseem :+1: 

Thanks for the PR!

**Pull request merged**
