### PR TITLE
Introduce browser tests using karma.

### LINKED ISSUE #987: Drop support for node.js 0.10 and 0.12?
Currently we have integration tests running on node.js 0.10, 0.12, 4, 6, and 8. To keep stuff compatible with node.js 0.10 and 0.12, we can't update all dev dependencies (like mocha, webpack), which isn't a good thing. 

I think it is time to drop support for node.js 0.10 and 0.12. mathjs will likely keep working on these node.js versions, but it's impossible to keep the develop environment running on these ancient versions of node.js. Ideally, we should set up an integration environment where we test the production version of mathjs on the latest versions of all browsers and node.js. Anyone interested in looking into that? (we can probably use BrowserStack for free since mathjs is an open source project).

Does anyone have concerns/objections in dropping support for node.js 0.10 and 0.12?

### PR DESCRIPTION
**Pull request by harrysarson**
This pull request uses karma to run mathjs's test in a headless firefox browser and additionally runs these browser tests as part of the travis CI.

#### Notes: 

- Adding chrome tests should be easy as travis has a plugin for them.
- Testing on IE might be harder - I haven't looked into it.
- Note that this PR includes commits from #1093.
- The reason for the hacky `browser-test/browser-tests.test.js` file is that having webpack bundle each test file separately caused node to run out of memory. 
  - See https://github.com/webpack-contrib/karma-webpack#alternative-usage.
  - Ideas of better places to put this file are very welcome.
- Only one test broke when running in firefox and that was due to the formatting of the error message. This test failure is fixed in 2b56dea.
- We may want to squash these commits.

---

closes #987

### CODE REVIEW

**Comment by josdejong** [comment]
Awesome, I'm really glad that you're working on setting up browser testing!

The PR looks fine. One small remark: can you use exact versioning in package.json? ie. `"karma": "2.0.2"` instead of "karma": "^2.0.2"?

We (as mathjs) do have free access to https://www.browserstack.com/#, which we can use to do automated testing on different browser types and versions. @ericman314 already did a bit of experimentation. @harrysarson shall I give you access too so you can see whether you can get the headless browser tests running there?

**Comment by harrysarson** [comment]
> The PR looks fine. One small remark: can you use exact versioning in package.json? ie. "karma": "2.0.2" instead of "karma": "^2.0.2"?
wha
Yep, of course. I will fix that.

> @harrysarson shall I give you access too so you can see whether you can get the headless browser tests running there?

Oo yes please, I can see what can be done.

**Comment by josdejong** [comment]
@harrysarson thanks for fixing the dev dependencies. Let's merge this PR as soon as we've merged #1093.

I've added you to the mathjs team on https://www.browserstack.com, there should be an invitation in your mailbox. Have fun :sunglasses:

**Comment by harrysarson** [comment]
This closes #987

**Comment by josdejong** [comment]
Merging now :)

**Comment by harrysarson** [comment]
CI failed it seems?

**Comment by josdejong** [comment]
ah, indeed: https://travis-ci.org/josdejong/mathjs/builds/377384431?utm_source=github_status&utm_medium=notification

I think it's because I deleted the `karma` branch before all tests on CircleCI where finished: one was in a waiting queue for a long time whilst the `develop` branch was already successful. So it's no problem, the ` develop` branch is ok.

**Comment by harrysarson** [comment]
Phew :)

**Pull request merged**
