### PR TITLE
Sinh Accuracy

### PR DESCRIPTION
**Pull request by cukejianya**
First commit to an open source ever. Whoohoo. Anyways, for sinh(x) where  -1 < x < 1, I used the 17th taylor series to calculate sinh.

( For sinh(.99999), I got 1.175185762896213 )

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for your contribution @cukejianya , and sorry for the late reply.

A few remarks:

- for the *number* implementation of `sinh`, we should not use *BigNumbers* under the hood.
- it's probably easier readable to write the taylor series as a simple for loop in a single function rather than  your solution of recursing over two functions `taylorExpansion` and `SummationFunc`, these functions spread the logic in a hard to read way.
- you've updated two unit tests testing sinh with units. I think it will be a good idea to also test it for numbers in the range of -1 to 1, as this is what we want to fix right now. Add a few unit tests for say `sinh(-0.7)`, `sinh(-0.3)`, `sinh(0.3)`, `sinh(0.7)`. You can validate the correct output by comparing against for example [Mathematica](http://www.wolframalpha.com/), Matlab, or other trusted/proven math applications. 

It's probably the easiest solution to just take the implementation of the GNU Scientific Library as @jrus [pointed out](https://github.com/josdejong/mathjs/issues/484#issue-112127827). This looks like a fast solution and is battle tested (of course we should unit test it ourselves too). What do you think?

**Comment by jrus** [comment]
Since Javascript is not a compiled language, I would recommend precomputing those divisions and putting the resulting constants directly in the code. e.g.

```javascript
var a0 = 1.666666666666667e-01; // 1 / 6
var a1 = 8.333333333333333e-03; // 1 / 120
var a2 = 1.984126984126984e-04; // 1 / 5040
var a3 = 2.755731922398589e-06; // 1 / 362880
var a4 = 2.505210838544172e-08; // 1 / 39916800
var a5 = 1.605904383682161e-10; // 1 / 6227020800
var a6 = 7.647163731819816e-13; // 1 / 1307674368000
var a7 = 2.811457254345521e-15; // 1 / 355687428096000
```

**Comment by jrus** [comment]
One more thing, I suspect there will still be an accuracy problem when evaluating complex sin, sinh, etc.

You might try testing various values and checking them against a reliable implementation.

You might again look to the GNU Scientific Library implementation for ideas about how to accurately implement complex sin / sinh for values near the origin.

**Comment by josdejong** [comment]
@cukejianya are you still interested in this PR or shall we close it? If not, @jrus, would you be interested to put your implementation in a PR (and add unit tests)?

**Comment by cukejianya** [comment]
@josdejong I dont mind.

**Comment by jrus** [comment]
That one looks fine now, though the alignment is slightly funky. I’d also put a comment in, along the lines of what I suggested above:
```
    // For |x| < 1, evaluate a degree 17 Taylor expansion of sinh using Horner’s rule.
```

**Comment by josdejong** [comment]
> I’m too lazy to fork the repo and make pull requests. :-)

thanks for your input, we'll improve the function.

**Comment by cukejianya** [comment]
@jrus @josdejong Is there anything else I need to do for this? I know @infusion is currently integrating complexjs. Should we wait till he is done before working on complex sin / sinh?

**Comment by josdejong** [comment]
@cukejianya well, @jus presented us a ready made solution which just needs to be implemented and unit tested. Since you let us know that you will not finish this, it simply waits until me or someone else has time to pick it up. This can safely be implemented in conjunction with other work.

**Comment by infusion** [comment]
Spent not too much time on reading the GSL implementation, but as far as I can tell the arithmetic looks similar to how I implemented complex sin and sinh. They don't have special code for `abs(x) < 1`, but maybe they rely on a more accurate real sinh implementation. It would be great if you could test either the dev branch of math.js or directly complex.js. If it doesn't have the accuracy you strive for, we should think of removing Math.sinh again and replace it with a more precise implementation like presented here, using a tailor approximation.

**Comment by cukejianya** [comment]
@josdejong @infusion I would love to continue working on this if possible.

**Comment by josdejong** [comment]
@cukejianya that would be great, thanks.

**Comment by cukejianya** [comment]
I think Math.sinh is accurate enough and maybe even more accurate than the GSL implementation. For Math.sinh(0.99999999999), I got 1.1752011936283706 which aligns with the answer in wolframalpha: http://www.wolframalpha.com/input/?i=sinh(.99999999999).

**Comment by cukejianya** [comment]
@infusion @josdejong @jrus

**Comment by josdejong** [comment]
try other values between -1 and 1, you will see :D

**Comment by cukejianya** [comment]
So I tried ±0.7, ±0.5, ±0.3 and the new built-in es6 function Math.sinh was spot on. It also looks like its supported in all major platforms except for IE11, Safari 7, and iOS 7. https://kangax.github.io/compat-table/es6/#test-Math_methods_Math.sinh

**Comment by josdejong** [comment]
Yes, we can use the native `Math.sinh` and when it doesn't exist provide a polyfill as provided by Jacob here: https://github.com/josdejong/mathjs/pull/555#issuecomment-177737978

**Comment by cukejianya** [comment]
First, I want to apologize for all those failed tests. It seems for node versions 0.12, Math.sinh is not as accurate as I initially thought. I guess they fix their accuracy in later versions. The question now is 1) do we withhold from using Math.sinh for now and just use the GSL implementation, 2) should we continue using Math.sinh and find away to check Math.sinh accuracy and if it meets a certain standard use it, 3) or do we not test for the accuracy that I am checking for in sinh.test.js

**Comment by josdejong** [comment]
I think we should use `math.sinh` though as it's the right "long term" solution. We've seen some numerical inaccuracies in node v0.12 before. To deal with this in unit tests you can do two things:
- find some inputs which do not result in a round-off error in node v0.12 (maybe 0.5 gives this problem, but 0.6 not).
- see whether the result is approximately equal rather than exactly equal, like compare up to 14 digits instead of the whole number.

**Comment by infusion** [comment]
I totally agree with Jos. I think most users (where user really means use and not just endure) already work on a machine, which supports `Math.sinh`, either on mobile or Firefox, Chrome, or even some useful IE of the younger generation. So it's not even a bet on the future, we already have it.

**Comment by josdejong** [comment]
I've fixed this in the `develop` branch by using ES6 Math functions when available, and if not, falling back on a simple implementation using `exp` (nothing fancy). This means that in practice you may see some inaccuracy issues on old versions of node (v0.10, v0.12).

**Comment by josdejong** [comment]
I think we could have closed this PR long time ago already, I will close it now.

**Pull request closed without merging**
