### PR TITLE
Escape string in toTex

### PR DESCRIPTION
**Pull request by FSMaxB**
See #995 

Still waiting for a new release of escape-latex and a bugfix (that's why the tests are failing).

### CODE REVIEW

**Comment by josdejong** [comment]
:+1:

**Comment by FSMaxB** [comment]
Now we just have to wait for the next release of escape-latex.

Is it ok that I am committing `package-lock.json` here?

**Comment by josdejong** [comment]
> Is it ok that I am committing package-lock.json here?

yes I think so, it could possibly give a conflict if the develop branch has updates in dependencies too but shouldn't be a problem.

**Comment by FSMaxB** [comment]
This is now ready to be merged.

**Comment by josdejong** [comment]
Awesome :)

**Pull request merged**
