### PR TITLE
Update README.md git clone link

### PR DESCRIPTION
**Pull request by Kartik199**
Updating the git clone link to adhere to github security update.https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, good point. Is there a specific reason that you changed it to https and not ssh? I would think ssh would be best (so that would be `git@github.com:josdejong/mathjs.git`)?

**Comment by Kartik199** [comment]
Sorry, my bad. ssh would be more secure than https. I have modified and the same.

**Comment by josdejong** [comment]
I'm not sure whether https is more or less secure than ssh, but when using https with git repos and you want to push something you have to enter your credentials each and every time which is not really workable 😁 

Thanks for the update!

**Comment by Kartik199** [comment]
Both https and ssh seems to be secure though. But https is easier to use than ssh for the uninitiated. ssh uses public key authentication and key-value has to be generated.https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.

**Comment by josdejong** [comment]
Yes true, https is easier in that regard. I expect though that most people cloning the project are developers that already use git for other projects too, I think it is a good default.

**Pull request merged**
