### PR TITLE
Fix Decimal prototype pollution

### LINKED ISSUE #2222: mathjs polluting Decimal prototype
For some reason I need to use Decimal.js and mathjs at the same time in project. However mathjs pollutes the decimal prototype with its own toJSON function, this produces undesirable effects in serialization:

minimal code to reproduce
```
const Decimal = require('decimal.js')
const mathjs = require('mathjs')

const dec = new Decimal(0)
console.log(JSON.stringify(dec))
```
expected output
```
"0"
```

actual output
```
{"mathjs":"BigNumber","value":"0"}
```

Is there a way for creating the bignumber using decimal.js without polluting its prototype?

### PR DESCRIPTION
**Pull request by m93a**
I made BigNumber **not** polute the `Decimal.prototype`, which fixes #2222. I had to modify tests and internals that unknowingly relied on the prototype pollution.

Right now the PR is ~~not~~ ready for merge, as there's an upstream bug that needs to be fixed first, see [#180 on decimal.js](https://github.com/MikeMcl/decimal.js/pull/180).

**EDIT**: The PR is ready to merge now.

### CODE REVIEW

**Comment by josdejong** [comment]
This solution makes a lot of sense, thanks @m93a  👍 

Will the extra logic in `isBigNumber` be needed in the end? The simpler and faster this function is, the better.

**Comment by m93a** [comment]
The extra logic in `isBigNumber` makes sure that Decimal, as imported from `decimal.js`, still works with math.js. In previous versions it worked because we polluted the prototype of `Decimal` with `isBigNumber`, now we need to check for it properly.

I think it would be a pity (and a breaking change) to remove the interop with `decimal.js`. Furthermore, it would probably cause a lot of confusion, because types like Complex and Fraction work well when imported from their respective libraries.

**Comment by josdejong** [comment]
Thanks for the clarification. If it's needed it's needed, I agree that it's preferrable to have Decimal working in all these cases.

**Comment by m93a** [comment]
Decimal.js has been updated, now the PR works!
(Actually, one test failed because of a timeout. I don't know if that's a real issue.)

**Comment by josdejong** [comment]
Nice!!

I've run the unit tests again but it's again exceeding the 2000 ms timeout. Some of the unit tests change the timeout to 10000 ms because of this, it would be nice if we could change the mocha timeout to 10000 by default to prevent these issues.

I think we can merge this PR, right?

**Comment by josdejong** [comment]
I've now defined a global timeout of 10 seconds for all mocha tests, see https://github.com/josdejong/mathjs/commit/4d841e4572fc662504f85d801cc437722ede3559

**Comment by m93a** [comment]
Before merging, take a look at `isBigNumber`, which I had to change again in order for it to work in Node 12. If you think it's ok, this PR is ready to be merged, yes :)

**Comment by josdejong** [comment]
Ah, I see you added two `try/catch` clauses in `isBigNumber`. What is the reason for that? Normally `try/catch` is terrible for performance, so I would like to avoid that if possible. 

To make it robust, I guess we can instead check existence for every needed property, like:

```js
if (x && x.isBigNumber === true && x.constructor && x.constructor.prototype && x.constructor.prototype.isBigNumber === true) {
  return true
}
```

or maybe we can use the new optional chaining syntax (not sure):

```js
if (x?.isBigNumber === true && x?.constructor?.prototype?.isBigNumber === true) {
  return true
}
```

**Comment by m93a** [comment]
Initially, I **did use** optional chaining, but it's not supported by Node 12, so I had to remove it. I thought that using `try/catch` would be a good alternative to make the code concise and readable, but you're right, it's is bad for performance and this piece of code is performance-critical. I've changed it once again, this time it should be ready to merge.

**Comment by josdejong** [comment]
Thanks!

I would think that Babel would transpile optional chainging 😕 . anyway, looks good 👍

**Comment by m93a** [comment]
The tests are run on the source code, therefore Babel won't help with that. Maybe, I could investigate if it's possible to make the CI tests to run on the compiled version...

**Comment by josdejong** [comment]
Ah, of course. To speed up, we removed compiling the tests, which is great. But indeed the down side is that we can't run like that on older versions of node.js. To enable this, you can run mocha like `mocha --require babel-core/register`.

**Comment by josdejong** [comment]
Fix is published now in `v9.4.3`, thanks again @m93a

**Comment by ifeelfishy** [comment]
Thak you guys for the prompt solution!

**Pull request merged**
