### PR TITLE
Improve API documentation V2

### PR DESCRIPTION
**Pull request by hgupta9**
I have improved https://github.com/josdejong/mathjs/pull/585 as per Jos, and here is the [hopefully] final version. I had to delete my fork, re-fork the `develop` branch, re-diff my changes into them file by file, all the while carefully retaining the code improvements in `develop`. Links from the Classes page also fixed.

**The following improvements have been made:**
- Certain classes annotated with JSDoc compatible tags
- JSDoc2Md used to generate documentation markdown files for Unit, DenseMatrix, SparseMatrix, Index, Range, ResultSet and FibonacciHeap
- List of classes created with links to the JSDoc generated files (`class_api.md`), and is currently the only way to access the JSDoc-generated files
- `densematrix.md` and `sparsematrix.md` have their constructor sections removed since the new operator is not the correct way to create those objects (I checked the constructors for all the other types and they look fine)
- Following units have been added : `acre, hectare, torr, bar, mmHg, mmH2O, cmH2O`

**The following changes have been made:**
- API for Complex numbers moved into a new section "API" on the same page
- API for Units moved into a new section "API" on the same page
- Unit reference moved into the `units.md` file

Please tell me if this is fine, and if any changes are required before it gets merged. Thanks.

### CODE REVIEW

**Comment by hgupta9** [comment]
Oh great the tests failed again. I'll have to test it locally first.

**Comment by josdejong** [comment]
Thanks. 

I think it would make things easier to split your PR in two like I suggested before (https://github.com/josdejong/mathjs/pull/585#issuecomment-190087979): one with updated documentation, and one with the new units. The PR with the docs (the largest) should not lead to failing unit tests since it's only updating text, that makes it easier to pinpoint the issue which has something to do with the new units.

**Comment by hgupta9** [comment]
Yes. I'm testing locally and it does not seem to be the units stuff. Even when I revert all changes a certain matrix test fails.

**Comment by josdejong** [comment]
So you mean a fresh clone of the develop branch also gives a failing unit test on your computer?

**Comment by hgupta9** [comment]
I'm just checking that. One sec.

**Comment by hgupta9** [comment]
Okay so I've run `npm install` & `npm test` on a fresh clone of `develop`, all tests are passing. Must be something I did.

**Comment by josdejong** [comment]
ok, one step at a time then :)

I noticed you'e using tabs instead of spaces, can you change that too?

**Comment by hgupta9** [comment]
Sorry for the stupid question (new to testing with mocha) but do I have to `npm install` everytime I want to `npm test`?

**Comment by josdejong** [comment]
No you have to do `npm install` only once. See docs on testing: https://github.com/josdejong/mathjs#test

**Comment by hgupta9** [comment]
Oh amazing, all tests are passing, new units and all. It was just a ONE LINE bug in DenseMatrix.js. Duh!

**Comment by josdejong** [comment]
ok great :)

**Pull request closed without merging**
