### PR TITLE
Fix #2528: improve explanation in CONTRIBUTING.md

### LINKED ISSUE #2528: Contribution guideline
Current guidelines seem to provide information about the standard and some requirements without much detail. It would be helpful to have some more detail, e.g., what has to be done when implementing new functions, what has to be done when changing the existing function, where are the tests, etc.

This should reduce many repetitive comments in the PRs, issues (e.g., #2487), and so on.

This might be related to #2472.

### PR DESCRIPTION
**Pull request by josdejong**
See #2528

### CODE REVIEW

**Comment by josdejong** [comment]
@HanchaiN can you have a look at this improved CONTRIBUTING.md?

**Comment by josdejong** [comment]
Thinking about it, maybe it is better to keep `CONTRIBUTING.md` concise, and put the extensive documentation in `README.md`  instead. Then we can link from `CONTRIBUTING.md` to these sections in `README.md`. What do you think?

**Comment by HanchaiN** [comment]
I think that the description is clear enough for new contributors (else they will raise the issue again sometime).
Whether or not the documentation is seperated depends on you. As long as they can reach the infomation from where they might look for them, that's fine.

**Comment by gwhitney** [comment]
For what it's worth, the new CONTRIBUTING in this PR seems clear enough but not too long. I would recommend (as part of this PR) mentioning the CONTRIBUTING guide in the README, though -- not all potential contributors look at the whole file tree (speaking from experience), but I think it's pretty common to at least read the README.

**Comment by josdejong** [comment]
I've moved the explanation on implementing a new function to the README, and add a small FAQ section to CONTRIBUTING.md linking to this section to keep it short. 

I'll merge this PR now, thanks for the feedback.

**Pull request merged**
