### PR TITLE
Reexport Fraction types from fraction.js instead of using custom one

### PR DESCRIPTION
**Pull request by fchu**
This should fix https://github.com/josdejong/mathjs/issues/3317
FYI `npm test` passed but got issues with `npm run test:types` (prior to this PR that is), so an approver might want to double check

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Francois!

I was just thinking: maybe we should just remove exporting the type definition of `Fraction`, and let TypeScript pick the type defintions from the Fraction.js library itself. If we export `Fraction` from mathjs, as an end user, you can import Fraction from two different sources: mathjs or Fraction.js. That is a duplicate. What do you think?

**Comment by fchu** [comment]
I'm not an expert so I won't be able to give you the most informed answer.
I would think that if you remove the definition, the user will still have to import it from _somewhere_, which will either be their own direct import of fraction.js (which can be a different version), or have to find the exact version your package is depending on, which is an hassle. Maybe re-exporting it is just the user-friendly way to have access to the correct version of the type?

**Comment by josdejong** [comment]
Hm, yeah. If we change that we should be consistent and not export the type definition of `Fraction` nor `BigNumber`. Ok let's leave the export in then 👍.

**Review by josdejong — APPROVED** [review]

**Comment by josdejong** [comment]
Published now in `v14.0.1`, thanks again.

**Pull request merged**
