### PR TITLE
Speed up reshaping function of a matrix

### PR DESCRIPTION
**Pull request by honeybar**
So I notice that in this comment [here](https://github.com/josdejong/mathjs/issues/1148#issuecomment-404037975), reshape is terribly slow compared to transpose. The issues lies mainly with how slow the recursion is, and thus, a friend of mine rewrites the reshape function iteratively instead, and the speed boost is immense. 

Here is the log of performance for the transpose of var a = math.ones(1, 100000) :
Call to algorithm for transpose took 67.26909599999993 milliseconds. 
Call to old algorithm for reshape took 6013.208004 milliseconds.
Call to new algorithm for reshape took 117.086568 milliseconds.

Here is the log of performance for reshape for converting 1 x 10000 to 1000 x 100 shape:
Call to old algorithm for power took 7273.37094 milliseconds.
Call to new algorithm for reshape took 120.73325700000004 milliseconds.

### CODE REVIEW

**Comment by josdejong** [comment]
wow!! That's impressive, a really nice improvement.

@honeybar I've updated the history with this improvement and attribution (see https://github.com/josdejong/mathjs/commit/e82de940c4687e8f8628e646bb0b3fd48a854907), but I don't know your friends name, can you share this name? (unless he wants to stay anonymous)

**Comment by honeybar** [comment]
Hi, he did said he rather keep himself anonymous so yeah, that is kind of unfortunate 😅

**Comment by josdejong** [comment]
That's fine with me. I really appreciate his improvements so please thank him. I find attribution important that's why I ask.

**Comment by honeybar** [comment]
will do. I am pretty sure he will be happy to hear it 😄

**Comment by josdejong** [comment]
The fast `reshape` function is now available in `v5.0.4`

**Pull request merged**
