### PR TITLE
Fixed #851: More consistent behavior of sqrt, nthRoot, and pow

### LINKED ISSUE #851: More consistent behavior of sqrt, nthRoot, and pow
Try:
```
a = nthRoot(i,3)

[{"r": 1, "phi": 0.5235987755983}, {"r": 1, "phi": 2.6179938779915}, {"r": 1, "phi": 4.7123889803847}]
```

The function returns array containing these objects instead of Complex numbers.

Also: for negative real radicands the degree of the root (currently) must be odd, so `nthRoot(-1,2)` throws exception. This is a bit weird, because `sqrt(-1)` returns `i`.

Even more weird and completely unintuitive: `nthRoot(-1+0 i ,2)` does **not** throw.

I think the problems are:
- the implementation for complex vs real radicands should be consistent (currently for real radicands a single root is returned, for complex radicands **all** roots are returned).
- the implementation of `nthRoot()` with degree of 2 should be consistent (identical) with the implementation of `sqrt()` (currently it is not).
- the implementaion of `nthRoot` should be continuous @ real number radicands. so e.g. if x->(-3), then `nthRoot(x,n)` -> `nthRoot(x,n)`, if possible.

These are hard to meet. I guess EITHER:
- roots should only be implemented for real numbers (for complex numbers a power can be used), OR
- roots of real numbers should return the principal OR all complex values as well.

### PR DESCRIPTION
**Pull request by dakotablair**
Here is a patch for #851, and I think it covers all the issues detailed there and in #486, but you tell me.

### CODE REVIEW

**Comment by josdejong** [comment]
@dakotablair I reviewed your PR, it looks great, thanks for your work! It's is a nice improvement.

Since this will change existing behavior I will merge this into a `v5` branch, scheduled for the first next breaking release.

Two small feedback points:
- Can you make the error message for `nthRoot` a bit more descriptive? It's currently "Argument must not be type Complex". Maybe change it to something like "Complex number not supported in function nthRoot. Use nthRoots instead.".
- I just discovered a but that was already in the code: the function does not an array with three complex values, but returns three objects with properties `r` and `phi`. This PR is a nice opportunity to correct this behavior too. Can you change that as well?

**Comment by dakotablair** [comment]
I made your suggested updates, but I seem to have broken some other tests, so I will work on fixing those. In the mean time, please inspect the `_nthComplexRoots` function. I altered it as you suggested, but also added a few features:
* purely imaginary and real roots are treated specially to avoid returning values like `1 + epsilon*i`
* if the argument is zero, the array returned returns a single complex zero value.

**Comment by josdejong** [comment]
wow, these are some nice extra improvements! Looks good @dakotablair, thanks.

I was thinking: right now you have the function `_onRay` which sometimes returns an index (and sometimes undefined), and separately the corresponding array `rays` (which is dynamically created every time). How about changing the `_onRay` function such that it immediately returns the result of executing the correct rays function? Rename it to something like `_calculateIntegerResult` which returns `Complex` or `null`.

**Comment by dakotablair** [comment]
Take a look at the diff and see if that's more in line with what you're thinking. I rearranged things slightly to make it clearer what was going on. As is, if we know the argument of the root is an integer multiple of pi/2 then it uses the special case functions which are still stored in an array, but computed only once.

This could conceivably be extended to rational multiples of pi/2, but that should wait probably until a more "exact" approach is implemented. That is, until the Complex type can support things like natively storing a rational value for `phi` to give users the option of dealing with a rational type rather than the JavaScript float. I'm not sure if your vision of math.js looks like that, but it's worth thinking about

**Comment by dakotablair** [comment]
So in the most recent update I introduced a bug that was the reason the original `_onRay` function returned undefined sometimes.

Consider this calculation:
`var halfPiFactor = (offset + 4*k)/root`

This should be an integer if we are going to apply the special treatment, so the test is to see if it is:
`if (halfPiFactor === Math.round(halfPiFactor)) {`

however, if `offset` is `0`, then that suggests the argument is on the real line. Hence the problem with initializing `offset` to `0`. On the other hand, if `offset` is `undefined` then `halfPiFactor` will evaluate to `NaN` which fails the integer test above.

**Comment by josdejong** [comment]
Thanks @dakotablair , I find the latest version of `_nthComplexRoots` indeed easier to understand :+1: 

I will merge your work now. We will release v5 when all breaking changes for v5 are addressed (see #1045)

**Pull request merged**
