### PR TITLE
Run IE 11 tests on pull requests

### PR DESCRIPTION
**Pull request by harrysarson**
The BrowserStack set up we have does not run until after a pull request is merged into mathjs. To help folk not to accidentally add features that are incompatible with IE 11 I have hooked up an integration with [azure pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/?view=azure-devops) which can run tests on IE 11 ([see my test runs](https://harrysarson.visualstudio.com/harrysarson/_build?definitionId=3&_a=summary)) during pull requests.

For this to work, you (@josdejong) would need to "install" azure pipelines to mathjs - I think this is the link: https://github.com/apps/azure-pipelines/installations/new.

It may not be worth adding a whole new integration just to check tests pass in IE 11 for pull requests.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Harry, this is an interesting experiment.

Some thoughts:
1. The reason we do not run browserstack tests on PR's is because that could expose the private browserstack keys to the code in the PR. Is there a similar risk for the Azure solution?
2. A hybrid solution doing some tests on BrowserStack and others on Azure is not ideal, it complicates the setup. I prefer to have a single solution. And like you say, it's a good question if not having early detection of IE issues outweighs the more complicated setup. We will detect the issues as soon as we merge them in `develop`. What do you think?
3. We could have another look if there are solutions to prevent exposing the BrowserStack keys? I guess we're not the only ones having this issue.

**Comment by harrysarson** [comment]
The problem with BrowserStack is that the the karma config file reads the secret password from an environment variable. If we configured travis to set this environment variable for pull requests a malicuous person could submit a pull request to mathjs that reads the value of the secret environment variable and logs it. They could then read the logs and use our browsersack account for their own uses.

> Is there a similar risk for the Azure solution?

The azure solution uses an instance of IE11 running on the CI server - there are no private keys.

> We will detect the issues as soon as we merge them in develop. What do you think?

We will, also changes made by contributors (which are usually the most substantial ones) can be made on branches of this repo and will thus be tested on browserstack. The gains are fairly marginal. I confess that a majority of my motivation for this was to try out Azure pipelines; I would advocate for merging this but only extreamly weekly.

**Comment by josdejong** [comment]
> The problem with BrowserStack is that the the karma config file reads the secret password from an environment variable.

Yes indeed. Reference for my future self: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions.

Tough it's an awesome solution, both the issue it addresses (broken builds on IE after merging a PR) and the solution (a separate testing solution for IE only) feels quite specific to me, whilst it complicates and fragments the setup of our automated testing. For that reason I think it's best not to implement it right now. Let's keep this solution in the back of our minds and reconsider this as soon as the issue (broken builds on IE after merging a PR) regularly occurs ok?

**Comment by harrysarson** [comment]
Sounds good, simple setup is preferable :+1:

**Pull request closed without merging**
