### PR TITLE
Add support for Array values argument in print function

### PR DESCRIPTION
**Pull request by jean-emmanuel**
I can write the tests, can't think of anything else than duplicating the existing ones with arrays instead of objects.

### CODE REVIEW

**Comment by josdejong** [comment]
Nice! Can you indeed add some unit tests? And probably add an example to the code comments showing how to use it with array input? Can you also change the base of your PR to the `develop` branch instead of `master`?

**Comment by jean-emmanuel** [comment]
Alright, I'll get back to it soon !

**Comment by josdejong** [comment]
@jean-emmanuel did you already have time to write a few unit tests and a usage example?

I've just changed the branch to `develop`

**Comment by jean-emmanuel** [comment]
Unfortunately I didn't, but I think I'll be able to do it this week.

**Comment by josdejong** [comment]
:+1: thanks

**Comment by jean-emmanuel** [comment]
Here we go :)

**Comment by josdejong** [comment]
Thanks!

**Comment by jean-emmanuel** [comment]
Yay :tada:

**Comment by josdejong** [comment]
Now available in `v4.1.0` :)

**Pull request merged**
