### PR TITLE
ObjectNode: prettier LaTeX output

### PR DESCRIPTION
**Pull request by FSMaxB**
This is my current approach, tell me if I should change something.

Example:
latex

### CODE REVIEW

**Comment by josdejong** [comment]
Cool, smart idea to use a matrix for this. 

I experimented a bit further with your idea. I think it looks nicer when the key and value are on the same row:

image

or maybe without closing bracket, and with keys/values in a single cell:

image

Still, I think it becomes messy when you have larger objects with deep nesting, but that may not be a big problem in practice.

**Comment by josdejong** [comment]
I also tried a more "traditional" solution, see this fiddle: http://jsfiddle.net/emqchL0a/3/, but I didn't yet manage to position the matrix cells top left.

**Comment by josdejong** [comment]
Hey, we could also use `\begin{cases} ... \end{cases}` ([see example](http://timmurphy.org/2011/12/12/math-case-definitions-in-latex/)) instead of matrix, that way we can left align the keys and values:

image
 
This will make the LaTeX much better readable in case of deep nesting.

**Comment by FSMaxB** [comment]
The `cases` environment doesn't work for empty objects, because it will just be an opening curly brace. This could be handled by an extra check for empty objects, but it would make everything inconsistent.

I couldn't find a way to do alignment with matrices, but the `array` environment seems to work just fine.

I'll update the code with everything being on the same row and using left aligned arrays, but including a closing curly brace for now.

**Comment by josdejong** [comment]
aha! now I finally managed to align cells of an array, so we can actually layout an object like we are used to in code editors: http://jsfiddle.net/je72txhc/

However I think in the LaTeX/math world your solution looks better, showing an object enclosed in two angle brackets. Thanks for helping out here, I will merge your PR now.

**Pull request merged**
