### PR TITLE
fix(algorithm): updated matAlgo07xSSf algorithm to return sparse matrix

### LINKED ISSUE #3219: `dotDivide` changes to denseMatrix when the inputs are sparseMatrix
Hi, 

I found an odd behavior of sparse matrices in `dotDivide` on 13.0.0

```js
math.dotDivide([1, 2], [1, 1])
// [1, 2]
// OK

math.dotDivide(math.sparse([1,2]), 1)
// SparseMatrix [1, 2]
// OK

math.dotDivide(math.sparse([1, 2]), math.sparse([1, 1]))
// DenseMatrix [[1], [2]]
// it's odd that the shape changes and it returns a DenseMatrix

math.dotDivide(math.sparse([1, 2]), math.sparse([1]))
// TypeError: undefined is not an object (evaluating 's[t]')
```

The implementation of `matrixAlgorithmSuite` in `dotDivide` seems different than the one in `dotMultiply` maybe it has something to do with the issue.

I found this while working on #3196, found that for sparse matrices broadcasting isn't working very well and went into a rabbit hole to find this separate issue.

### PR DESCRIPTION
**Pull request by Aakash-Rana**
## Updated `matAlgo07xSSf` algorithm and fixed #3219

This PR addresses an issue in the `matAlgo07xSSf` algorithm, where the result of any operation on two sparse matrices returning a dense matrix instead of preserving the sparse matrix format. This function `matAlgo07xSSf` is utilized by various functions such as  dotDivide , dotPow , bitXor , larger , smaller , equal , xor , smallerEq etc - to perform operations on sparse matrices.

The update ensures that the result of any sparse-sparse operation is correctly returned as a sparse matrix, maintaining consistency with the input types.

Changes:
- Refactored the `matAlgo07xSSf` algorithm to handle operations of sparse-sparse matrix ensuring only non-zero or true results are stored.
- Adjusted dependencies to properly handle sparse matrix operations.
- Updated corresponding test cases to compare result with sparse matrix.

@race-of-sloths Include this PR

### CODE REVIEW

**Comment by race-of-sloths** [comment]
### 🙁 This repository is not a part of the [Race of Sloths](https://race-of-sloths.com)
Please ask the maintainer to [contact us](https://github.com/NEAR-DevHub/race-of-sloths/issues/new/choose) to join the race!

<details><summary><strong>What is the Race of Sloths</strong></summary>
<p>

Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag us inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/Aakash-Rana)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!

</p>
</details>

**Comment by akorchyn** [comment]
Hello. First of all, sorry for hopping in the PR.
I just wanted to share that we have added a repo to the supported list. You can keep using it here. Enjoy!

@race-of-sloths

**Comment by josdejong** [comment]
Thanks @Aakash-Rana, this is a neat fix! 

I'll merge this PR into the first next major version `v14` since it changes the behavior of the functions like `dotDivide` and `dotPow`.

**Review by josdejong — APPROVED** [review]

**Comment by Aakash-Rana** [comment]
Hello @josdejong 
Thanks for the review. Yes it could be a breaking change and should go in the next major release.

**Comment by josdejong** [comment]
@race-of-sloths score 13

**Comment by josdejong** [comment]
Published now in `v14.0.0`.

**Pull request merged**
