### PR TITLE
Fix #1512: bug in format notation `engineering`

### LINKED ISSUE #1512: format in engineering notation with precision < 3 can produce incorrect results
Numbers such as 100e3, which is a perfectly valid engineering notation number, will be formatted as 10e3 when the precisions is set to 2. Formatting a number should never change its value. This is a general bug whenever the engineering notation would require a significand with more digits than the specified precision.

Example code:
```
const mathjs = require('mathjs')

const testEngFormat = () => {
  const testNumber = 100e3
  console.log(`testNumber ${testNumber}`)
  const formattedNum = mathjs.format(testNumber, {notation: 'engineering', precision: 2})
  console.log(`formattedNum ${formattedNum}`)
  const equal = testNumber === Number(formattedNum)
  console.log(`equal ${equal}`)
}

testEngFormat()
```

### PR DESCRIPTION
**Pull request by josdejong**
This is a fix for #1512 

@ericman314 can you review the fix and do some thorough testing too? 

It's not very elegant fix, I have the feeling that can simplify the implementation of `toEngineering`. But at least it's a fix.

### CODE REVIEW

**Comment by josdejong** [comment]
The issue was that in case of the following example, one zero was added to the significant digits `"1"` making it "10", but no zeros where added to account for the left over exponentials: (exp 2 turning "1" into "100").

```js
math.format(100, { notation: 'engineering', precision: 2 })
// output: "10e+0"
// expected: "100e+0"
```

**Comment by ericman314** [comment]
I will take a look at it tonight.

**Comment by ericman314** [comment]
Well, to be honest the `toExponential` function for numbers does seems to be quite complicated, but I couldn't find any bugs. I added some more tests. I think we should release the fix for now and then return later to clean up that function.

**Comment by josdejong** [comment]
Yes that's exactly my feeling too, the function can use some refactoring. I will publish this fix tonight after work, thanks for reviewing @ericman314 and @harrysarson!

**Pull request merged**
