### PR TITLE
Matrix storage formats

### PR DESCRIPTION
**Pull request by rjbaucells**
This is a refactoring allowing Matrix to use different storage formats. So far DenseFormat (dense) is the only one fully implemented (the one used by Matrix before). Two other formats are available Compressed Row Storage (crs) and Compressed Column Storage (ccs) but they are not fully implemented. These are the API changes (non breaking changes, existing code should continue working without problem):

Matrix: constructor allows a second optional parameter to specify the storage format:

`var m = new Matrix([], 'dense');`

Parser: constructor parameter `math` is no longer used, you can create a Parser without specifying one:

`var p = new Parser();`

Matrix related functions have not been modified. Optimization for specific storage formats will come next.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Rogelio, I will check it out this weekend.

**Comment by josdejong** [comment]
Nice job! Sorry for the late reply, I wanted to take the time to see what you created. It looks neat.

First a practical question: what improvements do these three new formats bring exactly? I suppose it's about memory usage. I'm wondering how JavaScript itself does with regard to "sparse" arrays: when you create a `new Array(1e9)` it just leaves all entries undefined, which could maybe serve as a "sparse" matrix by itself. Did you do some testing with the actual gains of these matrix formats in JavaScript with respect to the current implementation?

I suppose this will really start to pay off when we use typed arrays. This isn't yet the case. For me, having a matrix implementation which stores the entries in a flat Array (with multi dimensional support) rather than the current nested arrays is priority one in that regard. When that's implemented it's a small step towards support for typed arrays.

A few questions:

1. Just for clarity, `CcsFormat`, `CrsFormat` and `DenseFormat` support 2d matrices only, right? I think that's ok. Does the code throw an error when you try to load a 3d matrix?
2. I don't see the added value of packing Parser.js in a factory function instead of passing the `math` namespace on construction. It's a non-public prototype which is normally created indirectly via the function `math.parser()`, so you don't need to provide `math` anyway.
3. Right now there is still one Matrix class `new Matrix(data [, format])`. It stores data in the property `_storage`, which can be an instance of different storage types. Most methods of Matrix are reduced to making the same call to the internal _storage object. Instead of this, would it make sense to use `Matrix` as a base class, and create different implementations for this like `DenseMatrix`, `CcsMatrix`, and `CrsMatrix`. Each can extend `Matrix`, so that type checks on `Matrix` return true. Instead of specifying a type in the constructor of `Matrix`, you can either programmatically create a new Matrix of certain type, or use the constructor function `math.matrix(data [, format])`.
4. For v2, I'm trying to get rid of passing the global math instance around everywhere, and instead only pass `config`, and something like `dataTypes` (containing BigNumber, Matrix, Unit...). It's not yet completely decided on the final structure for v2. Would it work ok to pass `config` and `dataTypes` to parse.js, collection.js, etc instead of `math`?

**Comment by rjbaucells** [comment]
Jos,

Memory usage is one of the advantages of having Sparse Matrix representations. The CCS and CRS formats store only the non-zero elements (compressed), The amount of memory required to store a big sparse matrix is smaller than storing the same data in a dense format. For example, in a compressed row storage format (CRS) the memory requirements for a MxN matrix with NZ non-zero items is:

CRS = (2 * NZ) * sizeof(item) + (M + 1) * sizeof(int)

Dense = M * N * size(item)

The second advantage (the most important) of using compressed formats is that we can have function implementations that are optimized to handle sparse formats, for example matrix multiplication, diagonal, eye. There are algorithms that perform fast operations on these type of matrices.

The use of typed arrays for sparse storage formats could give an extra improvement but the big gain is by optimizing the storage for the specific type of data (sparse).

1- CssFormat and CrsFormat are for 2d matrices, items are numeric values (zero or non-zero). DenseFormat is the same implementation from Matrix in version 1.x, nothing has changed there.

2- You need to define Parser in a factory function due to the following dependencies:

- Parser.js depends on parse.js (Parser.js line 5)
- parse.js depends on Matrix (parse.js line 27)

3- Yes, this could be implemented using inheritance. I do not remember now why I went down this route. Let me know if that's the way we should go and I will update the implementation.

4- Yes. Passing `config` and `dataTypes` will work. One thing that we have to look into is that for some of the "optimized" operations that takes in consideration the internal storage format we might need some of the existing math functions. For example:

`CrsFormat.prototype.multiply = function () {      will eventually call math.multiply()      }`

I have not finalized these optimizations but I am pretty sure that something like that will be needed.

**Comment by josdejong** [comment]
Thanks, makes sense. I'm really looking forward to see this in action.

2. I think your solution of having a factory function for Parser.js makes most sense, is consistent with the rest.
3. It's open for discussion to me. I think it makes sense to create different classes for this, that removes this indirection via a shallow "wrapper" class. I think it will result in simpler, more straight forward code. The base class `Matrix` could become an abstract class, throwing errors when extended classes forgot to implement required methods similar to [/lib/expression/node/Node.js](https://github.com/josdejong/mathjs/blob/master/lib/expression/node/Node.js#L84).
4. Good point about calling functions from the math namespace. Maybe for now, for v1, we should leave it as is: passing the `math` namespace. For v2, we can easily switch to just passing config. (v2 is making good progress btw).

Awesome, I like this stuff :)

**Comment by rjbaucells** [comment]
I have updated the implementation using inheritance from `Matrix`. Only `DenseMatrix` is fully implemented, `CcsMatrix` and `CrsMatrix` are a work in progress.

**Comment by josdejong** [comment]
Thanks, this looks great. 

Until you've completed the implementations of `CcsMatrix` and `CrsMatrix` I think we should keep this code in a feature branch separate from `develop`. Can be the current `matrix2` branch on your account, or we can create a `matrix2` branch in `/josdejong/mathjs`. What do you think?

**Comment by rjbaucells** [comment]
Yes, we can keep it in my matrix2 branch so I can push changes faster. 

I remember now why I initially implemented the matrix formats not using inheritance, to avoid this API break:

`var m = new Matrix(...);`

Since Matrix is now an interface (no implementations), code using the Matrix instance will eventually throw an exception. I do not know if that was the recommended way to create a matrix before but we should push to avoid creating types directly.

Using the `math.matrix()` API call will not have this problem:

`var m = math.matrix(...);`

What do you think?

**Comment by josdejong** [comment]
Good point. This is a little bit of an edge case. It's not in the *official* API, but you *can* indeed create matrices like `new math.type.Matrix([...])`. This is nowhere described in the docs or examples though, which usethe factory function `math.matrix([...])` everywhere. 

Do you have an idea on how much work there is left here, and how much time that would take? I mean, suppose v2 will be ready within one to two months, and finishing sparse matrices will be too, it may be nicer to just put everything in v2.

**Comment by rjbaucells** [comment]
I think I can finish before two months, but maybe it is a good idea to push it to v2 so we do not have to re-do everything again. It is your call, let me know.

**Comment by josdejong** [comment]
It's hard to make an estimation on how much work it will be to convert the sparse matrix functionality from v1 to v2, The new Matrix implementations will be easy to merge. How many functions do you expect to extend with special algorithms to embrace sparse matrices? I expect these sparse algorithms to be relatively isolated, in which case it will be not that hard to merge into v2. 

And thinking about it, implementing the sparse matrix functionality right now in v2 will make it harder for you: it's currently half converted and the final structure isn't yet fully decided upon.

I think it's best to implement sparse matrices in v1, shall we go for that?

**Comment by rjbaucells** [comment]
Ok, v1 is the target. 

I would estimate that the functions in the function/matrix folder will be touched by the changes.

**Comment by josdejong** [comment]
Yes exactly. And maybe the function `collection.deepMap`  which is used by functions with one argument (like `abs`, `sqrt`, `sin`, etc) for handling matrices element wise.

**Comment by rjbaucells** [comment]
For the case of `collection.deepMap` I would like to propose a small API change (non-breaking), current signature is:

```js
collection.deepMap = function deepMap(array, callback) {
};
```

It will bring a big difference optimizing functions like `abs`, `sqrt` for sparse matrices if we add an optional parameter:

```js
collection.deepMap = function deepMap(array, callback, nonZeros) {
};
```

When `nonZeros=true` the callback function will be invoked only for non-zero values. For these functions a zero value does not make any difference `abs(0) == 0`. The `collection.deepMap` implementation delegates the functionality to `array.map()` and this operation is optimized for sparse matrices when the non-zero parameter is true.

What do you think?

**Comment by josdejong** [comment]
Yes, that makes sense. What would be the best name for this argument? Maybe `skipZeros` is more clear than `nonZeros`? The default behavior of `deepMap` should be the safest one: iterate over all values including zeros.

**Comment by rjbaucells** [comment]
I have completed the implementation of sparse matrices. There are three type of matrices:
- Dense Matrix (`'dense'`): The previous matrix implementation
- Compressed Row Storage (`'crs'`): MxN sparse matrix implementation
- Compressed Column Storage (`'ccs'`): MxN sparse matrix implementation

All matrix related functions now delegates the matrix operations on functions implemented in the specific Matrix type. Operations that were forbidden before (very slow) are very fast, as an example try the following operations in the mathjs command line interface:

```mathjs
a = eye(1000, 1000, "ccs")
b = a * a
c = b * complex(2, 2)
d = transpose(c)
d * a
```

As a comparison try the same operations based on a dense matrix `a = eye(1000, 1000)`.

Let me know what you think...

**Comment by josdejong** [comment]
wow, impressive! That's a huge difference! 

Shall I merge your code, or do you still have some things you want to work out?

Maybe for a next iteration: Would it be a good idea to let some functions automatically select the "best" storage type depending on the data? Like `eye` and `diag` could by default create a sparse matrix instead of dense. 
We could also create a configuration option for the default matrix type: `'matrix': 'auto' | 'dense' | 'crs' | 'css'`, which in case of `'auto'` would analyze the data on construction of a matrix (`math.matrix([...])`), and automatically select the best suited storage type (dense or sparse).

**Comment by rjbaucells** [comment]
Jos,

You can merge the code. 

I like your idea of having an `'auto'` format for detecting the best one for the data but I think it would be better to leave it for v2. As you can see in the code matrix related functions contains an extra parameter for the storage format, since this parameter is optional we have to create `if()` statements to analyse the parameters been passed, this code would be cleaner in v2. I can help you migrating the code to v2, 

I think for v1 is enough having the data types and some control over the type of matrix the client wants based on the data been processed.

Another thing is that many matrix related operations not currently implemented in mathjs can be implemented using the modular approach in v2 (decomposition, solvers...).

**Comment by josdejong** [comment]
Ok thanks a lot for all your work, nice job!

**Comment by josdejong** [comment]
Rogelio, I've just released math.js v1.5.0 with your sparse matrix implementations, congrats! The website still has to be updated.

**Comment by rjbaucells** [comment]
Perfect, I am in the process of porting everything  to v2. I will push all the necessary changes next week.

**Pull request merged**
