### PR TITLE
Fix nearly-zero temperature conversion result

### PR DESCRIPTION
**Pull request by costerwi**
The unit conversions with offset, like temperature, accumulate an unsightly roundoff error near zero:

```javascript
math.unit('32 degF').to('degC').toString()
"5.684341886080802e-14 degC"
```

This pull request sets the conversion result to exactly 0 if it is within `config.epsilon` of 0.

### CODE REVIEW

**Comment by mgreminger** [comment]
I agree that the string rendering of the value that should be exactly zero is unsightly. However, I would argue the issue should be handled in the string rendering of the value rather than at the conversion calculation level. The proposed implementation uses `config.epsilon` in a way that doesn't match the [documented purpose of `epsilon`](https://mathjs.org/docs/core/configuration.html), which may be surprising to users (especially if they reduce the value of `epsilon` not expecting it to impact actual calculations). Second, it appears as though the proposed implementation would apply to both bignumber conversions and regular number conversions, thus significantly reducing the precision of bignumber calculations for values near zero.

One solution that can be used by the user of the library would be to use `format` rather than `toString` and to use the option to pass a callback function to `format` to round the number to the desired precision before the string rendering:

```javascript
> math.unit('32 degF').to('degC').format((value) => math.round(value,2).toString())
'0 degC'
``` 
The benefit of this approach is that it works with other conversions that should be exact as well such as the conversion of -40 degrees:
```javascript
> math.unit('-40 degF').to('degC').toString()
'-39.99999999999997 degC'
> math.unit('-40 degF').to('degC').format((value) => math.round(value,2).toString())
'-40 degC'
```

**Comment by mgreminger** [comment]
Rounding to 12 digits works as well and will give approximately the same precision as using epsilon since epsilon is 1e-12 by default:

```javascript
> math.unit('32 degF').to('degC').format((value) => math.round(value,12).toString())
'0 degC'
> math.unit('-40 degF').to('degC').format((value) => math.round(value,12).toString())
'-40 degC'
> math.unit('1 degF').to('degC').format((value) => math.round(value,12).toString())
'-17.222222222222 degC'
````

There's not a great way to get around the rounding issue at the unit conversion level when using the javascript number type since it's running into the [limitations of floating point math using the IEEE 754 standard](https://javascript.plainenglish.io/why-0-1-0-2-0-3-in-javascript-d7e218224a72). Here's the raw calculation using the javascript number type:

```javascript
> (32+459.67)*(1/1.8)-273.15
5.684341886080802e-14
```

Ideally, using the mathjs bignumber type would solve this issue since it doesn't face the same limitations as IEEE 754 floating point math. However, due to the way some of the conversion scaling factors are defined, using bignumber does not solve this particular issue:

```javascript
> math.unit(math.bignumber(32), 'degF').to('degC').toString()
'2.1852e-14 degC'
```
The bignumber issue arises from the definition of the of the temperature [scaling factor](https://github.com/josdejong/mathjs/blob/23cf6e8035237747f5d197e659eeeaab3996bd89/src/type/unit/Unit.js#LL2312C1-L2312C22). Since `1/1.8` cannot be represented exactly as a javascript number type,  the precision is lost at the time of definition. Because of this, the later [conversion to bignumber](https://github.com/josdejong/mathjs/blob/23cf6e8035237747f5d197e659eeeaab3996bd89/src/type/unit/Unit.js#LL837C13-L837C26) does not restore the precision.

**Comment by costerwi** [comment]
This PR is only applicable to the very limited situation of unit conversions involving different offsets. This unique situation accumulates round-off errors which are beyond the precision of the offsets themselves. It seems like the appropriate place for improvement is within the `.to` method where the round-off happens, not necessarily in the `.toString` which affects everything.

Anyway, this latest commit adds a few more unit tests and it uses the `Fraction(5, 9)` to more accurately represent 1/1.8. This is not perfect but it is able to pass the major tests which the current develop branch will fail.

I greatly appreciate the discussion. It has already allowed me to make a reasonably robust solution in my own project. I certainly understand that using a Fraction in the unit value is a big change and perhaps not the direction we want to go but I was pleasantly surprised at how easy it was to implement.

**Comment by josdejong** [comment]
Ah, I see what you mean. You want the `toNumeric()` to replace any internal Fraction with a number. I think that is best not to do, because when I explicitly create an unit holding a fraction, like `math.unit(math.fraction(1/3), 'cm')`, I would like to let `toNumeric()` return this fraction, and not convert it to a different numeric type. I think `Unit` itself should be agnostic to what numeric type it is dealing with exactly. Does that make sense?

**Comment by costerwi** [comment]
Hi Jos, sorry but I think you misunderstood. The returned value type is matching the original value type. This is the same behavior as the current method. The use of the Fraction(5,9) internally provides additional accuracy but does not affect the returned type. For example:
```javascript
math.unit(math.fraction(32,1), 'degF').toNumeric('degC')    // Fraction(0,1)
```

**Comment by josdejong** [comment]
To make sure we're on the same page: what would the type of the internal `math.unit(98.6, 'degF').value`? A number or a Fraction? At what moment do we switch from number to Fraction and back to number in the expression 
`math.unit(98.6, 'degF').toNumeric('degC')`? 

> This is the internal calculation:
> 
> ```js
> f = math.fraction(5, 9)
> f*98.6 + Number(math.subtract(math.multiplyScalar(f, 459.67), 273.15))  // 37
> ```

To really utilize Fractions, all operations should be done with Fractions and only at the end we should convert the result to a number. Else you'll introduce rounding errors halfway the operation. So I think the proposed internal calculation should be something like the following, which results in a Fraction right now:

```js
f = math.fraction(5, 9)
math.add(math.multiply(f,98.6), math.subtract(math.multiply(f, 459.67), 273.15)) // Fraction 37
```


Right now, when you do a mixed operation like `math.multiply(f,98.6)`, the number `98.6` will be turned into a Fraction (implicit type conversion), then two fractions are multiplied, and the result is a Fraction. So, naturally, `math.unit(98.6, 'degF').value` would be a Fraction when we change `math.Unit.UNITS.degF.value` into a Fraction and operate on that. 

I think that if we go this route, `math.unit(98.6, 'degF').value` should be a Fraction, and the conversion to a number should only be done at the last step. What are your thoughts?

**Comment by costerwi** [comment]
> what would the type of the internal math.unit(98.6, 'degF').value? A number or a Fraction?

This value is a number type, exactly like it has always been. This is due to the [liberal use of `_getNumberConverter` within the `_normalize` method](https://github.com/josdejong/mathjs/blob/bf911816d3644e2780506930a0868484cd437630/src/type/unit/Unit.js#L499C1-L504) which was not altered by this PR.

> At what moment do we switch from number to Fraction and back to number in the expression
math.unit(98.6, 'degF').toNumeric('degC')?

The use of fractions happens inside the `to` method which is called by `toNumeric`. The `to` method [uses `_getNumberConverter` at the end](_getNumberConverter) so that the numeric type of the unit's value remains consistent. This is enough to provide a big improvement in accuracy without unexpectedly changing the value to a fraction. It also avoids the possible loss of accuracy converting a BigNumber value into a fraction. The user still has the option to store value as a fraction if they define the unit with that type like this: `math.unit(math.fraction(98.6), 'degF')`

The PR includes a [handful of new tests, including tests with BigNumbers](https://github.com/costerwi/mathjs/blob/b0f1353f2bfce8cd937419e2b798285210405f04/test/unit-tests/type/unit/Unit.test.js#L300C1-L313), which might help to demonstrate its advantage. All of these new tests are passing in the PR but failing in the develop branch.

**Comment by josdejong** [comment]
Ahh, I finally get it 😅, thanks for your patience. 

I was assuming that `.value` would have to be a `Fraction` in order not to lose precision when converting °C to °F for example, but now I see that (a) in the method `.to()` you defer converting this Fraction to number until after the operations (so the operations are done as Fraction), and (b) when constructing a Fraction, the value is already normalized into the number type of the input number (in method `_normalize`). This is indeed a perfect solution, and I don't think it has side effects 😎 .

Two remarks:

1. Is there a special reason you do the last `addScalar` after `convert`? I guess we can do `convert` last and wrap it around `addScalar`? 
2. In `._normalize()` and `._denormalize()` we too have a couple of conversions first and an operations next. Should we change that too to first do the operations and last the conversion? I can't come up with a case (it's like finding an `0.1+0.2` example that accidentally has a round-off error), but I guess it can happen with specific combinations of an input value and 1/1.8.

**Comment by costerwi** [comment]
If we simply `addScalar` _before_ `convert` then, when the value is a BigNumber, we get this TypeError in `addScalar` so we must chose a type:

> Cannot implicitly convert a Fraction to BigNumber or vice versa. Use function bignumber(x) to convert to BigNumber or fraction(x) to convert to Fraction.

There is a potential loss of accuracy converting number or BigNumber into Fraction so the PR is a safe compromise to perform the `convert` just before the `addScalar`.

Similarly for `.normalize()` and `._denormalize()` I think we could lose accuracy if we try to perform all calculations as Fraction and then convert at the end.

**Comment by josdejong** [comment]
I understand it, that makes sense.

Ok let's leave the PR as it is right now, it looks solid. Thanks again, I'll merge it now!

**Comment by josdejong** [comment]
The fix has been published now in `v11.9.0`

**Pull request merged**
