### PR TITLE
Implement toHTML() to Nodes v2

### PR DESCRIPTION
**Pull request by Nekomajin42**
toHTML() method to each Node, and update in the docs

### CODE REVIEW

**Comment by Nekomajin42** [comment]
Hi Jos!

I've fixed the `OperatorNode` problem and updated the docs, as we've discussed in #758.
I've created a new file for the class names and linked it in the `toHTML` section, because it's a long list, so it's more readable this way.

**Comment by josdejong** [comment]
Thanks for getting back onto this one, I will review it more thoroughly within a few days.

Two things that pop into my mind:
- Last months I've been busy securing the expression parser. This new `.toHTML` method should be secure too and does not allow injecting JS into HTML. Like when you create a string `math.parse("'...'").toHTML()` where the string contains bad code (I haven't look at whether it's secure against that sort of things already)
- We may need an example to demonstrate toHTML.

**Comment by Nekomajin42** [comment]
I am working on a browser extension, so I can provide some code for a toHTML demo.

About the security, it's your call, because I am not an expert in this field.

**Comment by samczsun** [comment]
Re: security, one change that would prevent a majority of injections would be to do what has been done with compilation. That is, register a function and always check if the provided object is an instance of the node. Otherwise I could just replace the `index` field [here](https://github.com/josdejong/mathjs/pull/859/files#diff-aaf67fdb8bb7580eb2981377d80b3af6R160)

**Comment by josdejong** [comment]
@Nekomajin42 yeah a demo would be useful.

Thanks @samczsun . I think there are two different kind of security risks here: one is trying to hack into the JS engine running the expression parser of math.js (similar to the security issues we've been solving last months), the other is trying to get some malicious expression rendered in HTML in a browser. For that last, new category I think we can draw inspiration from template engines like handlebars or lodash.template and involves things like escaping HTML tags. (I haven't dived into it deeply though)

**Comment by samczsun** [comment]
I can't imagine how you'd run into issues with the JS parser if you're just emitting HTML though

**Comment by josdejong** [comment]
I don't know in depth but as far as I understand it injecting JavaScript in HTML could allow [XSS attacks](https://www.wikiwand.com/en/Cross-site_scripting).

**Comment by samczsun** [comment]
Oh I see what you mean. I thought you meant injection akin to what I was doing with the nodes earlier.

A templating engine sounds pretty good for generating HTML.

**Comment by Nekomajin42** [comment]
@josdejong 
I guess you should merge this PR then I can add a demo tool to the HTML classes file using the RESTful API. 
I think and input field with two outputs (one for the result and one for the plain HTML) would be fine.
Is it OK?

**Comment by josdejong** [comment]
Wouldn't it be possible to create a simple pure client side example similar to this example?

http://mathjs.org/examples/browser/pretty_printing_with_mathjax.html.html
http://mathjs.org/examples/browser/pretty_printing_with_mathjax.html

Or maybe we could extend (and rename) this example to add HTML output.

I prefer waiting with merging until we have the security related issues sorted out. I can merge in a separate branch in the mathjs project if that would help you though but I don't think that's the point.

**Comment by Nekomajin42** [comment]
Ok, it's better. I will try to look into it in the next few days.

**Comment by josdejong** [comment]
@Nekomajin42 I was just thinking about the `toHTML` method last few days. It sounded like a very logical and useful feature when we discussed it months ago, but right now I'm having difficulty coming up with use cases, and also, nobody else reacted on this topic as a wanted feature these months. 

You have quite a special use case, developing an editor, and `toHTML` forms half of your solution there (rendering), the other half you implement yourself I suppose (manipulating and controlling editable HTML, dealing with caret location etc). A related topic is #834 about implementing syntax coloring for mathjs in existing editors like codemirror or Ace.

The only use case I can come up with is developing an editor like you do. But hardly anyone will do so. And even then, I'm not sure whether `toHTML` will be useful: it offers only part of the code that you need (rendering), but for example when using React you can't use it and probably need something returning virtual dom instead of HTML. 

What are your thoughts on applicability and use cases for `toHTML`?

**Comment by Nekomajin42** [comment]
I think they have different use cases. If I want to build a basic calculator with a few basic functions, it's easier to use mathJS, than implement my own parser. However, in this case, loading a JS library to post process the output is overkill. On the other hand, when you have a more advanced interface and you want to allow in-place modifications, the JS solution is definitely better.

In my concrete case, the app has an input field and displays all the inputs and their results above this field. The results are not editable (although I may implement a feature to copy the original input by clicking on the result). It's more like a command line calculator, where you can access previous inputs by walking in the history with the up and down cursor buttons.

I think an HTML output is as useful as the LaTeX one. For basic tasks, it better than using JS because it's more lightweight and easier to customize. For content editable interfaces using JS is better, but if you don't want that, why would you use a library to generate HTML when you can have it straight from the parser?

**Comment by josdejong** [comment]
Ah, I understand your use case now, I was only thinking about two way binded HTML. Ok makes sense, thanks. :+1:

Reason for not using the built in toHTML when editable interface: when working in React/Angular/vue.js the HTML is controlled by the used framework, you can't just inject random HTML because your DOM will not be in sync anymore with the virtual dom of the framework.

As for the HTML security: this shouldn't be too difficult. I just came across [escape-goat](https://github.com/sindresorhus/escape-goat) which is exactly what we need. Basically, every value that goes into toHTML should be run though this `escape` function (for example `this.value` of `ConstantNode` and `this.name` of `SymbolNode`). @Nekomajin42 can you add these `escape` functions, or shall I do this after merging?

**Comment by Nekomajin42** [comment]
Should I just use `this.value.escape().toHTML()`? How do you want the function to be imported?

**Comment by josdejong** [comment]
Yes, almost. For example `FunctionNode.prototype.toHTML`:

```js
FunctionNode.prototype.toHTML = function (options) {
  var args = this.args.map(function (arg) {
    return arg.toHTML(options);
  });

  // format the arguments like "add(2, 4.2)"
  return '<span class="math-function">' + this.fn + '</span><span class="math-paranthesis math-round-parenthesis">(</span>' + args.join('<span class="math-separator">,</span>') + '<span class="math-paranthesis math-round-parenthesis">)</span>';
};
```

should become:

```js
var escapeGoat = require('escape-goat');

// ...

FunctionNode.prototype.toHTML = function (options) {
  // (no need to escape args, that's done in the toHTML of each arg already)
  var args = this.args.map(function (arg) {
    return arg.toHTML(options);
  });

   // format the arguments like "add(2, 4.2)"
  var fn = escapeGoat.escape (this.fn);
  return '<span class="math-function">' + fn + '</span><span class="math-paranthesis math-round-parenthesis">(</span>' + args.join('<span class="math-separator">,</span>') + '<span class="math-paranthesis math-round-parenthesis">)</span>';
};
```

**Comment by Nekomajin42** [comment]
@josdejong 
It seems the build has failed because of the unknown `escape-goat` reference. It works on my machine, because I've installed it with Node. How can I fix this?

**Comment by josdejong** [comment]
I think you forgot to add the new dependency `escape-goat` to package.json?

**Comment by Nekomajin42** [comment]
Yep, lame mistake.

But it seems I also have to use `String()` on the argument before using `escape()`.

**Comment by josdejong** [comment]
Yes, that could be, sounds logical that the `escape()` expects a string

**Comment by Nekomajin42** [comment]
So, I've fixed the errors, it should work now. The test fails on old Node versions because of some syntax stuff in the escape-goat library. How to fix this?

I've also created an example page for the `toHTML` function.

**Comment by josdejong** [comment]
Thanks! 

I suppose escape-goat uses ES6 features not available on older browsers and node.js. so we will have to transpile it or use an alternative library. Not sure what will be the easiest of the two options right now, will look into it

**Comment by Nekomajin42** [comment]
Since it's just a single function, can we implement it? In `utils/string.js` the `stringify` function does similar stuff.  Can we just add an `escape` function?

**Comment by josdejong** [comment]
Yes, that maybe better! Let's not over engineer this. Thanks for your pragmatism :D.

We can copy the code + unit tests from escape-goat and change it to ES5 code.

**Comment by josdejong** [comment]
Looks great, thanks Toth!

**Pull request merged**
