### PR TITLE
Add type signature for lusolve(LUDecomposition, ...)

### PR DESCRIPTION
**Pull request by evanmiller**
`lusolve` has a two-argument format that accepts an `LUDecomposition`, see [here](https://github.com/josdejong/mathjs/blob/61a21da6b7df7c2eb262889250e378f7d44a958a/src/function/algebra/solver/lusolve.js#L77).

### CODE REVIEW

**Comment by evanmiller** [comment]
Bump

**Comment by josdejong** [comment]
Thanks Evan!

I see the linter isn't happy. Can you run `npm run format` to fix the indentation issue?

**Comment by evanmiller** [comment]
Think it's fixed? My local environment's a mess so I just tried to fix the warnings manually 🤞

**Comment by josdejong** [comment]
😂 well, if you clean up the mess on your computer, I'll fix the linting issue for you and merge your PR.

**Comment by evanmiller** [comment]
> 😂 well, if you clean up the mess on your computer, I'll fix the linting issue for you and merge your PR.

I can't promise the former but I appreciate the latter.

Thanks for a great project.

**Comment by josdejong** [comment]
👍  thanks, you're welcome

**Comment by josdejong** [comment]
Fixed now in `v11.5.1`.

**Pull request merged**
