### PR TITLE
Added isPrime method, to check to see if numbers are prime

### PR DESCRIPTION
**Pull request by MathBunny**
* Allows to check if numbers (including bignumbers) are prime 
* Included tests

Let me know if this is useful! I'm new to this whole open-source thing, so let me know what I can work or improve. Thanks :)

### CODE REVIEW

**Comment by MathBunny** [comment]
Heh on second thought this seems really simple and obvious... but I still had fun, not sure if this is any use. I'll take a look at the issues tab though.

**Comment by josdejong** [comment]
Thanks @MathBunny, I like it, its a nice addition :)

Your code looks neat and is well tested, thanks.

**Comment by josdejong** [comment]
Ow, I overlooked your implementation for BigNumber: it implicitly converts a BigNumber to number and *then* checks whether it's a prime, basically throwing away the possibility to test real big numbers. 

Can you maybe do another PR to fix this? Conditions like `x < 2` should be rewritten to `x.lt(2)` and the variable `i` should be created as a BigNumber.

**Comment by MathBunny** [comment]
Thanks!! Definitely, that should be fixed. Just wondering, is there a `mod` function for bignumbers? I tried just `.mod(2)` to see if the number is already even, but it doesn't seem to work for large numbers like `48112959837082048697`. Is there a way to do it for bignumbers with bitmasking? I think if I can do (num & 1) == 0 then I can avoid using mod (which might be a costly/slow operation too).

**Comment by josdejong** [comment]
math.js uses the decimal.js library for BigNumbers, so you can use all functions documented there, such as `x.mod(2).isZero()`, that should work. All operations should be done with BigNumber methods, also checks like is zero or x equals two.

**Pull request merged**
