### PR TITLE
Extend function `round` with support for units

### PR DESCRIPTION
**Pull request by josdejong**
Implements #2761

With three arguments, the number of different combinations of one or multiple of the arguments being an array explodes quickly. I'm not yet sure which signatures _actually_ make sense. Feedback would be welcome.

### CODE REVIEW

**Comment by mofosyne** [comment]
Had a look. Can't guarantee correctness. But it looks about right.

**Comment by josdejong** [comment]
Thanks for having a look Brian. Any thoughts on whether/which arguments should support arrays?

**Comment by mofosyne** [comment]
My personal opinion is that arrays is a separate PR, as there needs to be at least some sanity check on the implication of array support (Unless someone is relying on it). At least with the round() support for units, there is a direct application of this feature at the moment.

What's the application of array support for round in practice and has someone complained about the lack of it?

**Comment by josdejong** [comment]
Thanks for your input. I think being able to do `round(matrix, decimals)` is useful. Other variants less so, and also, you can always execute a matrix element wise using `map`, so it is only for convenience.

With that in mind, I think I'll reduce the signatures of this new feature to support a matrix with units as first arguments, but not implement support for an array with digits or array with unitless units, until people report that they really need that.

**Comment by mofosyne** [comment]
Nice! By the way when's the next release cycle version/timing do you intend this feature to be in?

**Comment by josdejong** [comment]
1 minute ago 😉

**Comment by josdejong** [comment]
This PR is published in `v12.1.0`

**Pull request merged**
