### PR TITLE
add util function hasNumericValue

### LINKED ISSUE #1281: Implement a function hasNumericValue(text)
Hi,

I'd like to request a change to how the `number()` function deals with strings that it can't convert to numbers:

```
number("a") # returns: error;  would like: "a"
```

This would be useful because currently, 

```
isNumeric("1")  # returns: false; 
```

so I would like to be able to do something like this:

```
testNum(val) = isNumeric(number(val));
testNum("1") # would like to return: true;
testNum("a") # would like to return: false;
```

Also, I noticed this result which i didn't expect:

```
isNumeric(NaN) # returns: true;  expected: false
```

Thanks!

### PR DESCRIPTION
**Pull request by Sathish-kumar-Subramani**
fixes #1281

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @Sathish-kumar-Subramani , your PR looks neat and well tested :+1: .

I was surprised by your solution to check whether a string contains a valid numerical value: `!isNaN(x)`. Do you think that's safe to use this solution with type-coersion, or should we use something like `isNaN(Number(x))`?

Also, can you please add a unit test for inputs like `hasNumericValue('2.3')` and `hasNumericValue('123ABC')`?

**Comment by Sathish-kumar-Subramani** [comment]
Thanks for your comments @josdejong 

I have never used Number object without the new operator. I checked the [MDN link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) and found that 

> In a non-constructor context (i.e., without the new operator), Number can be used to perform a type conversion.

wow! That just solves our problem. cheers !!!

P.S I have added a new case and commented it out. Should that pass?
`assert.strictEqual(hasNumericValue(' 2'), false)`

**Comment by josdejong** [comment]
Nice @Sathish-kumar-Subramani  :+1: 

> P.S I have added a new case and commented it out. Should that pass?
> assert.strictEqual(hasNumericValue(' 2'), false)

That is a good point! Yes, strings with whitespace around numbers like `" 2"` are also valid numbers, `math.number()` can turn these strings into a number.

**Comment by Sathish-kumar-Subramani** [comment]
Hi @josdejong,

I've added the test case.
Is there anything else?

**Comment by josdejong** [comment]
Thanks @Sathish-kumar-Subramani , looks good :+1:

**Comment by josdejong** [comment]
Fixed via https://github.com/josdejong/mathjs/commit/d0b1b5401ab09de35a7d5495238fead95ddd6423

Turns out IE11 doesn't support parsing a number like `'0b11'` and `'0o11'`, so I disabled these unit tests for now.

**Comment by Sathish-kumar-Subramani** [comment]
Does math.number() supports parsing `0b11` and `0o11` in IE ?
If yes, then hasNumericValue should also support in IE

**Comment by josdejong** [comment]
@sathish-kumar-subramani I've just released `v5.3.0` containing your new `hasNumericValue`. Sorry for the huge delay, I could have done a release way earlier.

**Comment by sathish-kumar-subramani** [comment]
@josdejong Thanks a lot for taking time to update me. I'm glad that my code has been released for public use :)

**Pull request merged**
