### PR TITLE
remove contributors from package.json in favour of AUTHORS

### PR DESCRIPTION
**Pull request by harrysarson**
The contributors section of our package.json is _very_ long and manually updating can be a pain.
I took a leaf out of nodejs's book and copied their update-authors script [1].

The new list is generated based on commits to the develop branch of mathjs (it is actually based on the current branch when the script is run) so the list is slightly different from the one from our package.json.

[1]: https://github.com/nodejs/node/blob/master/tools/update-authors.js

### CODE REVIEW

**Comment by harrysarson** [comment]
### Names present in package.json but not in commit logs

- Honybar (https://github.com/honeybar)
- Guillermo Indalecio Fernández (https://github.com/guillermobox)
- hamadu (https://github.com/hamadu)
- Huseyn Guliyev (https://github.com/husayt)
- Marcus Andre (https://github.com/marcusandre)
- Maxence Dalmais (https://github.com/maxired)
- mtraynham (https://github.com/mtraynham)
- Retsam (https://github.com/Retsam)
- Zach Zibrat (https://github.com/palimpsests)

Most of these names have corresponding names in AUTHORS (e.g. Zach Zibrat is Zak Zibrat). Huseyn Guiliyev loses out though because he is noted as a contributor (due to participation in a [number of issues](https://github.com/josdejong/mathjs/search?q=husayt&type=Issues) I think) but hasn't committed to mathjs. I do not know how we can fix this though.

**Comment by harrysarson** [comment]
### Names in AUTHORS that were not in package.json

 - 0xflotus <0xflotus@gmail.com>
 - Adam Butler <adam@lab.io>
 - Alex Edgcomb <alex.edgcomb@zyante.com>
 - Amin Abdul Manaf <afolanyaaminu@gmail.com>
 - Ben Nelson <Ben.Nelson@inin.com>
 - Clément P <yukulele@users.noreply.github.com>
 - Daniel Ruf <daniel@daniel-ruf.de>
 - Guillermo Indalecio <guillermobox@gmail.com>
 - Honeybar <verina_jean@hotmail.com>
 - J. Harshbarger <hypercubed@gmail.com>
 - Jack Mason <42824992+jackcmason@users.noreply.github.com>
 - James Herdman <james.herdman@gmail.com>
 - Jos de Jong <wjosdejong@gmail.com>
 - Kunal Vyas <kv.kunalvyas@gmail.com>
 - Liam Newman <bitwiseman@gmail.com>
 - Marcus André <hello@marcusandre.de>
 - Matt Traynham <mrt6467@alum.uncw.edu>
 - Max Kramer <mckramer@gmail.com>
 - Maximilian <mcschempp@gmx.de>
 - Maxired (Maxence Dalmais) <github@maxired.fr>
 - Nick Foti <nfoti01@gmail.com>
 - Ole Kröger <o.kroeger@wikunia.de>
 - Priidik Vaikla <priidik.vaikla@gmail.com>
 - Robin Wieruch <wrobin@gmx.net>
 - SzechuanSage <chris.hadgis@gmail.com>
 - Tomek Wiszniewski <t.wiszniewski@gmail.com>
 - Troy Alford <TroyAlford@users.noreply.github.com>
 - Ubuntu <ubuntu@ip-172-31-35-162.us-west-2.compute.internal>
 - Veaceslav Grimalschi <grimalschi@yandex.ru>
 - Victor <viclai@users.noreply.github.com>
 - Vincent Lee <ancienlee@live.com>
 - Zak Zibrat <zakzibrat@gmail.com>
 - hama_du <dercll1020@gmail.com>
 - jeffreyshen19 <jshen@andover.edu>
 - john marinelli <jonmarinelli@hotmail.com>
 - mocking <mocking@gmail.com>
 - oyvindjam <oyvindjam@gmail.com>
 - paulmasson <paulmasson@comcast.net>
 - pokeball99 <pokeball99@users.noreply.github.com>
 - sam-19 <sampsa.lohi@gmail.com>
 - viclai <victor1.lai@gmail.com>
 - woylie <woylie@users.noreply.github.com>

Some of these are legit AUTHORS whom we forgot to add to the package.json. There are also some duplicates that I haven't managed to mail map out. @josdejong you are also part of this list!

**Comment by josdejong** [comment]
Nice, I like it! It's indeed tricky not to forget to keep the list up to date.

Maybe we should run the `update-authors` script during `npm run build` so we can't forget running it?

**Comment by harrysarson** [comment]
If a person "John Smith"

a) makes a change
b) runs `npm run build-and-test`
c) commits that change
d) gets that commit merged into master (via a pull request)

the next time someone runs `npm run build-and-test` then "John Smith" will suddenly appear in the AUTHORS file. Would an explicit instruction in `how_to_publish.md` suffice?

**Comment by josdejong** [comment]
That's a good point. OK can you describe this step in the `how_to_publish.md` then please?

**Comment by harrysarson** [comment]
See https://github.com/josdejong/mathjs/pull/1774/commits/b2172a3107bb9123e6aa05d92829c48a53ad0b93

It looks like I typed the commit message out in a hurry, should probably say `add instruction to how_to_publish` instead. :man_shrugging:

**Comment by josdejong** [comment]
Thanks again Harry, I've merged your PR!

**Pull request merged**
