### PR TITLE
Modulo support for configurable definition, negative divisors

### PR DESCRIPTION
**Pull request by luke-gumbley**
Added three modulo function definitions
Permitted choosing preferred modulo via 'moduloFunc' config option
Removed exception for negative divisors
Preserved but noted current behaviour for divisor of 0
Modified and expanded tests to cover new functionality

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Luke, this looks neat, a nice addition.

One thing: as the configuration is specific to the function `mod`, it makes sense to me to pass it as an (optional) third argument instead of setting a global config variable, something like:

```js
math.mod(x, y)
math.mod(x, y, mode)
```

What do you think?

**Comment by luke-gumbley** [comment]
Fine by me! I'll switch that up tonight. I wanted to add Unit support as well anyway.

**Comment by josdejong** [comment]
If you use the expression parser you can pass an extra parameter with the mode too, right? Or do you mean something else? 

I think this is new option for `mod` is comparable to for example the function `log` where you can optionally specify the base, or `norm` where you can optionally specify what type of norm you want to calculate.

**Comment by luke-gumbley** [comment]
Updated to use a parameter after a lengthy digression into typed-function. Some hacky bits remain until 0.10.2 is released. The issue now is that I discovered Decimal.js uses a config option and Fraction.js has no support for custom modulo. For now there's a new hack in BigNumber.js.

Options:
1. Stick with parameter hacks for now and raise PR for Decimal.js and Fraction.js to add parameter support (happy to do this but it depends on the maintainers)
2. Go back to config option, optionally duplicate Decimal.js style ('modulo':1 = truncated, 3 = floored etc.)

Your thoughts?

**Comment by josdejong** [comment]
Thanks for the update Luke. I've just released `typed-function` v0.10.2, that should make things a bit easier :). 

I'm really in favor of passing the mode as a function parameter (`mod(x, y, mode)`) instead of a global config variable. 

It's logic that these modes are not supported right now by Decimal.js and Fraction.js. We can't be sure they will be supported in the future. For BigNumber.js we already have a lot of extensions, they are located in [/lib/utils/bignumber](https://github.com/josdejong/mathjs/tree/master/lib/utils/bignumber), and I think that's just fine. And if it's not easy to implement support for Fractions, it's fine if these modes are just not supported for Fraction, or maybe we can create our own implementation for this (similar to the util functions for Decimal.js).

**Comment by luke-gumbley** [comment]
Happy to stick with the parameter method, I was just pointing out that Decimal.js has already gone down the config route. Since [mathjs config is passed to Decimal](https://github.com/josdejong/mathjs/blob/master/lib/type/bignumber/BigNumber.js#L5), mathjs config of e.g. {modulo:3} already [changes the behaviour of mod](https://github.com/MikeMcl/decimal.js/blob/master/decimal.js#L3177) for BigNumbers.

Until I can get a PR into Decimal, that means that to support changing modulo with a parameter we need to use something like [this hacky override](https://github.com/luke-gumbley/mathjs/blob/17d148e4776245da18362a567afde7af544cf978/lib/type/bignumber/BigNumber.js#L55) that changes Decimal config, performs the modulo, and changes it back. That's why I suggested just using the same config option as Decimal (it'd be neater).

Back on typed-function for now, sorry about that...

**Comment by josdejong** [comment]
@luke-gumbley I see we didn't yet finish this PR but you did some additional commits. What's the status of it?

**Comment by gwhitney** [comment]
Was just looking at this because of closing #320, and I think it's obsolete and that mathjs now has the standard mathematical definition of mod, which it should stick with. So I recommend closing this.

**Comment by josdejong** [comment]
Ok sounds good @gwhitney , let's close this PR.

**Pull request closed without merging**
