### PR TITLE
Store uncompressed matricies and drop dev dep on tar and on q.

### PR DESCRIPTION
**Pull request by harrysarson**
git handles compression for us so compressing the matricies we use to test
is unnessessary. Additionally, handling the compression made the
code significantly more complex and required pulling in extra packages
from npm.

This commit updates the matrix market code to use uncompressed files.
I have also replaced use of the promise libary 'q' with built in
promises.

### CODE REVIEW

**Comment by harrysarson** [comment]
Pinging @rjbaucells as I believe you to be the original author of the code :)

**Comment by harrysarson** [comment]
It has just occurred to me that I have changed the API of a function that users could conceivably use. We should save this till the next major version.

**Comment by rjbaucells** [comment]
It is OK, just verify that the matrix market tool function is part of the API. If its is not, it is safe to merge.

**Comment by harrysarson** [comment]
Thanks!

**Comment by josdejong** [comment]
Good idea @harrysarson! 

The `tools` section is not part of the public API, its only for use with development. So I think it's safe to apply your changes. We could merge them though in big refactoring that I'm working on, that will be a major version bump anyway. Merging to `modular_architecture` will give some merge conflicts I think but should be merged in the end anyway.

**Comment by harrysarson** [comment]
I have changed the base to `modular_architecture` and cherry-picked my commit onto that branch. 👍

**Comment by josdejong** [comment]
Nice, thanks Harry :+1:

**Comment by harrysarson** [comment]
Just to check, you don't have a problem with forced pushes to branches of mathjs do you?

**Comment by josdejong** [comment]
No problem at all, if it helps us to do what we want to do. In general I try not to use any "fancy" git features though since that can easily go wrong too, I try to stick to just using basic git commit, push, pull, and branches and that's about it :)

**Pull request merged**
