### PR TITLE
add fraction support to intersect.js

### LINKED ISSUE #2291: intersect can also support fractions easily
All computation in intersect also work with fractions since they only use basic arithmetic commands. I tried to enable this by simply putting

```javascript
import { isBigNumber, isFraction } from '../../utils/is.js';
```
at the top and inserting ``|| isFraction(a)`` further down:
```javascript
  function _isNumeric(a) {
    // intersect supports numbers and bignumbers ((and maybe fractions!?))
    return typeof a === 'number' || isBigNumber(a) || isFraction(a);
  }
```
in ``intersect.js``. This works with all desired cases, e. g.
```javascript
intersect([1,-1,1], [2,0,2], [4, 0, 1], [2, 2, 5])
intersect([1,-1,1], [2,0,2], [4, 0, 1], [fraction(2,1), 2, 5])
```
Both return the correct result ``[3,1,3]``; the second call returns an array of fractions ``[3/1, 1/1, 3/1]`` (which is ok imho).

I don't really know what cases have to be tested so I thought I'd mention this as an easily implementable feature request, rather than providing a pull request.

### PR DESCRIPTION
**Pull request by thetazero**
Makes currently supported operations by `intersect.js` work for fractions. Had to catch a few potential divides by zeroes.

(Fixes #2291)

### CODE REVIEW

**Review by m93a — APPROVED** [review]

**Comment by m93a** [comment]
Looks good to me! What do you think @josdejong?

**Comment by josdejong** [comment]
Nice improvement, looks good. Thanks @thetazero . 

I think we can merge it as it is, but we could also go a little step further: replace the `_isNumeric` function with the official `isNumeric` function (inject it like `isZero`). And remove the `isFraction` occurrences: I think the `isZero` is what is important here and should apply to any numeric value, not just fractions. What do you think?

**Comment by thetazero** [comment]
@josdejong I think you're right, I've implemented your suggestions.

**Comment by josdejong** [comment]
Thanks, looks good 👍 

I see there is a linting issue, I'll merge your PR now and fix the linting afterwards, not a big deal.

**Pull request merged**
