### PR TITLE
Allow any vector in pickRandom function

### LINKED ISSUE #1974: `pickRandom` should not look at element types, in my opinion.
`pickRandom` wants a one-dimensional array.  I understand the design decision, but it still feels not so intuitive, I expect `pickRandom` to only look at the length of my array and then return the element at a random index.  So e.g. `math.pickRandom([[0, 1], [2, 3]])` should randomly return either `[0, 1]` or `[2, 3]`.  After all, `pickRandom([0, [1, 2], [3, 4]])` works as expected.  Even if we pretend that JS is a strictly typed language with no mixed arrays, I'd expect `pickRandom` to be of type `forall a. [a] -> M a` where `M` is a suitable monad.

### PR DESCRIPTION
**Pull request by KonradLinkowski**
Hello, let me know if anything is wrong :)
Fixes #1974

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Konrad for picking this up 👍 

We should think through what behavior we want. The current solution assumes an array, and picks a random element from the array. In mathjs you often have say a 2d matrix or array, and I think it makes more sense though to pick an element from the matrix instead of returning a row of the matrix. For example:

```js
// create a 2x2 array
const array = [
  [1, 2], 
  [3, 4]
]
math.pickRandom(array) 
// currently returns a "row": [1, 2] or [3, 4]
// I would expect it to return a value 1, 2, 3, or 4
```

I also noticed an unrelated bug that is already in the existing implementation:

```js
    if (length === 0) {
      return []
    } else if (number >= length) {
      return number > 1 ? possibles : possibles[0]
    }
```
This causes input like `pickRandom([1,2,3], 10)` to always return `[1, 2, 3]` without the result being random nor 10 values being returned. Maybe you can also have a look into this?

**Comment by KonradLinkowski** [comment]
@josdejong I tried to implement the behavior described in #1974 which was to pick any element from the array. So that's what I did, but it sure makes sense to behave differently in case of matrices.

**Comment by josdejong** [comment]
Yes indeed. I think this should be easy to achieve, by doing `possibles = flattenArray(possibles.valueOf())`

**Comment by KonradLinkowski** [comment]
I used `flatten`, but now in some tests I'm getting `AssertionError [ERR_ASSERTION]: Input objects identical but not reference equal` and it makes sense for me that the reference shouldn't be equal for example here `should return the given array if the given number is equal its length`, so probably tests are wrong.

**Comment by josdejong** [comment]
It could be that we need to change some tests.

**Comment by KonradLinkowski** [comment]
@josdejong 
Regarding
> This causes input like pickRandom([1,2,3], 10) to always return [1, 2, 3] without the result being random nor 10 values being returned. Maybe you can also have a look into this?

There is a test described as `should return the given array if the given number is greater than its length` so it's seems like this bug you mentioned is an intended behavior. I would rather change it in a different PR or even create an issue to change it.

**Comment by josdejong** [comment]
The flattening looks good, thanks 👍 

You're right about changing the behavior of `pickRandom`, we could consider it a breaking change in behavior. I've created a separate issue for it and we'll merge this into the first next breaking version `v8`.

**Comment by josdejong** [comment]
Improvement is now available in `v7.4.0` 🎉

**Comment by KonradLinkowski** [comment]
Hmm, so should I reopen this?

**Comment by josdejong** [comment]
?

**Comment by KonradLinkowski** [comment]
You didn't merged that

**Comment by josdejong** [comment]
😱 I'm not sure what went wrong there, sorry! I really thought I had pressed the merge button.

**Comment by KonradLinkowski** [comment]
Will fix this coverage today

**Comment by josdejong** [comment]
I think the code coverage change is false alarm

**Comment by josdejong** [comment]
Will merge now - for real 😉

**Comment by KonradLinkowski** [comment]
Thanks :)

**Comment by josdejong** [comment]
I'm glad you saw that I made a mistake here, thanks again!

**Comment by josdejong** [comment]
Available now in `v7.5.0`

**Comment by fweth** [comment]
Hi, I accidentally commented on the wrong issue before.  I just wanted to say that sometimes the behaviour of returning a vector instead of a value is what I prefer.  For example, when I store a set of points in a list, each point represented as 2-dim vector, I expect pickRandom to return a random point, not the position of a random point along a random axis.  Perhaps we could allow some property to distinguish n-dim arrays from lists of (n-1)-dim arrays.

**Comment by josdejong** [comment]
Thanks for your input @fweth , would be good to support both situations indeed. I think passing an option could be a solution here, in our case it's not possible I think to distinguish an n-dim array from a list with arrays, that will get confusing (mixing Arrays with Matrices etc).

See also #1990

**Comment by fweth** [comment]
Oh, I didn't realize that math.js already distinguishes between arrays and matrices.  Wouldn't it make sense then that pickRandom applied to a matrix returns a random entry (not random vector) but applied to array returns random element (no matter what type)?

**Comment by josdejong** [comment]
Hm, I think that would be confusing too. So far, the behavior of all functions is consistent independent of whether you're using an Array or a Matrix. Using either an Array or a Matrix is just a different "jacket" around the same data.

**Comment by KonradLinkowski** [comment]
@fweth @josdejong but it's working like that now after I added matrix flattening

**Comment by josdejong** [comment]
Yes I know, I hadn't expected this could impact how the function was used in practice.

**Comment by josdejong** [comment]
New option is published now in `v8.0.0` (see #1990 for details)

**Pull request merged**
