### PR TITLE
Multinomial

### PR DESCRIPTION
**Pull request by devanp92**
Adding support for [multinomial theorem](https://en.wikipedia.org/wiki/Multinomial_theorem).

### CODE REVIEW

**Comment by josdejong** [comment]
Interesting one, I will have a look at your code asap, thanks.

**Comment by josdejong** [comment]
Thanks Devan, looks good, with docs, unit tests and support for numbers and bignumbers. 

I saw the same issue here tough as pointed out here https://github.com/josdejong/mathjs/pull/350#issuecomment-100527873, maybe it's easiest to write a helper function `isPositiveInteger` which works for both numbers and BigNumbers.

**Comment by devanp92** [comment]
Ok, thanks for the input. I somewhat mocked the combinations.js function. It is written similarly [here](https://github.com/josdejong/mathjs/blob/master/lib/function/probability/combinations.js#L64). Though it does use

    if(k.gt(n)){...} //Line 67

Would using the same function (gt) be helpful in BellNumbers and StrilingS2. For example:

    if (n instanceof BigNumber && n.gt(0)) {...}

**Comment by josdejong** [comment]
Yes. This helper function could look something like:

```js
function isPositiveInteger (x) {
  if (isNumber(n) && isInteger(n) && n >= 0) {
    return true;
  }
  
  if (n instanceof BigNumber && n.isInteger() && n.gte(0)) {
    return true;
  }
  
  return false;
}
```

**Comment by josdejong** [comment]
@devanp92 shall we keep this PR and #350 open until you've completed BigNumber support?

**Comment by devanp92** [comment]
Fixed. Thank you for reminding me.

**Comment by josdejong** [comment]
Thanks, I've merged your PR. Will do a release today or tomorrow.

**Comment by josdejong** [comment]
Argh! there was already some `Permutation` Stuff in your clone. I've remove that for now. I also removed an unnecessary new depencency on `underscore` in the multinomial function.

**Pull request merged**
