### PR TITLE
Improvements to simplify

### PR DESCRIPTION
**Pull request by tetslee**
I couldn't see any work on simplifying expressions since Eric's work from #439, so I've implemented constant folding and started improving the term rewriting to work on commutative operators better. I also merged with v3.6.

There were a few issues that came up:

1. I felt that `math.eval` should always return a number rather than having a special case for the `simplify` and `derivative` functions, so I changed the way are used to this (curly braces are expression trees here):

`math.simplify('x+x')`                                       ->  {2*x}
`math.simplify('derivative(x^2+x, x)')`             ->  {2*x+1}
`math.parse('derivative(x^2+x, x)').eval({x:1})` ->  3
`math.parse('derivative(x^2+x, x)').simplify()` ->  {2*x+1}

2. You can also customize `simplify` by passing in your own set of rules:

`expr = math.parse('x+1+x')`
`expr.simplify(['c+v -> v+c'])`    ->  {x+x+1}
`expr.simplify(['n+n -> 2*n'])`   ->  {1+2*x}

The rules can also be functions. The constant folding function can be accessed from `math.algebra.simplify.simplifyConstant`.

3. I didn't think of a good way to decide whether or not operators are commutative and associative. For now, `multiply` and `add` operators are both hard coded as being commutative and associative, but that may not be true depending on the context.

4. The algorithm doesn't simplify across inverse operators. For instance, {x-1+x} will not simplify further.

5. I didn't try to deal with matrices and other things possible in mathjs, partly because of issue 3.

Another improvement could be to classify subtrees as rational functions and make use of something like [polynomial.js](https://github.com/infusion/Polynomial.js/) to simplify them.

I'm planning to clean some things up later but what do you think of these changes?

### CODE REVIEW

**Comment by ericman314** [comment]
@tetslee, thanks for bringing this all up to date. The associativity and commutivity of operators was what stumped me before. If you can figure it out, that's great!

**Comment by josdejong** [comment]
Awesome @tetslee , there have been some cool initiatives regarding algebraic computation (simplify, derivative), they have been paused for a while but it will be really great to work them out. Thanks for picking this up again! 

It's good to be aware that @evy (from Socratic) is doing algebraic stuff too. They're creating an extension for mathjs with a step solver: https://github.com/socraticorg/mathjs/tree/ek-mathsteps/lib/expression/step-solver. 

Regaring point 4: To solve this @evy normalizes inverse operations, rewrite `2 - 3 + 4` 
to `2 + -3 + 4`, and put it in a custom OperatorNode which can hold more than two arguments.

**Comment by tetslee** [comment]
Thanks for the feedback.

@ericman314, what you described with flattening trees then matching ordered pairs of arguments is pretty much how the term rewriting algorithm now works. Guess that was the obvious way to do it.
As to different simplified forms, it should be possible to create `expand` and `factor` functions by just passing custom rules to `simplify`. I've haven't given it much thought at this stage since I was thinking about replacing some of the rules with a rational expression simplifier which I think will be more reliable. 

@josdejong, I did what you said and added some rules to temporarily replace `subtract` and `divide` operators with their inverses. It works for the few cases I've tested. Thanks for pointing me to @evy's step solver, I'm also very interested in this.

I think I'm done with `simplify` for now, is there anything that needs cleaning up before it can be merged? Should I have updated to version 3.6 in a separate PR?

**Comment by josdejong** [comment]
Ok great @tetslee, I will merge your work now in the `algebraic_differentiation` branch. Your PR is a bit hard to read due to merging the latest master into the outdated branch but well we had to do that anyway, no problem :).

I will take some more time soon to play around with `simplify` extensively.

**Comment by husayt** [comment]
Hi @josdejong ,
when is the plan to merge this into master? This looks really solid.

Thanks

**Comment by josdejong** [comment]
I'm sorry I've been occupied with other things last months (time really flies). I definitely want to look at it soon!

**Comment by josdejong** [comment]
Ok finally working on it, see #779 :)

**Comment by josdejong** [comment]
@husayt I've released v3.9.0 with support for `simplify` and `derivative`. 

(In this regard you may also find [`mathsteps`](https://github.com/socraticorg/mathsteps) interesting, which is built on top of math.js and was officially launched last week.)

**Pull request merged**
