### PR TITLE
Fix #328 abs(0+0*i) evaluates to NaN

### LINKED ISSUE #328: abs(0 + 0i) evaluates to NaN
Attempting to evaluate abs(0 + 0i) returns NaN. This appears to be an unnoticed edge case in avoiding overflows when calculating the absolute value of a complex number.

abs(0 + 0i) should, obviously, return 0.

### PR DESCRIPTION
**Pull request by FSMaxB**
This is a quick fix. This might need a better solution though (
numerical instabilities still remain ).

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks. Are you aware of other possible edge cases?

**Comment by FSMaxB** [comment]
Not really, I haven't really looked into how this works mathematically, I just noticed that the code might try to divide by zero.

But values close to zero might be problematic ( numerical instability ).

**Comment by josdejong** [comment]
Ah, I get what you mean. Well, the algorithm was already improved in this regard a lot as you can see from the comment in the complex part of the function :).

**Comment by Lakedaemon** [comment]
On 04/22/2015 02:53 PM, Max Bruckner wrote:
>
> Not really, I haven't really looked into how this works 
> mathematically, I just noticed that the code might try to divide by zero.
>
> But values close to zero might be problematic ( numerical instability ).
>

when both values are small (say less than 1000), you could just use 
sqrt(x*x+y*y)
it avoids a division and should avoid numerical instability

**Comment by josdejong** [comment]
Done :)

**Pull request merged**
