### PR TITLE
WIP: Bump webpack to v5 (fixes #2050)

### LINKED ISSUE #2050: Upgrade to webpack 5
We need to upgrade the build process from Webpack 4 to Webpack 5. There are breaking changes, but I'm not sure if this will be simple or not.

Any help would be very welcome! Anyone interested?

### PR DESCRIPTION
**Pull request by flaviut**
Imports are required to be done a little differently, and there needs to be a "type: module" in the package.json

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks a lot Flaviu! I'm happily surprised that there are no config changes needed for webpack, looks quite straightforward.

A few small remarks:

1. I think the old `treeShakingApp.js` can be removed since you copied it to `./source`.
2. I think it will be wise not to switch to `karma-webpack@5.0.0-alpha.5` since it's an (unstable) alpha version, shall we await upgrading it until `v5.0.0` is published for real?

**Comment by flaviut** [comment]
> I think the old `treeShakingApp.js` can be removed since you copied it to `./source`.

It was, I think the github ui just didn't do a very good job making it clear.

> EDIT: or is the upgrade of karma needed to get the integration tests running?

I went through and bumped everything webpack related up--but it turns out that `karma-webpack` doesn't need to be updated yet, unless you're experiencing [these bugs](https://github.com/ryanclark/karma-webpack/issues/452). I've brought it back to v4, and `test:all` still works fine for me now.

**Comment by josdejong** [comment]
> It was, I think the github ui just didn't do a very good job making it clear.

Ah, now I see, you're right

I see all except one of the CI tests are green. Only "Browser testing locally / browser-tests (pull_request)" gives an error. The [logs say](https://github.com/josdejong/mathjs/pull/2066/checks?check_run_id=1600772922):

```
Cannot find plugin "/home/runner/work/mathjs/mathjs/node_modules/karma-webpack".
```

Which is just odd. When I run `npm run test:browser` locally I get an error which makes more sense:

```
> npm run test:browser

24 12 2020 08:51:57.789:ERROR [plugin]: Error during loading "...\mathjs\node_modules/karma-webpack" plugin:
  Cannot find module 'webpack/lib/dependencies/SingleEntryDependency'
```
Any ideas?

**Comment by josdejong** [comment]
Maybe we're hitting this issue: https://github.com/ryanclark/karma-webpack/issues/431

**Comment by josdejong** [comment]
I see some new commits here @flaviut , are you picking this up again? 

Pinging @JayFate, please be aware @flaviut was also working on this (see #2094)

**Comment by flaviut** [comment]
Yup, I've had some free time lately. No promises though--fixing issues arising from dependencies 5 levels down gets frustrating quickly :)

**Comment by josdejong** [comment]
Thanks @flaviut. Yes this stuff can be very frustrating indeed!!

**Comment by josdejong** [comment]
@flaviut just to be sure you're aware of it: you can run those browser tests locally via:

```
npm run test:browser
```

**Comment by flaviut** [comment]
Yup! I've been doing a bit of both—local tests, and in CI in order to make
sure the issues aren't just my local configuration being messed up.

If you're getting spammed by emails, I think you can unsubscribe to this PR
to get them to stop. I can email you (rather than post on GitHub) when this
is ready and you can take a look.

**Comment by gwhitney** [comment]
This appears to be superseded by a later PR, as mathjs@11.0.1 does use webpack 5. If you agree, feel free to close or let me know to.

**Comment by josdejong** [comment]
Yes 🎉  this has been addressed (it required to drop IE11 support)

**Pull request closed without merging**
