### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Mancalrod**
Adding a code of conduct for mathjs

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks. Where does your template come from? 

I see Github also offers two ready-made templates that I can insert.

**Comment by Mancalrod** [comment]
Hi Jos, we've drawn inspiration from the Contributor Covenant template but have made adjustments to enhance clarity and refine the wording according to our perspective.

**Comment by josdejong** [comment]
OK clear. I prefer using the standard version of Github, so it's recognizable for people and, well, a standard. 

https://github.com/josdejong/mathjs/community/code-of-conduct/new?template=contributor-covenant

Is that OK with you?

**Comment by josdejong** [comment]
Ok thanks. I've now added Github's standard CODE_OF_CONDUCT via 00583064edc231ab3ac8144f10663e2626ea1fae, I'll close this PR now.

**Pull request closed without merging**
